import {mkdtempSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {StateStore} from "@loom/state";
import {ControlPlaneService,ControlServer,hashOperatorToken,type ControlState} from "./index.js";

const servers:ControlServer[]=[];afterEach(async()=>{await Promise.all(servers.splice(0).map(server=>server.stop()))});
async function fixture(options:Record<string,unknown>={}){const state=new StateStore(":memory:");const raw="a".repeat(64);state.createOperatorCredential({id:"op1",name:"Operator",tokenHash:hashOperatorToken(raw)});const service=new ControlPlaneService(state as unknown as ControlState,{daemonStatus:()=>({running:true})});const server=new ControlServer(service,{port:0,...options});servers.push(server);await server.start();const address=server.address()!;const base=`http://127.0.0.1:${address.port}`;return {state,raw,server,base};}
async function login(base:string,raw:string){const response=await fetch(`${base}/api/v1/auth/login`,{method:"POST",headers:{Authorization:`Bearer ${raw}`}});const body=await response.json() as any;return {response,body,cookie:response.headers.get("set-cookie")!.split(";",1)[0]};}

describe("ControlServer",()=>{
 it("exchanges an operator token for an HttpOnly session and rotates CSRF",async()=>{const {base,raw}=await fixture();const logged=await login(base,raw);expect(logged.response.status).toBe(200);expect(logged.response.headers.get("set-cookie")).toContain("HttpOnly");expect(logged.response.headers.get("set-cookie")).toContain("SameSite=Strict");expect(logged.body.csrfToken).toBeTruthy();const session=await fetch(`${base}/api/v1/auth/session`,{headers:{Cookie:logged.cookie}});expect(session.status).toBe(200);const body=await session.json() as any;expect(body.csrfToken).not.toBe(logged.body.csrfToken);});
 it("rejects expired sessions",async()=>{let now=1000;const {base,raw}=await fixture({now:()=>now,sessionTtlMs:100});const logged=await login(base,raw);now=1200;const response=await fetch(`${base}/api/v1/summary`,{headers:{Cookie:logged.cookie}});expect(response.status).toBe(401);});
 it("denies viewer credentials mutation authority",async()=>{const {base,state}=await fixture();const viewer="v".repeat(64);state.createOperatorCredential({id:"viewer",name:"Viewer",role:"viewer",tokenHash:hashOperatorToken(viewer)});const logged=await login(base,viewer);const job=state.enqueueJob({type:"agent_run",payload:{goal:"test"}})!;const response=await fetch(`${base}/api/v1/jobs/${job.id}/cancel`,{method:"POST",headers:{Cookie:logged.cookie,Origin:base,"X-CSRF-Token":logged.body.csrfToken}});expect(response.status).toBe(403);expect(state.getJob(job.id)?.status).toBe("queued");expect(state.listOperatorAudit({action:"http.mutation_failed"})).toHaveLength(1);});
 it("requires exact Origin and CSRF for mutations and records audit",async()=>{const {base,raw,state}=await fixture();const logged=await login(base,raw);const job=state.enqueueJob({type:"agent_run",payload:{goal:"test"}})!;const missing=await fetch(`${base}/api/v1/jobs/${job.id}/cancel`,{method:"POST",headers:{Cookie:logged.cookie}});expect(missing.status).toBe(403);const wrong=await fetch(`${base}/api/v1/jobs/${job.id}/cancel`,{method:"POST",headers:{Cookie:logged.cookie,Origin:"https://evil.example","X-CSRF-Token":logged.body.csrfToken}});expect(wrong.status).toBe(403);const ok=await fetch(`${base}/api/v1/jobs/${job.id}/cancel`,{method:"POST",headers:{Cookie:logged.cookie,Origin:base,"X-CSRF-Token":logged.body.csrfToken}});expect(ok.status).toBe(200);expect(state.getJob(job.id)?.status).toBe("cancelled");expect(state.listOperatorAudit({action:"job.cancel"})).toHaveLength(1);});
 it("protects SSE with the session cookie and emits durable events",async()=>{const {base,raw,state}=await fixture({sseHeartbeatMs:20});const denied=await fetch(`${base}/api/v1/events`);expect(denied.status).toBe(401);const logged=await login(base,raw);state.appendControlEvent({type:"test.changed",resourceType:"job",resourceId:"j1"});const abort=new AbortController();const response=await fetch(`${base}/api/v1/events`,{headers:{Cookie:logged.cookie,Origin:base},signal:abort.signal});expect(response.status).toBe(200);expect(response.headers.get("content-type")).toContain("text/event-stream");const {value}=await response.body!.getReader().read();expect(new TextDecoder().decode(value)).toContain("event: invalidate");abort.abort();});
 it("rejects insecure non-local exposure",()=>{const state=new StateStore(":memory:");const service=new ControlPlaneService(state as unknown as ControlState);expect(()=>new ControlServer(service,{host:"0.0.0.0",publicOrigin:"http://example.test"})).toThrow(/non-local/);expect(()=>new ControlServer(service,{host:"0.0.0.0",publicOrigin:"https://example.test",cookieSecure:true,allowedOrigins:["https://example.test"],tls:{key:"key",cert:"cert"}})).not.toThrow();});
 it("sets security headers and safely serves the SPA",async()=>{const root=mkdtempSync(join(tmpdir(),"loom-control-"));writeFileSync(join(root,"index.html"),"<main>loom</main>");const {base}=await fixture({webRoot:root});const response=await fetch(`${base}/dashboard`,{headers:{Accept:"text/html"}});expect(await response.text()).toContain("loom");expect(response.headers.get("content-security-policy")).toContain("frame-ancestors 'none'");expect(response.headers.get("x-content-type-options")).toBe("nosniff");const traversal=await fetch(`${base}/%2e%2e/%2e%2e/etc/passwd`);expect(traversal.status).not.toBe(200);});
});
