import {createHash,randomBytes,randomUUID,timingSafeEqual} from "node:crypto";
import {createReadStream,realpathSync,statSync} from "node:fs";
import {createServer,type IncomingMessage,type Server,type ServerResponse} from "node:http";
import {createServer as createHttpsServer} from "node:https";
import type {AddressInfo} from "node:net";
import {extname,relative,resolve} from "node:path";
import {ControlPlaneService,number,object} from "./service.js";
import type {ControlEvent,ControlOptions,OperatorSession,RateLimitOptions} from "./types.js";

const jsonType="application/json; charset=utf-8";
const mimes:Record<string,string>={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":jsonType,".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2"};
export const hashOperatorToken=(token:string)=>createHash("sha256").update(token).digest("hex");
const safeEqual=(a:string,b:string)=>{const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);};
const token=()=>randomBytes(32).toString("base64url");
const safeId=(id:string)=>/^[A-Za-z0-9_.:-]{1,160}$/.test(id);
class HttpError extends Error {constructor(readonly status:number,readonly code:string,message:string){super(message)}}
class Limiter {private hits=new Map<string,{start:number,count:number}>();constructor(private readonly options:RateLimitOptions,private readonly now:()=>number){} check(key:string,auth=false){const window=auth?this.options.authWindowMs:this.options.windowMs,max=auth?this.options.authMax:this.options.max,now=this.now();let hit=this.hits.get(key);if(!hit||now-hit.start>=window){hit={start:now,count:0};this.hits.set(key,hit)}hit.count++;if(this.hits.size>this.options.maxKeys){for(const [k,v] of this.hits)if(now-v.start>=window)this.hits.delete(k);while(this.hits.size>this.options.maxKeys)this.hits.delete(this.hits.keys().next().value!)}return hit.count>max?Math.max(1,Math.ceil((window-(now-hit.start))/1000)):0}}

type Context={requestId:string,session?:OperatorSession,actorId?:string};
export class ControlServer {
 private server?:Server;private readonly now:()=>number;private readonly limits:Limiter;private readonly options:Required<Omit<ControlOptions,"webRoot"|"publicOrigin"|"allowedOrigins"|"tls"|"rateLimit">>&Pick<ControlOptions,"webRoot"|"publicOrigin"|"allowedOrigins"|"tls">;private sseClients=0;private readonly sseResponses=new Set<ServerResponse>();private readonly sseSessions=new Map<ServerResponse,string>();
 constructor(readonly service:ControlPlaneService,options:ControlOptions={}){this.now=options.now??Date.now;const rate={windowMs:60_000,max:180,authWindowMs:60_000,authMax:10,maxKeys:10_000,...options.rateLimit};this.limits=new Limiter(rate,this.now);this.options={host:options.host??"127.0.0.1",port:options.port??0,webRoot:options.webRoot,publicOrigin:options.publicOrigin,allowedOrigins:options.allowedOrigins,tls:options.tls,readOnly:options.readOnly??false,sessionTtlMs:options.sessionTtlMs??8*60*60_000,sessionIdleMs:options.sessionIdleMs??30*60_000,cookieSecure:options.cookieSecure??options.publicOrigin?.startsWith("https://")??false,bodyLimitBytes:options.bodyLimitBytes??64*1024,requestTimeoutMs:options.requestTimeoutMs??15_000,maxSseClients:options.maxSseClients??100,sseHeartbeatMs:options.sseHeartbeatMs??15_000,now:this.now};const local=["127.0.0.1","::1","localhost"].includes(this.options.host);if(!local){const origin=options.publicOrigin?normalizeOrigin(options.publicOrigin):undefined;if(!origin?.startsWith("https://")||this.options.cookieSecure!==true||!options.allowedOrigins?.map(normalizeOrigin).includes(origin)||!options.tls?.key||!options.tls?.cert)throw new Error("non-local control-plane exposure requires TLS, HTTPS publicOrigin, secure cookies, and an explicit exact origin allowlist");}}
 async start(){if(this.server)return;this.server=(this.options.tls?createHttpsServer(this.options.tls,(req,res)=>void this.handle(req,res)):createServer((req,res)=>void this.handle(req,res)));this.server.requestTimeout=this.options.requestTimeoutMs;await new Promise<void>((ok,bad)=>{this.server!.once("error",bad);this.server!.listen(this.options.port,this.options.host,ok)});}
 address(){return this.server?.address() as AddressInfo|undefined;}
 async stop(){if(!this.server)return;const server=this.server;this.server=undefined;for(const response of this.sseResponses)response.end();this.sseResponses.clear();this.sseSessions.clear();await new Promise<void>((ok,bad)=>server.close(e=>e?bad(e):ok()));}
 private origins(){if(this.options.allowedOrigins)return this.options.allowedOrigins.map(normalizeOrigin);if(this.options.publicOrigin)return [normalizeOrigin(this.options.publicOrigin)];const a=this.address();return a?[`http://${a.address.includes(":")?`[${a.address}]`:a.address}:${a.port}`]:[];}
 private headers(res:ServerResponse,requestId:string,origin?:string){res.setHeader("X-Request-Id",requestId);res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()");res.setHeader("Content-Security-Policy","default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'");res.setHeader("Cross-Origin-Resource-Policy","same-origin");if(this.options.cookieSecure)res.setHeader("Strict-Transport-Security","max-age=31536000");if(origin){try{if(this.origins().includes(normalizeOrigin(origin))){res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Access-Control-Allow-Credentials","true");res.setHeader("Vary","Origin")}}catch{}}}
 private async handle(req:IncomingMessage,res:ServerResponse){const ctx:Context={requestId:`req_${randomUUID()}`},ip=req.socket.remoteAddress??"unknown";this.headers(res,ctx.requestId,req.headers.origin);try{const url=new URL(req.url??"/","http://local");const retry=this.limits.check(ip,url.pathname==="/api/v1/auth/login");if(retry){res.setHeader("Retry-After",String(retry));throw new HttpError(429,"rate_limited","too many requests")}
   if(req.method==="OPTIONS")return this.optionsResponse(req,res);
   if(url.pathname==="/api/v1/auth/login"&&req.method==="POST")return await this.login(req,res,ctx,ip);
   if(url.pathname==="/api/v1/health"&&req.method==="GET")return this.send(res,200,await this.service.health());
   if(url.pathname.startsWith("/api/")||url.pathname==="/api/v1/events"){ctx.session=this.authenticate(req);ctx.actorId=ctx.session.credentialId;const sessionRetry=this.limits.check(`session:${ctx.session.id}`);if(sessionRetry){res.setHeader("Retry-After",String(sessionRetry));throw new HttpError(429,"rate_limited","too many requests")}}
   if(url.pathname==="/api/v1/auth/session"&&req.method==="GET")return this.session(res,ctx.session!);
   if(url.pathname==="/api/v1/auth/logout"&&req.method==="POST"){this.mutationGuard(req,ctx.session!,false);this.service.revokeSession(ctx.session!.id,this.now());for(const [stream,sessionId] of this.sseSessions)if(sessionId===ctx.session!.id)stream.end();this.audit(ctx,req,ip,"auth.logout","session",ctx.session!.id,"success",204);this.clearCookie(res);return this.send(res,204);}
   if(url.pathname==="/api/v1/events"&&req.method==="GET")return this.events(req,res,url,ctx.session!);
   if(url.pathname.startsWith("/api/v1/"))return await this.api(req,res,url,ctx,ip);
   if(req.method==="GET"||req.method==="HEAD")return this.static(req,res,url);
   throw new HttpError(404,"not_found","route not found");
 }catch(error){const status=error instanceof HttpError?error.status:typeof (error as any)?.status==="number"?(error as any).status:500;if(ctx.session&&["POST","PATCH","DELETE"].includes(req.method??"")){try{this.audit(ctx,req,ip,"http.mutation_failed",undefined,undefined,status<500?"denied":"error",status)}catch{}}this.error(res,error,ctx.requestId)}}
 private authenticate(req:IncomingMessage){const raw=cookie(req,this.options.cookieSecure?"__Host-loom_session":"loom_session");if(!raw)throw new HttpError(401,"unauthorized","authentication required");const session=this.service.getSession(hashOperatorToken(raw));const now=this.now();const credential=session?this.service.credential(session.credentialId):undefined;if(!session||!credential?.enabled||session.revokedAt||session.expiresAt<=now||now-session.lastSeenAt>this.options.sessionIdleMs)throw new HttpError(401,"session_expired","session expired");this.service.touchSession(session.id,now);session.lastSeenAt=now;return session;}
 private async login(req:IncomingMessage,res:ServerResponse,ctx:Context,ip:string){this.assertOriginIfPresent(req);const auth=req.headers.authorization;if(!auth||Array.isArray(auth)||!auth.startsWith("Bearer ")||auth.includes(",")){this.audit(ctx,req,ip,"auth.login",undefined,undefined,"denied",401);throw new HttpError(401,"invalid_credentials","invalid credentials")}const raw=auth.slice(7);if(raw.length<32){this.audit(ctx,req,ip,"auth.login",undefined,undefined,"denied",401);throw new HttpError(401,"invalid_credentials","invalid credentials")}const hash=hashOperatorToken(raw),credential=this.service.credentialByTokenHash(hash);if(!credential?.enabled||!safeEqual(hash,credential.tokenHash)){this.audit(ctx,req,ip,"auth.login",undefined,undefined,"denied",401);throw new HttpError(401,"invalid_credentials","invalid credentials")}const sid=token(),csrf=token(),now=this.now(),id=`session_${randomUUID()}`;const session=this.service.createSession({id,credentialId:credential.id,sessionHash:hashOperatorToken(sid),csrfHash:hashOperatorToken(csrf),createdAt:now,lastSeenAt:now,expiresAt:now+this.options.sessionTtlMs});ctx.session=session;ctx.actorId=credential.id;this.setCookie(res,sid);this.audit(ctx,req,ip,"auth.login","session",id,"success",200);return this.send(res,200,{authenticated:true,user:{id:credential.id,name:credential.name,role:credential.role??"operator"},operator:{id:credential.id,name:credential.name},csrfToken:csrf,expiresAt:session.expiresAt});}
 private session(res:ServerResponse,session:OperatorSession){const csrf=token(),now=this.now(),credential=this.service.credential(session.credentialId);this.service.rotateSessionCsrf(session.id,hashOperatorToken(csrf),now);return this.send(res,200,{authenticated:true,user:{id:session.credentialId,name:credential?.name,role:credential?.role},operatorId:session.credentialId,csrfToken:csrf,expiresAt:session.expiresAt});}
 private mutationGuard(req:IncomingMessage,session:OperatorSession,enforceReadOnly=true){const credential=this.service.credential(session.credentialId);if(enforceReadOnly&&(!credential?.enabled||credential.role==="viewer"))throw new HttpError(403,"insufficient_role","operator role required");if(enforceReadOnly&&this.options.readOnly)throw new HttpError(403,"read_only","control plane is read-only");const origin=req.headers.origin;if(!origin||!this.origins().includes(normalizeOrigin(origin)))throw new HttpError(403,"invalid_origin","origin rejected");const csrf=req.headers["x-csrf-token"];if(typeof csrf!=="string"||!safeEqual(hashOperatorToken(csrf),session.csrfHash))throw new HttpError(403,"invalid_csrf","CSRF token rejected");}
 private assertOriginIfPresent(req:IncomingMessage){const origin=req.headers.origin;if(origin&&!this.origins().includes(normalizeOrigin(origin)))throw new HttpError(403,"invalid_origin","origin rejected");}
 private async api(req:IncomingMessage,res:ServerResponse,url:URL,ctx:Context,ip:string){const path=url.pathname.slice("/api/v1".length),method=req.method??"GET";let match:RegExpMatchArray|null;let result:unknown;
   if((path==="/summary"||path==="/dashboard")&&method==="GET")result=await this.service.summary();
   else if(path==="/agents"&&method==="GET")result=this.service.agents(url.searchParams);
   else if((match=path.match(/^\/agents\/([^/]+)\/(tasks|plan|reviews|trace)$/))&&method==="GET"){const agentId=id(match[1]);result=found(match[2]==="tasks"?this.service.agentTasks(agentId):match[2]==="plan"?this.service.agentPlan(agentId):match[2]==="reviews"?this.service.agentReviews(agentId):this.service.agentTraces(agentId,number(url.searchParams.get("limit"),1,500)??100,url.searchParams.get("rootTimeline")==="true"));}
   else if((match=path.match(/^\/agents\/([^/]+)$/))&&method==="GET")result=found(this.service.agent(id(match[1])));
   else if(path==="/jobs"&&method==="GET")result=this.service.jobs(url.searchParams);
   else if((match=path.match(/^\/jobs\/([^/]+)$/))&&method==="GET")result=found(this.service.job(id(match[1])));
   else if((match=path.match(/^\/jobs\/([^/]+)\/(cancel|retry)$/))&&method==="POST"){this.mutationGuard(req,ctx.session!);result=match[2]==="cancel"?this.service.cancelJob(id(match[1])):this.service.retryJob(id(match[1]));this.changed(ctx,req,ip,`job.${match[2]}`,"job",match[1],result);}
   else if(path==="/schedules"&&method==="GET")result=this.service.schedules();
   else if(path==="/schedules"&&method==="POST"){this.mutationGuard(req,ctx.session!);result=this.service.createSchedule(object(await this.body(req)));this.changed(ctx,req,ip,"schedule.create","schedule",resourceId(result),result);}
   else if((match=path.match(/^\/schedules\/([^/]+)$/))&&method==="GET")result=found(this.service.schedule(id(match[1])));
   else if((match=path.match(/^\/schedules\/([^/]+)$/))&&method==="DELETE"){this.mutationGuard(req,ctx.session!);result=this.service.deleteSchedule(id(match[1]));this.changed(ctx,req,ip,"schedule.delete","schedule",match[1],result);}
   else if((match=path.match(/^\/schedules\/([^/]+)\/(pause|resume)$/))&&method==="POST"){this.mutationGuard(req,ctx.session!);result=match[2]==="resume"?this.service.resumeSchedule(id(match[1])):this.service.pauseSchedule(id(match[1]));this.changed(ctx,req,ip,`schedule.${match[2]}`,"schedule",match[1],result);}
   else if(path==="/approvals"&&method==="GET")result=this.service.approvals(url.searchParams);
   else if((match=path.match(/^\/approvals\/([^/]+)$/))&&method==="GET")result=found(this.service.approval(id(match[1])));
   else if((match=path.match(/^\/approvals\/([^/]+)\/(approve|deny)$/))&&method==="POST"){this.mutationGuard(req,ctx.session!);result=await this.service.decideApproval(id(match[1]),match[2]==="approve"?"approved":"denied");this.changed(ctx,req,ip,`approval.${match[2]}`,"approval",match[1],result);}
   else if(path==="/workers"&&method==="GET")result=this.service.workers();
   else if((match=path.match(/^\/workers\/([^/]+)\/(assignments|leases)$/))&&method==="GET")result=match[2]==="assignments"?this.service.workerAssignments(id(match[1])):this.service.workerLeases(id(match[1]));
   else if((match=path.match(/^\/workers\/([^/]+)\/(assignments|leases)$/))&&method==="GET")result=match[2]==="assignments"?this.service.workerAssignments(id(match[1])):this.service.workerLeases(id(match[1]));
   else if((match=path.match(/^\/workers\/([^/]+)$/))&&method==="GET")result=found(this.service.worker(id(match[1])));
   else if((path==="/remote/assignments"||path==="/remote-assignments")&&method==="GET")result=this.service.assignments(url.searchParams);
   else if((match=path.match(/^\/remote(?:\/assignments|-assignments)\/([^/]+)$/))&&method==="GET")result=found(this.service.assignment(id(match[1])));
   else if(path==="/traces"&&method==="GET")result=this.service.traces(url.searchParams);
   else if((match=path.match(/^\/traces\/([^/]+)$/))&&method==="GET")result=this.service.agentTraces(id(match[1]),number(url.searchParams.get("limit"),1,500)??100,true);
   else if(path==="/audit"&&method==="GET")result=this.service.audit(url.searchParams);
   else if(path==="/routes"&&method==="GET")result=await this.service.routes();
   else if(path.startsWith("/routes/")&&method==="GET")result=found(await this.service.route(decodeURIComponent(path.slice("/routes/".length))));
   else throw new HttpError(404,"not_found","route not found");
   return this.send(res,200,result);
 }
 private changed(ctx:Context,req:IncomingMessage,ip:string,action:string,type:string,rid:string|undefined,_data:unknown){this.audit(ctx,req,ip,action,type,rid,"success",200);}
 private audit(ctx:Context,req:IncomingMessage,ip:string,action:string,type:string|undefined,rid:string|undefined,outcome:"success"|"denied"|"error",status:number){this.service.recordAudit({requestId:ctx.requestId,actorId:ctx.actorId,sessionFingerprint:ctx.session?.sessionHash.slice(0,16),action,resourceType:type,resourceId:rid,outcome,httpStatus:status,sourceAddress:ip,details:{method:req.method},createdAt:this.now()});}
 private events(req:IncomingMessage,res:ServerResponse,url:URL,session:OperatorSession){this.assertOriginIfPresent(req);if(this.sseClients>=this.options.maxSseClients)throw new HttpError(503,"sse_capacity","event stream capacity reached");this.sseClients++;this.sseResponses.add(res);this.sseSessions.set(res,session.id);res.statusCode=200;res.setHeader("Content-Type","text/event-stream; charset=utf-8");res.setHeader("Cache-Control","no-store, no-transform");res.setHeader("Connection","keep-alive");res.setHeader("X-Accel-Buffering","no");res.flushHeaders();let after=number(req.headers["last-event-id"] as string??url.searchParams.get("after"),0,Number.MAX_SAFE_INTEGER)??0;let draining=false;const flush=()=>{if(draining)return;for(const event of this.service.controlEvents({afterId:after,limit:200})){after=event.id;if(!writeEvent(res,event)){draining=true;res.once("drain",()=>{draining=false;flush()});break}}};flush();const poll=setInterval(flush,1000),heartbeat=setInterval(()=>{const current=this.service.getSession(session.sessionHash),now=this.now();if(!current||!this.service.credential(current.credentialId)?.enabled||current.revokedAt||current.expiresAt<=now||now-current.lastSeenAt>this.options.sessionIdleMs)return res.end();res.write(`: heartbeat ${now}\n\n`)},this.options.sseHeartbeatMs);let closed=false;const close=()=>{if(closed)return;closed=true;clearInterval(poll);clearInterval(heartbeat);this.sseClients--;this.sseResponses.delete(res);this.sseSessions.delete(res)};req.once("close",close);res.once("close",close);}
 private async body(req:IncomingMessage){const type=req.headers["content-type"]?.split(";",1)[0].trim().toLowerCase();if(type!=="application/json")throw new HttpError(415,"unsupported_media_type","application/json required");const chunks:Buffer[]=[];let size=0;for await(const raw of req){const chunk=Buffer.from(raw);size+=chunk.length;if(size>this.options.bodyLimitBytes)throw new HttpError(413,"body_too_large","request body too large");chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"))}catch{throw new HttpError(400,"invalid_json","invalid JSON")}}
 private static(req:IncomingMessage,res:ServerResponse,url:URL){if(!this.options.webRoot)throw new HttpError(404,"not_found","route not found");let pathname:string;try{pathname=decodeURIComponent(url.pathname)}catch{throw new HttpError(400,"invalid_path","invalid path")};if(pathname.includes("\0"))throw new HttpError(400,"invalid_path","invalid path");const root=resolve(this.options.webRoot),candidate=resolve(root,`.${pathname}`);let file=candidate;const rel=relative(root,candidate);if(rel.startsWith("..")||rel.includes("..")||resolve(root,rel)!==candidate)throw new HttpError(403,"path_forbidden","path rejected");try{if(statSync(file).isDirectory())file=resolve(file,"index.html");if(!statSync(file).isFile())throw new Error()}catch{if(extname(pathname)||!String(req.headers.accept??"").includes("text/html"))throw new HttpError(404,"not_found","asset not found");file=resolve(root,"index.html");try{if(!statSync(file).isFile())throw new Error()}catch{throw new HttpError(404,"not_found","asset not found")}}const realRoot=realpathSync(root),realFile=realpathSync(file),realRel=relative(realRoot,realFile);if(realRel.startsWith("..")||resolve(realRoot,realRel)!==realFile)throw new HttpError(403,"path_forbidden","path rejected");file=realFile;res.statusCode=200;res.setHeader("Content-Type",mimes[extname(file)]??"application/octet-stream");res.setHeader("Cache-Control",extname(file)===".html"?"no-store":"public, max-age=31536000, immutable");if(req.method==="HEAD")return res.end();createReadStream(file).on("error",()=>res.destroy()).pipe(res);}
 private optionsResponse(req:IncomingMessage,res:ServerResponse){const origin=req.headers.origin;if(!origin||!this.origins().includes(normalizeOrigin(origin)))throw new HttpError(403,"invalid_origin","origin rejected");res.statusCode=204;res.setHeader("Access-Control-Allow-Methods","GET, POST, PATCH, DELETE, OPTIONS");res.setHeader("Access-Control-Allow-Headers","Authorization, Content-Type, X-CSRF-Token");res.setHeader("Access-Control-Max-Age","600");res.end();}
 private setCookie(res:ServerResponse,value:string){const name=this.options.cookieSecure?"__Host-loom_session":"loom_session";res.setHeader("Set-Cookie",`${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${Math.floor(this.options.sessionTtlMs/1000)}${this.options.cookieSecure?"; Secure":""}`)}
 private clearCookie(res:ServerResponse){const name=this.options.cookieSecure?"__Host-loom_session":"loom_session";res.setHeader("Set-Cookie",`${name}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${this.options.cookieSecure?"; Secure":""}`)}
 private send(res:ServerResponse,status:number,value?:unknown){res.statusCode=status;res.setHeader("Cache-Control","no-store");if(status===204)return res.end();res.setHeader("Content-Type",jsonType);res.end(JSON.stringify(value??null));}
 private error(res:ServerResponse,error:unknown,requestId:string){if(res.headersSent){res.destroy();return}const status=typeof(error as any)?.status==="number"?(error as any).status:500,code=typeof(error as any)?.code==="string"?(error as any).code:"internal_error",message=status===500?"internal server error":String((error as any)?.message??"request failed");this.send(res,status,{error:{code,message,requestId},message});}
}
function cookie(req:IncomingMessage,name:string){const values=(req.headers.cookie??"").split(";").map(x=>x.trim()).filter(x=>x.startsWith(`${name}=`));if(values.length>1)throw new HttpError(400,"invalid_cookie","duplicate session cookie");return values[0]?.slice(name.length+1)}
function normalizeOrigin(origin:string){try{const u=new URL(origin);if(u.origin==="null"||u.pathname!=="/"||u.search||u.hash||u.username||u.password)throw new Error();return u.origin}catch{throw new HttpError(403,"invalid_origin","origin rejected")}}
function id(raw:string){let value:string;try{value=decodeURIComponent(raw)}catch{throw new HttpError(400,"invalid_id","invalid resource id")};if(!safeId(value))throw new HttpError(400,"invalid_id","invalid resource id");return value}
function found<T>(value:T|undefined|null){if(value===undefined||value===null)throw new HttpError(404,"not_found","resource not found");return value}
function resourceId(value:unknown){return value&&typeof value==="object"&&"id" in value?String((value as any).id):undefined}
function writeEvent(res:ServerResponse,event:ControlEvent){const data=JSON.stringify(event);return res.write(`id: ${event.id}\nevent: invalidate\ndata: ${data}\n\n`)}
