import type {ControlProviders,ControlState} from "./types.js";

const apiError=(message:string,status:number,code:string)=>Object.assign(new Error(message),{status,code});
const parseJson=(value:unknown)=>{if(typeof value!=="string")return value;try{return JSON.parse(value);}catch{return value;}};
const normalize=(value:any)=>value&&typeof value==="object"&&"payload" in value?{...value,payload:parseJson(value.payload)}:value;
export class ControlPlaneService {
 private readonly startedAt=Date.now();
 constructor(readonly state:ControlState,private readonly providers:ControlProviders={}){}
 credentialByTokenHash(hash:string){return this.state.findOperatorCredentialByTokenHash(hash);}
 credential(id:string){return this.state.getOperatorCredential?.(id);}
 createSession(input:Parameters<ControlState["createOperatorSession"]>[0]){return this.state.createOperatorSession(input);}
 getSession(hash:string){return this.state.getOperatorSession(hash);}
 rotateSessionCsrf(id:string,hash:string,lastSeenAt:number){return this.state.rotateOperatorSessionCsrf(id,hash,lastSeenAt);}
 touchSession(id:string,at:number){return this.state.touchOperatorSession?.(id,at);}
 revokeSession(id:string,at?:number){return this.state.revokeOperatorSession(id,at);}
 recordAudit(input:Parameters<ControlState["recordOperatorAudit"]>[0]){return this.state.recordOperatorAudit(input);}
 controlEvents(input?:Parameters<ControlState["listControlEvents"]>[0]){return this.state.listControlEvents(input);}
 async health(){const daemon=await this.providers.daemonStatus?.();return {status:"ok",version:this.providers.version??"0.9.0",apiVersion:"v1",daemonId:daemon?.daemonId??this.providers.daemonId??null,uptimeMs:Math.max(0,Date.now()-(daemon?.startedAt??this.startedAt))};}
 async summary(){const [daemon,bots]=await Promise.all([this.providers.daemonStatus?.(),this.providers.bots?.()]);const jobs=this.state.listJobs(),agents=this.state.listAgents(),workers=this.state.listWorkers(),approvals=this.state.listApprovals(),assignments=this.state.listRemoteAssignments(),schedules=this.state.listSchedules(),roots=agents.filter((agent:any)=>agent.id===agent.rootAgentId),enabled=schedules.filter((schedule:any)=>schedule.enabled);return {daemon:daemon??null,bots:bots??null,counts:{agents:agents.length,activeRoots:roots.filter((agent:any)=>["created","running","waiting","recovering"].includes(agent.status)).length,jobs:jobs.length,failedJobs:jobs.filter((job:any)=>job.status==="failed").length,waitingApprovals:approvals.filter((approval:any)=>approval.status==="pending").length,pendingApprovals:approvals.filter((approval:any)=>approval.status==="pending").length,workers:workers.length,connectedWorkers:workers.filter((worker:any)=>worker.status==="online").length,activeRemoteAssignments:assignments.filter((assignment:any)=>["assigned","dispatched","accepted","running"].includes(assignment.status)).length,schedules:schedules.length,bots:Array.isArray(bots)?bots.length:0},jobs:{queued:jobs.filter((job:any)=>job.status==="queued").length,running:jobs.filter((job:any)=>job.status==="running"||job.status==="claimed").length,failed:jobs.filter((job:any)=>job.status==="failed").length},nextSchedule:enabled.sort((a:any,b:any)=>(a.nextRunAt??Infinity)-(b.nextRunAt??Infinity))[0]??null,recentFailures:jobs.filter((job:any)=>job.status==="failed").slice(-10).reverse()};}
 agents(query:URLSearchParams){let rows=this.state.listAgents(query.get("rootAgentId")??undefined);for(const key of ["status","role","parentAgentId"] as const){const value=query.get(key);if(value)rows=rows.filter((row:any)=>row[key]===value);}const after=query.get("createdAfter");if(after)rows=rows.filter((row:any)=>Date.parse(row.createdAt)>Date.parse(after));return paginate(rows,query).map(normalize);}
 agent(id:string){const agent=this.state.getAgent(id);if(!agent)return undefined;const rootId=agent.rootAgentId??agent.id,plan=this.state.getPlanForAgent?.(rootId);return {agent,children:this.state.listChildren(id),delegations:this.state.listDelegations(id),artifacts:this.state.listArtifactsForRoot?.(rootId)??this.state.listArtifacts(id),plan,tasks:plan?this.state.listPlanTasks?.(plan.id)??[]:[]};}
 agentTasks(id:string){const agent=this.state.getAgent(id);if(!agent)return undefined;const plan=this.state.getPlanForAgent?.(agent.rootAgentId??agent.id);return plan?this.state.listPlanTasks?.(plan.id)??[]:[];}
 agentPlan(id:string){const agent=this.state.getAgent(id);if(!agent)return undefined;const plan=this.state.getPlanForAgent?.(agent.rootAgentId??agent.id);return plan?{plan,revisions:this.state.listPlanRevisions?.(plan.id)??[]}:null;}
 agentReviews(id:string){const tasks=this.agentTasks(id);if(!tasks)return undefined;return tasks.flatMap((task:any)=>(this.state.listReviews?.(task.id)??[]).map((review:any)=>({...review,taskId:task.id})));}
 agentTraces(id:string,limit:number,rootTimeline=false){return this.state.getTrace(id,rootTimeline).slice(-limit);}
 jobs(query:URLSearchParams){return paginate(this.state.listJobs(query.get("status")??undefined),query).map(normalize);}
 job(id:string){return normalize(this.state.getJob(id));}
 cancelJob(id:string){const exists=this.state.getJob(id);if(!exists)throw apiError("job not found",404,"job_not_found");try{const result=this.providers.actions?.cancelJob?.(id)??this.state.cancelJob?.(id);if(result)return normalize(result);}catch{}throw apiError("job cannot be cancelled",409,"invalid_state");}
 retryJob(id:string){const exists=this.state.getJob(id);if(!exists)throw apiError("job not found",404,"job_not_found");try{const result=this.providers.actions?.retryJob?.(id)??this.state.retryJob?.(id);if(result)return normalize(result);}catch{}throw apiError("job cannot be retried",409,"invalid_state");}
 schedules(){return this.state.listSchedules().map(normalize);}
 schedule(id:string){return normalize(this.state.getSchedule(id));}
 createSchedule(input:any){validateSchedule(input);try{return normalize(this.providers.actions?.createSchedule?.(input)??this.state.createSchedule(input));}catch{throw apiError("invalid schedule",400,"invalid_schedule");}}
 updateSchedule(id:string,input:any){if(!this.state.getSchedule(id))throw apiError("schedule not found",404,"schedule_not_found");return normalize(this.state.updateSchedule(id,input));}
 pauseSchedule(id:string){if(!this.state.getSchedule(id))throw apiError("schedule not found",404,"schedule_not_found");try{return normalize(this.providers.actions?.pauseSchedule?.(id)??this.updateSchedule(id,{enabled:false}));}catch{throw apiError("schedule cannot be paused",409,"invalid_state");}}
 resumeSchedule(id:string){if(!this.state.getSchedule(id))throw apiError("schedule not found",404,"schedule_not_found");try{return normalize(this.providers.actions?.resumeSchedule?.(id)??this.updateSchedule(id,{enabled:true}));}catch{throw apiError("schedule cannot be resumed",409,"invalid_state");}}
 deleteSchedule(id:string){if(!this.state.getSchedule(id))throw apiError("schedule not found",404,"schedule_not_found");try{const result=this.providers.actions?.deleteSchedule?.(id)??this.state.deleteSchedule?.(id);if(result)return normalize(result);}catch{}throw apiError("schedule cannot be deleted",409,"invalid_state");}
 approvals(query:URLSearchParams){const root=query.get("rootAgentId"),status=query.get("status");let rows=root?this.state.listApprovalsForRoot(root):this.state.listApprovals();if(status)rows=rows.filter((approval:any)=>approval.status===status);return paginate(rows,query).map(normalize);}
 approval(id:string){return normalize(this.state.getApproval(id));}
 async decideApproval(id:string,decision:"approved"|"denied"){const existing=this.state.getApproval(id);if(!existing)throw apiError("approval not found",404,"approval_not_found");if(existing.status!=="pending")throw apiError("approval already decided",409,"invalid_state");let result;try{result=await this.providers.actions?.decideApproval?.(id,decision)??this.state.resolveApprovalIfPending?.(id,decision);}catch{throw apiError("approval decision conflict",409,"invalid_state");}if(result)return normalize(result);const approval=this.state.getApproval(id);throw approval?apiError("approval already decided",409,"invalid_state"):apiError("approval not found",404,"approval_not_found");}
 workers(query=new URLSearchParams()){let rows=this.state.listWorkers();const status=query.get("status");if(status)rows=rows.filter((worker:any)=>worker.status===status);return paginate(rows,query);}
 worker(id:string){const worker=this.state.getWorker(id);if(!worker)return undefined;return {worker,address:`loom://worker/${encodeURIComponent(id)}`,assignments:this.workerAssignments(id),connections:this.state.listWorkerConnections?.(id)??[],leases:this.state.listRemoteLeases?.(id)??[]};}
 workerAssignments(id:string){return this.state.listRemoteAssignments().filter((assignment:any)=>assignment.workerId===id).map(normalize);}
 workerLeases(id:string){return this.state.listRemoteLeases?.(id)??[];}
 assignments(query:URLSearchParams){let rows=this.state.listRemoteAssignments(query.get("status")??undefined);const worker=query.get("workerId");if(worker)rows=rows.filter((assignment:any)=>assignment.workerId===worker);return paginate(rows,query).map(normalize);}
 assignment(id:string){const assignment=normalize(this.state.getRemoteAssignment(id));if(!assignment)return undefined;return {...assignment,lease:this.state.getRemoteLease?.(assignment.leaseId),events:this.state.listRemoteExecutionEvents?.(id,50)??[]};}
 traces(query:URLSearchParams){let rows=this.state.listTraces?.({type:query.get("type")??undefined,since:query.get("since")??undefined,limit:number(query.get("limit"),1,500)??100})??[];for(const [key,dataKey] of [["workerId","workerId"],["jobId","jobId"],["assignmentId","assignmentId"]] as const){const value=query.get(key);if(value)rows=rows.filter((row:any)=>row.data?.[dataKey]===value);}return rows;}
 audit(query:URLSearchParams){return this.state.listOperatorAudit({afterId:number(query.get("afterId"),0,Number.MAX_SAFE_INTEGER),limit:number(query.get("limit"),1,200)??100,action:query.get("action")??undefined,resourceType:query.get("resourceType")??undefined});}
 async routes(){return await this.providers.routes?.()??[];}
 async route(target:string){try{return await this.providers.route?.(target)}catch{throw apiError("invalid route target",400,"invalid_route")}}
}
export function number(value:string|null,min:number,max:number){if(value===null)return undefined;const n=Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw apiError("invalid numeric query",400,"invalid_query");return n;}
export function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw apiError("JSON object required",400,"invalid_body");return value as Record<string,unknown>;}
function validateSchedule(input:any){const allowed=new Set(["id","kind","expression","timezone","payload","enabled","nextRunAt"]);if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).some(key=>!allowed.has(key)))throw apiError("invalid schedule body",400,"invalid_body");if(!["once","interval","cron"].includes(input.kind)||typeof input.expression!=="string"||input.expression.length<1||input.expression.length>500||typeof input.payload!=="object"||input.payload===null||Array.isArray(input.payload))throw apiError("invalid schedule body",400,"invalid_body");if(input.timezone!==undefined&&(typeof input.timezone!=="string"||input.timezone.length>100))throw apiError("invalid schedule body",400,"invalid_body");if(input.enabled!==undefined&&typeof input.enabled!=="boolean")throw apiError("invalid schedule body",400,"invalid_body");if(input.nextRunAt!==undefined&&(!Number.isSafeInteger(input.nextRunAt)||input.nextRunAt<0))throw apiError("invalid schedule body",400,"invalid_body");}
function paginate<T>(rows:T[],query:URLSearchParams){const offset=number(query.get("offset"),0,1_000_000)??0,limit=number(query.get("limit"),1,200)??50;return rows.slice(offset,offset+limit);}

