import {mkdirSync} from "node:fs";
import {randomUUID} from "node:crypto";
import {createRequire} from "node:module";
import type {
  Agent, AgentMessage, AgentMessageType, AgentResult, AgentRole, AgentStatus,
  ApprovalRequest, Artifact, ArtifactOperation, Checkpoint, Delegation,
  DelegationStatus, ExecutionPhase, FailurePolicy, MemoryEntry, MemoryScope,
  Message, Plan, PlanTask, TaskCheckpoint, TaskLease, TaskStatus, TraceCorrelation,
  TraceEvent, Visibility,
} from "@loom-agent/core";

type Statement={run(...args:unknown[]):unknown;get(...args:unknown[]):unknown;all(...args:unknown[]):unknown[]};
type Database={exec(sql:string):void;prepare(sql:string):Statement;pragma(sql:string):unknown;close?():void};

function loadDatabase(filename:string):Database{
  const req=createRequire(import.meta.url);const mod=process.versions.bun?req("bun:sqlite"):req("node:sqlite");
  if(process.versions.bun){const db=new mod.Database(filename);return {exec:(sql)=>db.run(sql),prepare:(sql)=>db.query(sql),pragma:()=>undefined,close:()=>db.close()};}
  const db=new mod.DatabaseSync(filename);return {exec:(sql)=>db.exec(sql),prepare:(sql)=>db.prepare(sql),pragma:()=>undefined,close:()=>db.close()};
}

const agentSelect=`SELECT id,task,COALESCE(goal,task) as goal,COALESCE(role,'general') as role,parent_agent_id as parentAgentId,COALESCE(root_agent_id,id) as rootAgentId,status,created_at as createdAt,updated_at as updatedAt,result,error FROM agents`;
const taskSelect=`SELECT id,plan_id as planId,title,kind,status,dependencies,retry_count as retryCount,max_retries as maxRetries,failure_policy as failurePolicy,blocked_reason as blockedReason,result,position,owner_agent_id as ownerAgentId,lease_id as leaseId,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt FROM plan_tasks`;

function redactTraceData(value:unknown,depth=0):unknown{if(depth>5)return "[truncated]";if(typeof value==="string"){if(value.length>2000)return `${value.slice(0,2000)}…[truncated]`;return value.replace(/Bearer\s+[A-Za-z0-9._~+\/-]+/gi,"Bearer [redacted]").replace(/(?:sk|pk)-[A-Za-z0-9_-]{16,}|(?:AKIA|ASIA)[A-Z0-9]{16}|(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}/g,"[redacted-token]").replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,"[redacted-jwt]")}if(Array.isArray(value))return value.slice(0,100).map(item=>redactTraceData(item,depth+1));if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const [key,item] of Object.entries(value).slice(0,100))out[/token|secret|password|authorization|cookie|private.?key|api.?key/i.test(key)?"[redacted-field]":key]=/token|secret|password|authorization|cookie|private.?key|api.?key/i.test(key)?"[redacted]":redactTraceData(item,depth+1);return out}return value;}
export class StateStore{
  readonly db:Database;
  constructor(filename=process.env.LOOM_DB??".loom/loom.db"){
    if(filename!==":memory:"){const dir=filename.replace(/[\\/][^\\/]+$/,"");if(dir)mkdirSync(dir,{recursive:true});}
    this.db=loadDatabase(filename);this.db.pragma("journal_mode = WAL");this.migrate();
  }

  private migrate(){
    this.db.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);`);
    this.applyMigration(1,`CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, task TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, result TEXT, error TEXT); CREATE TABLE IF NOT EXISTS traces (id INTEGER PRIMARY KEY AUTOINCREMENT, agent_id TEXT NOT NULL, type TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS checkpoints (agent_id TEXT PRIMARY KEY, step INTEGER NOT NULL, messages TEXT NOT NULL, status TEXT NOT NULL, result TEXT);`);
    this.applyMigration(2,`CREATE TABLE IF NOT EXISTS working_memory (agent_id TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(agent_id,key)); CREATE TABLE IF NOT EXISTS tool_execution_ledger (tool_call_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, tool_name TEXT NOT NULL, input TEXT NOT NULL, status TEXT NOT NULL, result TEXT, error TEXT, updated_at TEXT NOT NULL);`);
    this.applyMigration(3,`CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, goal TEXT NOT NULL, status TEXT NOT NULL, phase TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS plan_tasks (id TEXT PRIMARY KEY, plan_id TEXT NOT NULL, title TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, dependencies TEXT NOT NULL, retry_count INTEGER NOT NULL, max_retries INTEGER NOT NULL, failure_policy TEXT, blocked_reason TEXT, result TEXT, position INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS approval_requests (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, task_id TEXT, tool_call_id TEXT, tool_name TEXT NOT NULL, input TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, decided_at TEXT); CREATE TABLE IF NOT EXISTS artifacts (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, task_id TEXT, checkpoint_id TEXT, path TEXT NOT NULL, operation TEXT NOT NULL, created_at TEXT NOT NULL);`);
    this.applyMigration(4,`CREATE TABLE IF NOT EXISTS task_checkpoints (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, plan_id TEXT NOT NULL, task_id TEXT, phase TEXT NOT NULL, step INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL);`);
    this.applyMigration(5,`
      ALTER TABLE agents ADD COLUMN parent_agent_id TEXT; ALTER TABLE agents ADD COLUMN root_agent_id TEXT; ALTER TABLE agents ADD COLUMN role TEXT NOT NULL DEFAULT 'general'; ALTER TABLE agents ADD COLUMN goal TEXT;
      UPDATE agents SET root_agent_id=id WHERE root_agent_id IS NULL; UPDATE agents SET goal=task WHERE goal IS NULL;
      ALTER TABLE plan_tasks ADD COLUMN owner_agent_id TEXT; ALTER TABLE plan_tasks ADD COLUMN lease_id TEXT; ALTER TABLE plan_tasks ADD COLUMN lease_expires_at TEXT;
      ALTER TABLE artifacts ADD COLUMN type TEXT NOT NULL DEFAULT 'file'; ALTER TABLE artifacts ADD COLUMN visibility TEXT NOT NULL DEFAULT 'parent-visible';
      ALTER TABLE approval_requests ADD COLUMN role TEXT; ALTER TABLE approval_requests ADD COLUMN reason TEXT; ALTER TABLE approval_requests ADD COLUMN arguments_summary TEXT;
      ALTER TABLE traces ADD COLUMN root_agent_id TEXT; ALTER TABLE traces ADD COLUMN parent_agent_id TEXT; ALTER TABLE traces ADD COLUMN task_id TEXT; ALTER TABLE traces ADD COLUMN delegation_id TEXT; ALTER TABLE traces ADD COLUMN message_id TEXT; ALTER TABLE traces ADD COLUMN tool_call_id TEXT; ALTER TABLE traces ADD COLUMN checkpoint_id TEXT;
      UPDATE traces SET root_agent_id=agent_id WHERE root_agent_id IS NULL;
      CREATE TABLE delegations (id TEXT PRIMARY KEY,parent_agent_id TEXT NOT NULL,child_agent_id TEXT NOT NULL,task_id TEXT,goal TEXT NOT NULL,status TEXT NOT NULL,failure_policy TEXT,created_at TEXT NOT NULL,started_at TEXT,completed_at TEXT,result_summary TEXT,failure_reason TEXT);
      CREATE UNIQUE INDEX delegations_active_task ON delegations(parent_agent_id,task_id) WHERE status IN ('created','assigned','running','waiting');
      CREATE TABLE agent_messages (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,from_agent_id TEXT NOT NULL,to_agent_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,visibility TEXT NOT NULL,created_at TEXT NOT NULL,delivered_at TEXT,acknowledged_at TEXT);
      CREATE TABLE agent_results (id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,delegation_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL,summary TEXT NOT NULL,artifacts TEXT,task_updates TEXT,findings TEXT,failure_policy TEXT,error TEXT,created_at TEXT NOT NULL);
      CREATE TABLE task_leases (id TEXT PRIMARY KEY,task_id TEXT NOT NULL,agent_id TEXT NOT NULL,status TEXT NOT NULL,acquired_at TEXT NOT NULL,expires_at TEXT NOT NULL,released_at TEXT);
      CREATE UNIQUE INDEX task_leases_active_task ON task_leases(task_id) WHERE status='active';
      CREATE TABLE scoped_memory (agent_id TEXT NOT NULL,root_agent_id TEXT NOT NULL,scope TEXT NOT NULL,visibility TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(agent_id,scope,key));
      CREATE TABLE coordination_decisions (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,agent_id TEXT NOT NULL,task_id TEXT,delegation_id TEXT,decision TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
      CREATE INDEX agents_root_idx ON agents(root_agent_id); CREATE INDEX messages_recipient_idx ON agent_messages(to_agent_id,acknowledged_at); CREATE INDEX traces_root_idx ON traces(root_agent_id,id);
    `);
    this.applyMigration(6,`CREATE TABLE IF NOT EXISTS plan_revisions (id TEXT PRIMARY KEY,plan_id TEXT NOT NULL,root_agent_id TEXT NOT NULL,version INTEGER NOT NULL,previous_version INTEGER,reason TEXT,proposal TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(plan_id,version)); CREATE TABLE IF NOT EXISTS execution_rounds (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,task_id TEXT NOT NULL,round INTEGER NOT NULL,checkpoint_id TEXT,status TEXT NOT NULL,tool_calls TEXT NOT NULL,messages TEXT NOT NULL,summary TEXT,created_at TEXT NOT NULL,UNIQUE(task_id,round)); CREATE TABLE IF NOT EXISTS review_records (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,task_id TEXT NOT NULL,review_id TEXT NOT NULL,round INTEGER NOT NULL,verdict TEXT NOT NULL,summary TEXT NOT NULL,issues TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(task_id,round)); CREATE TABLE IF NOT EXISTS repair_rounds (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,task_id TEXT NOT NULL,review_id TEXT NOT NULL,round INTEGER NOT NULL,status TEXT NOT NULL,instruction TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(task_id,round)); CREATE TABLE IF NOT EXISTS test_evidence (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,task_id TEXT NOT NULL,checkpoint_id TEXT,level TEXT NOT NULL,command TEXT NOT NULL,exit_code INTEGER NOT NULL,duration_ms INTEGER NOT NULL,stdout_summary TEXT NOT NULL,stderr_summary TEXT NOT NULL,selected_because TEXT,created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS semantic_root_idx ON plan_revisions(root_agent_id); CREATE INDEX IF NOT EXISTS execution_task_idx ON execution_rounds(task_id); CREATE TABLE IF NOT EXISTS runtime_kv (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);`);
    this.applyMigration(7,`CREATE TABLE IF NOT EXISTS daemon_instances (daemon_id TEXT PRIMARY KEY,started_at INTEGER NOT NULL,heartbeat_at INTEGER NOT NULL,pid INTEGER,hostname TEXT,version TEXT,status TEXT NOT NULL,last_shutdown_at INTEGER); CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY,type TEXT NOT NULL,status TEXT NOT NULL,payload_json TEXT NOT NULL,priority INTEGER NOT NULL,idempotency_key TEXT UNIQUE,root_agent_id TEXT,schedule_id TEXT,attempt INTEGER NOT NULL,max_attempts INTEGER NOT NULL,available_at INTEGER NOT NULL,claimed_by TEXT,lease_expires_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,started_at INTEGER,completed_at INTEGER,error_code TEXT,error_message TEXT,result_summary TEXT); CREATE INDEX IF NOT EXISTS jobs_due_idx ON jobs(status,available_at,priority); CREATE TABLE IF NOT EXISTS schedules (id TEXT PRIMARY KEY,name TEXT,kind TEXT NOT NULL,expression TEXT NOT NULL,timezone TEXT NOT NULL,enabled INTEGER NOT NULL,payload_json TEXT NOT NULL,misfire_policy TEXT NOT NULL,overlap_policy TEXT NOT NULL,next_run_at INTEGER,last_run_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,error_message TEXT); CREATE TABLE IF NOT EXISTS schedule_occurrences (id TEXT PRIMARY KEY,schedule_id TEXT NOT NULL,intended_run_at INTEGER NOT NULL,job_id TEXT NOT NULL UNIQUE,created_at INTEGER NOT NULL,UNIQUE(schedule_id,intended_run_at));`);
    this.applyMigration(8,`ALTER TABLE jobs ADD COLUMN waiting_reason TEXT; ALTER TABLE jobs ADD COLUMN waiting_ref TEXT;`);
    this.applyMigration(9,`CREATE TABLE IF NOT EXISTS workers (worker_id TEXT PRIMARY KEY,name TEXT,capabilities_json TEXT NOT NULL,metadata_json TEXT NOT NULL,status TEXT NOT NULL,registered_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,disconnected_at INTEGER); CREATE TABLE IF NOT EXISTS connections (connection_id TEXT PRIMARY KEY,worker_id TEXT NOT NULL,transport TEXT NOT NULL,status TEXT NOT NULL,connected_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,disconnected_at INTEGER,metadata_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS connections_worker_idx ON connections(worker_id,status); CREATE TABLE IF NOT EXISTS worker_presence (worker_id TEXT PRIMARY KEY,status TEXT NOT NULL,last_seen_at INTEGER NOT NULL,connection_id TEXT,metadata_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS remote_assignments (id TEXT PRIMARY KEY,worker_id TEXT NOT NULL,task_id TEXT,payload_json TEXT NOT NULL,status TEXT NOT NULL,lease_id TEXT,assigned_at INTEGER NOT NULL,started_at INTEGER,completed_at INTEGER,error_message TEXT); CREATE INDEX IF NOT EXISTS remote_assignments_worker_idx ON remote_assignments(worker_id,status); CREATE TABLE IF NOT EXISTS remote_leases (id TEXT PRIMARY KEY,assignment_id TEXT NOT NULL,worker_id TEXT NOT NULL,status TEXT NOT NULL,acquired_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,released_at INTEGER); CREATE UNIQUE INDEX IF NOT EXISTS remote_leases_active_assignment ON remote_leases(assignment_id) WHERE status='active'; CREATE TABLE IF NOT EXISTS protocol_state (connection_id TEXT PRIMARY KEY,send_sequence INTEGER NOT NULL,receive_sequence INTEGER NOT NULL,last_acked_sequence INTEGER NOT NULL,updated_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS execution_events (execution_id TEXT NOT NULL,sequence INTEGER NOT NULL,message_id TEXT NOT NULL,payload_json TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(execution_id,sequence),UNIQUE(message_id));`);
    this.applyMigration(10,`CREATE TABLE IF NOT EXISTS execution_events (execution_id TEXT NOT NULL,sequence INTEGER NOT NULL,message_id TEXT NOT NULL,payload_json TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(execution_id,sequence),UNIQUE(message_id));`);
    if(!(this.db.prepare("PRAGMA table_info(remote_leases)").all() as any[]).some((column:any)=>column.name==="fencing_token")) this.db.exec("ALTER TABLE remote_leases ADD COLUMN fencing_token INTEGER NOT NULL DEFAULT 0");
    this.applyMigration(11,`CREATE TABLE IF NOT EXISTS protocol_messages (message_id TEXT PRIMARY KEY,connection_id TEXT NOT NULL,direction TEXT NOT NULL,sequence INTEGER NOT NULL,envelope_json TEXT NOT NULL,acked_at INTEGER,created_at INTEGER NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS protocol_messages_cursor_idx ON protocol_messages(connection_id,direction,sequence);`);
    this.applyMigration(12,`CREATE TABLE IF NOT EXISTS remote_event_cursors (assignment_id TEXT NOT NULL,lease_id TEXT NOT NULL,connection_id TEXT NOT NULL,last_sequence INTEGER NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(assignment_id,lease_id,connection_id)); CREATE TABLE IF NOT EXISTS remote_event_messages (message_id TEXT PRIMARY KEY,connection_id TEXT NOT NULL,transport_sequence INTEGER NOT NULL);`);
    this.applyMigration(13,`CREATE TABLE IF NOT EXISTS operator_credentials (id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator' CHECK(role IN ('viewer','operator')),token_hash TEXT NOT NULL UNIQUE,enabled INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,last_used_at INTEGER); CREATE TABLE IF NOT EXISTS operator_sessions (id TEXT PRIMARY KEY,credential_id TEXT NOT NULL,session_hash TEXT NOT NULL UNIQUE,csrf_hash TEXT NOT NULL,created_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,revoked_at INTEGER,FOREIGN KEY(credential_id) REFERENCES operator_credentials(id)); CREATE INDEX IF NOT EXISTS operator_sessions_hash_idx ON operator_sessions(session_hash); CREATE TABLE IF NOT EXISTS operator_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL,actor_id TEXT,session_fingerprint TEXT,action TEXT NOT NULL,resource_type TEXT,resource_id TEXT,outcome TEXT NOT NULL CHECK(outcome IN ('success','denied','error')),http_status INTEGER NOT NULL,source_address TEXT,details_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS operator_audit_cursor_idx ON operator_audit(id,created_at); CREATE TABLE IF NOT EXISTS control_events (id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,resource_type TEXT,resource_id TEXT,data_json TEXT NOT NULL,created_at INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS control_events_cursor_idx ON control_events(id,created_at); CREATE TABLE IF NOT EXISTS worker_connection_epochs (worker_id TEXT PRIMARY KEY,epoch INTEGER NOT NULL,updated_at INTEGER NOT NULL);`);
  }
  private applyMigration(version:number,sql:string){if(!this.db.prepare("SELECT version FROM schema_migrations WHERE version=?").get(version)){this.transaction(()=>{this.db.exec(sql);this.db.prepare("INSERT INTO schema_migrations VALUES (?,?)").run(version,new Date().toISOString());});}}
  transaction<T>(operation:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const result=operation();this.db.exec("COMMIT");return result;}catch(error){this.db.exec("ROLLBACK");throw error;}}
  close():void{this.db.close?.();}
  getSchemaVersion():number{return (this.db.prepare("SELECT MAX(version) as version FROM schema_migrations").get() as {version:number}).version;}
  acceptRemoteEvent(input:{assignmentId:string;workerId:string;leaseId:string;fencingToken:number;sequence:number;messageId:string;payload:unknown;connectionId?:string}){return this.transaction(()=>{const assignment=this.getRemoteAssignment(input.assignmentId),lease=this.getRemoteLease(input.leaseId);if(!assignment||assignment.workerId!==input.workerId||assignment.leaseId!==input.leaseId||!lease||lease.status!=="active"||lease.workerId!==input.workerId||lease.fencingToken!==input.fencingToken||lease.expiresAt<=Date.now())return {accepted:false,reason:"stale_or_invalid_lease"};if(!Number.isSafeInteger(input.sequence)||input.sequence<1)return {accepted:false,reason:"invalid_sequence"};const connectionId=input.connectionId??"legacy";const duplicate=this.db.prepare("SELECT e.payload_json as payload,m.connection_id as connectionId,m.transport_sequence as transportSequence FROM execution_events e LEFT JOIN remote_event_messages m ON m.message_id=e.message_id WHERE e.message_id=?").get(input.messageId) as any;if(duplicate){if(duplicate.payload!==JSON.stringify(input.payload)||(duplicate.connectionId&&(duplicate.connectionId!==connectionId||duplicate.transportSequence!==input.sequence)))return {accepted:false,reason:"message_id_conflict"};return {accepted:true,duplicate:true,ack:duplicate.transportSequence??input.sequence};}const cursor=this.db.prepare("SELECT last_sequence as lastSequence FROM remote_event_cursors WHERE assignment_id=? AND lease_id=? AND connection_id=?").get(input.assignmentId,input.leaseId,connectionId) as any;if(cursor&&input.sequence!==cursor.lastSequence+1)return {accepted:false,reason:input.sequence<=cursor.lastSequence?"stale_sequence":"sequence_gap",ack:cursor.lastSequence};const ordinal=(this.db.prepare("SELECT COALESCE(MAX(sequence),0)+1 as sequence FROM execution_events WHERE execution_id=?").get(input.assignmentId) as any).sequence;this.db.prepare("INSERT INTO execution_events(execution_id,sequence,message_id,payload_json,created_at) VALUES(?,?,?,?,?)").run(input.assignmentId,ordinal,input.messageId,JSON.stringify(input.payload),Date.now());this.db.prepare("INSERT INTO remote_event_messages(message_id,connection_id,transport_sequence) VALUES(?,?,?)").run(input.messageId,connectionId,input.sequence);this.db.prepare("INSERT INTO remote_event_cursors(assignment_id,lease_id,connection_id,last_sequence,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(assignment_id,lease_id,connection_id) DO UPDATE SET last_sequence=excluded.last_sequence,updated_at=excluded.updated_at").run(input.assignmentId,input.leaseId,connectionId,input.sequence,Date.now());return {accepted:true,duplicate:false,ack:input.sequence};});}
  appendRemoteEvent(input:{executionId:string;sequence:number;messageId:string;payload:unknown}){return this.transaction(()=>{this.db.prepare("INSERT OR IGNORE INTO execution_events(execution_id,sequence,message_id,payload_json,created_at) VALUES(?,?,?,?,?)").run(input.executionId,input.sequence,input.messageId,JSON.stringify(input.payload),Date.now());return {accepted:true,ack:(this.db.prepare("SELECT MAX(sequence) as sequence FROM execution_events WHERE execution_id=?").get(input.executionId) as any)?.sequence??0};});}
  registerWorker(input:{workerId:string;name?:string;capabilities?:unknown;metadata?:unknown;status?:string}){const now=Date.now();this.db.prepare("INSERT INTO workers(worker_id,name,capabilities_json,metadata_json,status,registered_at,last_seen_at,disconnected_at) VALUES(?,?,?,?,?,?,?,NULL) ON CONFLICT(worker_id) DO UPDATE SET name=excluded.name,capabilities_json=excluded.capabilities_json,metadata_json=excluded.metadata_json,status=excluded.status,last_seen_at=excluded.last_seen_at").run(input.workerId,input.name??null,JSON.stringify(input.capabilities??[]),JSON.stringify(input.metadata??{}),input.status??"online",now,now);const worker=this.getWorker(input.workerId);this.appendControlEvent({type:"worker.connected",resourceType:"worker",resourceId:input.workerId,data:{status:worker?.status}});return worker;}
  getWorker(workerId:string){const row=this.db.prepare("SELECT worker_id as workerId,name,capabilities_json as capabilities,metadata_json as metadata,status,registered_at as registeredAt,last_seen_at as lastSeenAt,disconnected_at as disconnectedAt FROM workers WHERE worker_id=?").get(workerId) as any;if(row){row.capabilities=JSON.parse(row.capabilities);row.metadata=JSON.parse(row.metadata);}return row;}
  listWorkers(status?:string){const rows=(status?this.db.prepare("SELECT worker_id as workerId FROM workers WHERE status=? ORDER BY registered_at").all(status):this.db.prepare("SELECT worker_id as workerId FROM workers ORDER BY registered_at").all()) as any[];return rows.map(r=>this.getWorker(r.workerId));}
  heartbeatWorker(workerId:string,status="online",metadata?:unknown){this.db.prepare("UPDATE workers SET status=?,last_seen_at=?,metadata_json=COALESCE(?,metadata_json) WHERE worker_id=?").run(status,Date.now(),metadata===undefined?null:JSON.stringify(metadata),workerId);}
  setWorkerStatus(workerId:string,status:string){this.db.prepare("UPDATE workers SET status=?,last_seen_at=? WHERE worker_id=?").run(status,Date.now(),workerId);this.appendControlEvent({type:status==="offline"?"worker.disconnected":"worker.updated",resourceType:"worker",resourceId:workerId,data:{status}});}
  openWorkerConnection(input:{connectionId:string;workerId:string;transport:string;metadata?:unknown}){const now=Date.now();this.db.prepare("INSERT OR REPLACE INTO connections(connection_id,worker_id,transport,status,connected_at,last_seen_at,disconnected_at,metadata_json) VALUES(?,?,?,'online',?,?,NULL,?)").run(input.connectionId,input.workerId,input.transport,now,now,JSON.stringify(input.metadata??{}));this.db.prepare("INSERT OR REPLACE INTO worker_presence(worker_id,status,last_seen_at,connection_id,metadata_json) VALUES(?, 'online',?,?,?)").run(input.workerId,now,input.connectionId,JSON.stringify(input.metadata??{}));return {connectionId:input.connectionId,workerId:input.workerId};}
  closeWorkerConnection(connectionId:string){this.db.prepare("UPDATE connections SET status='offline',disconnected_at=? WHERE connection_id=?").run(Date.now(),connectionId);}
  assignRemote(input:{workerId:string;taskId?:string;payload:unknown;id?:string}){const id=input.id??`remote_${randomUUID()}`;this.db.prepare("INSERT INTO remote_assignments(id,worker_id,task_id,payload_json,status,lease_id,assigned_at) VALUES(?,?,?,?,'assigned',NULL,?)").run(id,input.workerId,input.taskId??null,JSON.stringify(input.payload),Date.now());const assignment=this.getRemoteAssignment(id);this.appendControlEvent({type:"remote.assignment.updated",resourceType:"remote-assignment",resourceId:id,data:{status:assignment?.status,workerId:input.workerId}});return assignment;}
  listRemoteAssignments(status?:string){const rows=(status?this.db.prepare("SELECT id FROM remote_assignments WHERE status=? ORDER BY assigned_at").all(status):this.db.prepare("SELECT id FROM remote_assignments ORDER BY assigned_at").all()) as any[];return rows.map(row=>this.getRemoteAssignment(row.id));}
  getRemoteAssignment(id:string){return this.db.prepare("SELECT id,worker_id as workerId,task_id as taskId,payload_json as payload,status,lease_id as leaseId,assigned_at as assignedAt,started_at as startedAt,completed_at as completedAt,error_message as errorMessage FROM remote_assignments WHERE id=?").get(id) as any;}
  acquireRemoteLease(assignmentId:string,workerId:string,ttlMs:number){if(!Number.isSafeInteger(ttlMs)||ttlMs<=0)throw new Error("remote lease TTL must be a positive integer");return this.transaction(()=>{const assignment=this.getRemoteAssignment(assignmentId);if(!assignment)throw new Error("remote assignment not found");if(assignment.status!=="assigned"&&assignment.status!=="expired")throw new Error("remote assignment is not available for leasing");if(assignment.status==="assigned"&&assignment.workerId!==workerId)throw new Error("remote assignment owner mismatch");const existing=this.db.prepare("SELECT id FROM remote_leases WHERE assignment_id=? AND status='active'").get(assignmentId);if(existing)throw new Error("remote assignment already leased");const id=`lease_${randomUUID()}`,now=Date.now();const next=((this.db.prepare("SELECT COALESCE(MAX(fencing_token),0) as n FROM remote_leases").get() as any)?.n??0)+1;this.db.prepare("INSERT INTO remote_leases(id,assignment_id,worker_id,status,acquired_at,expires_at,fencing_token) VALUES(?,?,?,'active',?,?,?)").run(id,assignmentId,workerId,now,now+ttlMs,next);this.db.prepare("UPDATE remote_assignments SET worker_id=?,status='dispatched',lease_id=?,started_at=? WHERE id=?").run(workerId,id,now,assignmentId);return {id,assignmentId,workerId,expiresAt:now+ttlMs,fencingToken:next};});}
  renewRemoteLease(leaseId:string,workerId:string,ttlMs:number){if(!Number.isSafeInteger(ttlMs)||ttlMs<=0)throw new Error("remote lease TTL must be a positive integer");const now=Date.now();const r=this.db.prepare("UPDATE remote_leases SET expires_at=? WHERE id=? AND worker_id=? AND status='active' AND expires_at>?").run(now+ttlMs,leaseId,workerId,now);return !!(r as any)?.changes;}
  releaseRemoteLease(leaseId:string,workerId:string,fencingToken:number){const r=this.db.prepare("UPDATE remote_leases SET status='released',released_at=? WHERE id=? AND worker_id=? AND fencing_token=? AND status='active'").run(Date.now(),leaseId,workerId,fencingToken);return !!(r as any)?.changes;}
  updateRemoteAssignmentStatus(id:string,status:string,errorMessage?:string){this.db.prepare("UPDATE remote_assignments SET status=?,error_message=? WHERE id=?").run(status,errorMessage??null,id);const assignment=this.getRemoteAssignment(id);this.appendControlEvent({type:"remote.assignment.updated",resourceType:"remote-assignment",resourceId:id,data:{status,workerId:assignment?.workerId}});return assignment;}
  getRemoteLease(leaseId:string){return this.db.prepare("SELECT id,assignment_id as assignmentId,worker_id as workerId,status,acquired_at as acquiredAt,expires_at as expiresAt,fencing_token as fencingToken,released_at as releasedAt FROM remote_leases WHERE id=?").get(leaseId) as any;}
  expireRemoteLeases(now=Date.now()){return this.transaction(()=>{const expired=this.db.prepare("SELECT id FROM remote_leases WHERE status='active' AND expires_at<=?").all(now) as any[];this.db.prepare("UPDATE remote_leases SET status='expired',released_at=? WHERE status='active' AND expires_at<=?").run(now,now);for(const lease of expired)this.db.prepare("UPDATE remote_assignments SET status='expired' WHERE lease_id=? AND status IN ('dispatched','running')").run(lease.id);return expired.length;});}
  recordProtocolMessage(input:{messageId:string;connectionId:string;direction:string;sequence:number;envelope:unknown}){const r=this.db.prepare("INSERT OR IGNORE INTO protocol_messages(message_id,connection_id,direction,sequence,envelope_json,created_at) VALUES(?,?,?,?,?,?)").run(input.messageId,input.connectionId,input.direction,input.sequence,JSON.stringify(input.envelope),Date.now());return !!(r as any)?.changes;}
  listUnackedProtocolMessagesForWorker(workerId:string,direction="outbound"){return this.db.prepare("SELECT p.message_id as messageId,p.connection_id as connectionId,p.sequence,p.envelope_json as envelope FROM protocol_messages p JOIN connections c ON c.connection_id=p.connection_id WHERE c.worker_id=? AND p.direction=? AND p.acked_at IS NULL ORDER BY p.sequence").all(workerId,direction) as any[];}
  listUnackedProtocolMessages(connectionId:string,direction="outbound"){return this.db.prepare("SELECT message_id as messageId,sequence,envelope_json as envelope FROM protocol_messages WHERE connection_id=? AND direction=? AND acked_at IS NULL ORDER BY sequence").all(connectionId,direction) as any[];}
  getMaxProtocolSequenceForWorker(workerId:string,direction="outbound"){return (this.db.prepare("SELECT COALESCE(MAX(p.sequence),0) as sequence FROM protocol_messages p JOIN connections c ON c.connection_id=p.connection_id WHERE c.worker_id=? AND p.direction=?").get(workerId,direction) as any)?.sequence??0;}
  ackProtocolMessageById(messageId:string){this.db.prepare("UPDATE protocol_messages SET acked_at=? WHERE message_id=? AND acked_at IS NULL").run(Date.now(),messageId);}
  ackProtocolMessagesForWorker(workerId:string,direction:string,sequence:number){this.db.prepare("UPDATE protocol_messages SET acked_at=? WHERE connection_id IN (SELECT connection_id FROM connections WHERE worker_id=?) AND direction=? AND sequence<=? AND acked_at IS NULL").run(Date.now(),workerId,direction,sequence);}
  ackProtocolMessage(connectionId:string,direction:string,sequence:number){this.db.prepare("UPDATE protocol_messages SET acked_at=? WHERE connection_id=? AND direction=? AND sequence<=? AND acked_at IS NULL").run(Date.now(),connectionId,direction,sequence);}
  nextProtocolSequenceForWorker(workerId:string){return this.transaction(()=>{const key=`worker:${workerId}`,persisted=(this.db.prepare("SELECT COALESCE(MAX(p.sequence),0) as sequence FROM protocol_messages p JOIN connections c ON c.connection_id=p.connection_id WHERE c.worker_id=? AND p.direction='outbound'").get(workerId) as any)?.sequence??0,current=(this.db.prepare("SELECT send_sequence as sequence FROM protocol_state WHERE connection_id=?").get(key) as any)?.sequence??0,next=Math.max(persisted,current)+1,now=Date.now();this.db.prepare("INSERT INTO protocol_state(connection_id,send_sequence,receive_sequence,last_acked_sequence,updated_at) VALUES(?,?,0,0,?) ON CONFLICT(connection_id) DO UPDATE SET send_sequence=excluded.send_sequence,updated_at=excluded.updated_at").run(key,next,now);return next;});}
  nextProtocolSequence(connectionId:string){const now=Date.now();this.db.prepare("INSERT INTO protocol_state(connection_id,send_sequence,receive_sequence,last_acked_sequence,updated_at) VALUES(?,1,0,0,?) ON CONFLICT(connection_id) DO UPDATE SET send_sequence=send_sequence+1,updated_at=?").run(connectionId,now,now);return (this.db.prepare("SELECT send_sequence FROM protocol_state WHERE connection_id=?").get(connectionId) as any).send_sequence;}
  acknowledgeProtocol(connectionId:string,sequence:number){this.db.prepare("UPDATE protocol_state SET last_acked_sequence=MAX(last_acked_sequence,?),updated_at=? WHERE connection_id=?").run(sequence,Date.now(),connectionId);}
  receiveProtocolSequence(connectionId:string,sequence:number){this.db.prepare("UPDATE protocol_state SET receive_sequence=MAX(receive_sequence,?),updated_at=? WHERE connection_id=?").run(sequence,Date.now(),connectionId);}
  getProtocolState(connectionId:string){return this.db.prepare("SELECT connection_id as connectionId,send_sequence as sendSequence,receive_sequence as receiveSequence,last_acked_sequence as lastAckedSequence,updated_at as updatedAt FROM protocol_state WHERE connection_id=?").get(connectionId) as any;}
  getActiveDaemon(staleAfterMs:number,now=Date.now()){return this.db.prepare("SELECT daemon_id as daemonId,started_at as startedAt,heartbeat_at as heartbeatAt,pid,hostname,version,status,last_shutdown_at as lastShutdownAt FROM daemon_instances WHERE status='running' AND heartbeat_at>? ORDER BY heartbeat_at DESC LIMIT 1").get(now-staleAfterMs) as any;}
  startDaemon(input:{daemonId:string;pid?:number;hostname?:string;version?:string;staleAfterMs:number}){const active=this.getActiveDaemon(input.staleAfterMs);if(active&&active.daemonId!==input.daemonId)throw new Error(`daemon already running: ${active.daemonId}`);const now=Date.now();this.db.prepare("INSERT INTO daemon_instances(daemon_id,started_at,heartbeat_at,pid,hostname,version,status,last_shutdown_at) VALUES(?,?,?,?,?,?,?,NULL) ON CONFLICT(daemon_id) DO UPDATE SET heartbeat_at=excluded.heartbeat_at,status='running',pid=excluded.pid").run(input.daemonId,now,now,input.pid??null,input.hostname??null,input.version??null,"running");return this.getDaemon(input.daemonId);}
  heartbeatDaemon(id:string){this.db.prepare("UPDATE daemon_instances SET heartbeat_at=?,status='running' WHERE daemon_id=?").run(Date.now(),id);}
  stopDaemon(id:string){this.db.prepare("UPDATE daemon_instances SET status='stopped',last_shutdown_at=?,heartbeat_at=? WHERE daemon_id=?").run(Date.now(),Date.now(),id);}
  getDaemon(id:string){return this.db.prepare("SELECT daemon_id as daemonId,started_at as startedAt,heartbeat_at as heartbeatAt,pid,hostname,version,status,last_shutdown_at as lastShutdownAt FROM daemon_instances WHERE daemon_id=?").get(id) as any;}
  listDaemons(){return this.db.prepare("SELECT daemon_id as daemonId,started_at as startedAt,heartbeat_at as heartbeatAt,pid,hostname,version,status,last_shutdown_at as lastShutdownAt FROM daemon_instances ORDER BY heartbeat_at DESC").all() as any[];}
  enqueueJob(input:{id?:string;type:string;payload:unknown;priority?:number;idempotencyKey?:string;rootAgentId?:string;scheduleId?:string;maxAttempts?:number;availableAt?:number}){const id=input.id??`job_${randomUUID()}`,now=Date.now();this.db.prepare("INSERT OR IGNORE INTO jobs(id,type,status,payload_json,priority,idempotency_key,root_agent_id,schedule_id,attempt,max_attempts,available_at,created_at,updated_at) VALUES(?,?, 'queued',?,?,?,?,?,0,?,?,?,?)").run(id,input.type,JSON.stringify(input.payload),input.priority??0,input.idempotencyKey??null,input.rootAgentId??null,input.scheduleId??null,input.maxAttempts??3,input.availableAt??now,now,now);const job=this.getJobByIdempotency(input.idempotencyKey??id)??this.getJob(id);if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:job.id,data:{status:job.status}});return job;}
  getJob(id:string){return this.db.prepare("SELECT id,type,status,payload_json as payload,priority,idempotency_key as idempotencyKey,root_agent_id as rootAgentId,schedule_id as scheduleId,attempt,max_attempts as maxAttempts,available_at as availableAt,claimed_by as claimedBy,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt,started_at as startedAt,completed_at as completedAt,error_code as errorCode,error_message as errorMessage,result_summary as resultSummary,waiting_reason as waitingReason,waiting_ref as waitingRef FROM jobs WHERE id=?").get(id) as any;}
  getJobByIdempotency(key:string){return this.db.prepare("SELECT id,type,status,payload_json as payload,priority,idempotency_key as idempotencyKey,root_agent_id as rootAgentId,schedule_id as scheduleId,attempt,max_attempts as maxAttempts,available_at as availableAt,claimed_by as claimedBy,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt,started_at as startedAt,completed_at as completedAt,error_code as errorCode,error_message as errorMessage,result_summary as resultSummary,waiting_reason as waitingReason,waiting_ref as waitingRef FROM jobs WHERE idempotency_key=?").get(key) as any;}
  listJobs(status?:string){return (status?this.db.prepare("SELECT id,type,status,payload_json as payload,priority,idempotency_key as idempotencyKey,root_agent_id as rootAgentId,schedule_id as scheduleId,attempt,max_attempts as maxAttempts,available_at as availableAt,claimed_by as claimedBy,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt,started_at as startedAt,completed_at as completedAt,error_code as errorCode,error_message as errorMessage,result_summary as resultSummary,waiting_reason as waitingReason,waiting_ref as waitingRef FROM jobs WHERE status=? ORDER BY priority DESC,available_at,created_at"):this.db.prepare("SELECT id,type,status,payload_json as payload,priority,idempotency_key as idempotencyKey,root_agent_id as rootAgentId,schedule_id as scheduleId,attempt,max_attempts as maxAttempts,available_at as availableAt,claimed_by as claimedBy,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt,started_at as startedAt,completed_at as completedAt,error_code as errorCode,error_message as errorMessage,result_summary as resultSummary,waiting_reason as waitingReason,waiting_ref as waitingRef FROM jobs ORDER BY created_at")).all(...(status?[status]:[])) as any[];}
  renewJobLease(id:string,daemonId:string,leaseMs:number,now=Date.now()){const r=this.db.prepare("UPDATE jobs SET lease_expires_at=?,updated_at=? WHERE id=? AND claimed_by=? AND status IN ('claimed','running') AND lease_expires_at>?").run(now+leaseMs,now,id,daemonId,now);return !!(r as any)?.changes;}
  claimNextJob(daemonId:string,leaseMs:number,now=Date.now()){return this.transaction(()=>{const j=this.db.prepare("SELECT id FROM jobs WHERE (status='queued' OR (status='retry_wait' AND available_at<=?) OR ((status='claimed' OR status='running') AND lease_expires_at<?)) AND available_at<=? ORDER BY priority DESC,available_at,created_at LIMIT 1").get(now,now,now) as any;if(!j)return undefined;this.db.prepare("UPDATE jobs SET status='claimed',claimed_by=?,lease_expires_at=?,attempt=attempt+1,updated_at=? WHERE id=? AND (status='queued' OR status='retry_wait' OR lease_expires_at<?)").run(daemonId,now+leaseMs,now,j.id,now);return this.getJob(j.id);});}
  setJobWaiting(id:string,reason:string,ref?:string){this.db.prepare("UPDATE jobs SET status='waiting',attempt=CASE WHEN attempt>0 THEN attempt-1 ELSE 0 END,claimed_by=NULL,lease_expires_at=NULL,waiting_reason=?,waiting_ref=?,updated_at=? WHERE id=?").run(reason,ref??null,Date.now(),id);const job=this.getJob(id);if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:id,data:{status:job.status}});return job;}
  wakeWaitingJob(id:string){this.db.prepare("UPDATE jobs SET status='queued',waiting_reason=NULL,waiting_ref=NULL,available_at=?,updated_at=? WHERE id=? AND status='waiting'").run(Date.now(),Date.now(),id);const job=this.getJob(id);if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:id,data:{status:job.status}});return job;}
  updateJob(id:string,status:string,data:Record<string,unknown>={}){this.db.prepare("UPDATE jobs SET status=?,root_agent_id=COALESCE(?,root_agent_id),claimed_by=COALESCE(?,claimed_by),lease_expires_at=COALESCE(?,lease_expires_at),updated_at=?,started_at=CASE WHEN ?='running' AND started_at IS NULL THEN ? ELSE started_at END,completed_at=CASE WHEN ? IN ('completed','failed','cancelled') THEN ? ELSE completed_at END,error_code=COALESCE(?,error_code),error_message=COALESCE(?,error_message),result_summary=COALESCE(?,result_summary),available_at=COALESCE(?,available_at) WHERE id=?").run(status,data.rootAgentId??null,data.claimedBy??null,data.leaseExpiresAt??null,Date.now(),status,Date.now(),status,Date.now(),data.errorCode??null,data.errorMessage??null,data.resultSummary??null,data.availableAt??null,id);const job=this.getJob(id);if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:id,data:{status:job.status}});return job;}
  recoverStaleJobs(now=Date.now(),availableAt=Date.now()){this.db.prepare("UPDATE jobs SET status='queued',claimed_by=NULL,lease_expires_at=NULL,available_at=?,updated_at=? WHERE (status='claimed' OR status='running') AND lease_expires_at IS NOT NULL AND lease_expires_at<?").run(availableAt,Date.now(),now);}
  createSchedule(input:{id?:string;name?:string;kind:string;expression:string;timezone:string;payload:unknown;misfirePolicy?:string;overlapPolicy?:string;nextRunAt?:number}){const id=input.id??`schedule_${randomUUID()}`,now=Date.now();this.db.prepare("INSERT INTO schedules(id,name,kind,expression,timezone,enabled,payload_json,misfire_policy,overlap_policy,next_run_at,last_run_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?, ?,?,?,NULL,?,?)").run(id,input.name??null,input.kind,input.expression,input.timezone,1,JSON.stringify(input.payload),input.misfirePolicy??"run_once",input.overlapPolicy??"queue",input.nextRunAt??now,now,now);const schedule=this.getSchedule(id);this.appendControlEvent({type:"schedule.updated",resourceType:"schedule",resourceId:id,data:{enabled:schedule?.enabled}});return schedule;}
  getSchedule(id:string){return this.db.prepare("SELECT id,name,kind,expression,timezone,enabled,payload_json as payload,misfire_policy as misfirePolicy,overlap_policy as overlapPolicy,next_run_at as nextRunAt,last_run_at as lastRunAt,created_at as createdAt,updated_at as updatedAt,error_message as errorMessage FROM schedules WHERE id=?").get(id) as any;}
  listSchedules(){return this.db.prepare("SELECT id,name,kind,expression,timezone,enabled,payload_json as payload,misfire_policy as misfirePolicy,overlap_policy as overlapPolicy,next_run_at as nextRunAt,last_run_at as lastRunAt,created_at as createdAt,updated_at as updatedAt,error_message as errorMessage FROM schedules ORDER BY next_run_at").all() as any[];}
  updateSchedule(id:string,data:{enabled?:boolean;nextRunAt?:number|null;lastRunAt?:number|null;errorMessage?:string|null}){const sets:string[]=[],params:unknown[]=[];if(data.enabled!==undefined){sets.push("enabled=?");params.push(data.enabled?1:0)}if(data.nextRunAt!==undefined){sets.push("next_run_at=?");params.push(data.nextRunAt)}if(data.lastRunAt!==undefined){sets.push("last_run_at=?");params.push(data.lastRunAt)}if(Object.prototype.hasOwnProperty.call(data,"errorMessage")){sets.push("error_message=?");params.push(data.errorMessage)}if(sets.length){sets.push("updated_at=?");params.push(Date.now(),id);this.db.prepare(`UPDATE schedules SET ${sets.join(",")} WHERE id=?`).run(...params)}const schedule=this.getSchedule(id);if(schedule)this.appendControlEvent({type:"schedule.updated",resourceType:"schedule",resourceId:id,data:{enabled:schedule.enabled}});return schedule;}
  materializeSchedule(scheduleId:string,intended:number,payload:unknown){return this.transaction(()=>{const current=this.db.prepare("SELECT enabled,next_run_at as nextRunAt FROM schedules WHERE id=? AND enabled=1 AND next_run_at=?").get(scheduleId,intended) as any;if(!current)return undefined;const existing=this.db.prepare("SELECT job_id as jobId FROM schedule_occurrences WHERE schedule_id=? AND intended_run_at=?").get(scheduleId,intended) as any;if(existing)return this.getJob(existing.jobId);const job=this.enqueueJob({type:"scheduled_agent_run",payload,scheduleId,idempotencyKey:`schedule:${scheduleId}:${intended}`});this.db.prepare("INSERT INTO schedule_occurrences(id,schedule_id,intended_run_at,job_id,created_at) VALUES(?,?,?,?,?)").run(randomUUID(),scheduleId,intended,job.id,Date.now());return job;});}
  get<T>(key:string):T|undefined{const row=this.db.prepare("SELECT value FROM runtime_kv WHERE key=?").get(key) as {value:string}|undefined;return row?JSON.parse(row.value) as T:undefined;}
  set<T>(key:string,value:T):void{this.db.prepare("INSERT INTO runtime_kv(key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(key,JSON.stringify(value),new Date().toISOString());}
  recordPlanRevision(input:{planId:string;rootAgentId:string;version:number;previousVersion?:number;reason?:string;proposal:unknown;status?:string}){this.db.prepare("INSERT OR IGNORE INTO plan_revisions (id,plan_id,root_agent_id,version,previous_version,reason,proposal,status,created_at) VALUES (?,?,?,?,?,?,?,?,?)").run(`${input.planId}:v${input.version}`,input.planId,input.rootAgentId,input.version,input.previousVersion??null,input.reason??null,JSON.stringify(input.proposal),input.status??"proposed",new Date().toISOString());return this.getPlanRevision(input.planId,input.version);}
  getPlanRevision(planId:string,version:number){return this.db.prepare("SELECT id,plan_id as planId,root_agent_id as rootAgentId,version,previous_version as previousVersion,reason,proposal,status,created_at as createdAt FROM plan_revisions WHERE plan_id=? AND version=?").get(planId,version) as any;}
  listPlanRevisions(planId:string){return this.db.prepare("SELECT id,plan_id as planId,root_agent_id as rootAgentId,version,previous_version as previousVersion,reason,proposal,status,created_at as createdAt FROM plan_revisions WHERE plan_id=? ORDER BY version").all(planId) as any[];}
  recordExecutionRound(input:{id?:string;rootAgentId:string;taskId:string;round:number;checkpointId?:string;status:string;toolCalls?:unknown;messages?:unknown;summary?:string}){const id=input.id??`${input.taskId}:r${input.round}`;this.db.prepare("INSERT OR IGNORE INTO execution_rounds (id,root_agent_id,task_id,round,checkpoint_id,status,tool_calls,messages,summary,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id,input.rootAgentId,input.taskId,input.round,input.checkpointId??null,input.status,JSON.stringify(input.toolCalls??[]),JSON.stringify(input.messages??[]),input.summary??null,new Date().toISOString());return id;}
  listExecutionRounds(taskId:string){return this.db.prepare("SELECT id,root_agent_id as rootAgentId,task_id as taskId,round,checkpoint_id as checkpointId,status,tool_calls as toolCalls,messages,summary,created_at as createdAt FROM execution_rounds WHERE task_id=? ORDER BY round").all(taskId) as any[];}
  recordReview(input:{id?:string;rootAgentId:string;taskId:string;round:number;verdict:string;summary:string;issues?:unknown;reviewId?:string}){const id=input.id??`${input.taskId}:review${input.round}`;this.db.prepare("INSERT OR IGNORE INTO review_records (id,root_agent_id,task_id,review_id,round,verdict,summary,issues,created_at) VALUES (?,?,?,?,?,?,?,?,?)").run(id,input.rootAgentId,input.taskId,input.reviewId??id,input.round,input.verdict,input.summary,JSON.stringify(input.issues??[]),new Date().toISOString());return id;}
  listReviews(taskId:string){return this.db.prepare("SELECT id,root_agent_id as rootAgentId,task_id as taskId,review_id as reviewId,round,verdict,summary,issues,created_at as createdAt FROM review_records WHERE task_id=? ORDER BY round").all(taskId) as any[];}
  recordRepair(input:{id?:string;rootAgentId:string;taskId:string;round:number;reviewId:string;status:string;instruction?:unknown}){const id=input.id??`${input.taskId}:repair${input.round}`;this.db.prepare("INSERT OR IGNORE INTO repair_rounds (id,root_agent_id,task_id,review_id,round,status,instruction,created_at) VALUES (?,?,?,?,?,?,?,?)").run(id,input.rootAgentId,input.taskId,input.reviewId,input.round,input.status,JSON.stringify(input.instruction??{}),new Date().toISOString());return id;}
  listRepairs(taskId:string){return this.db.prepare("SELECT id,root_agent_id as rootAgentId,task_id as taskId,review_id as reviewId,round,status,instruction,created_at as createdAt FROM repair_rounds WHERE task_id=? ORDER BY round").all(taskId) as any[];}
  recordTestEvidence(input:{id?:string;rootAgentId:string;taskId:string;checkpointId?:string;level:string;command:string;exitCode:number;durationMs:number;stdout?:string;stderr?:string;selectedBecause?:string}){const id=input.id??randomUUID();this.db.prepare("INSERT OR IGNORE INTO test_evidence (id,root_agent_id,task_id,checkpoint_id,level,command,exit_code,duration_ms,stdout_summary,stderr_summary,selected_because,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").run(id,input.rootAgentId,input.taskId,input.checkpointId??null,input.level,input.command,input.exitCode,input.durationMs,(input.stdout??"").slice(0,2000),(input.stderr??"").slice(0,2000),input.selectedBecause??null,new Date().toISOString());return id;}
  listTestEvidence(taskId:string){return this.db.prepare("SELECT id,root_agent_id as rootAgentId,task_id as taskId,checkpoint_id as checkpointId,level,command,exit_code as exitCode,duration_ms as durationMs,stdout_summary as stdout,stderr_summary as stderr,selected_because as selectedBecause,created_at as createdAt FROM test_evidence WHERE task_id=? ORDER BY created_at").all(taskId) as any[];}

  createAgent(task:string,id:string=randomUUID()):Agent{return this.createAgentRecord({id,goal:task,task,role:"general"});}
  createAgentRecord(input:{id?:string;goal:string;task?:string;role?:AgentRole;parentAgentId?:string;rootAgentId?:string}):Agent{
    const id=input.id??`agent_${randomUUID()}`;const parent=input.parentAgentId?this.getAgent(input.parentAgentId):undefined;
    if(input.parentAgentId&&!parent)throw new Error(`parent agent not found: ${input.parentAgentId}`);
    const rootAgentId=input.rootAgentId??parent?.rootAgentId??id;const now=new Date().toISOString();
    this.db.prepare("INSERT INTO agents (id,task,status,created_at,updated_at,result,error,parent_agent_id,root_agent_id,role,goal) VALUES (?,?,?,?,?,NULL,NULL,?,?,?,?)").run(id,input.task??input.goal,"created",now,now,input.parentAgentId??null,rootAgentId,input.role??"general",input.goal);
    return this.getAgent(id)!;
  }
  getAgent(id:string):Agent|undefined{return this.db.prepare(`${agentSelect} WHERE id=?`).get(id) as Agent|undefined;}
  listAgents(rootAgentId?:string):Agent[]{return (rootAgentId?this.db.prepare(`${agentSelect} WHERE root_agent_id=? ORDER BY created_at`).all(rootAgentId):this.db.prepare(`${agentSelect} ORDER BY created_at DESC`).all()) as Agent[];}
  listChildren(parentAgentId:string):Agent[]{return this.db.prepare(`${agentSelect} WHERE parent_agent_id=? ORDER BY created_at`).all(parentAgentId) as Agent[];}
  updateAgent(id:string,status:AgentStatus,result?:string,error?:string):void{this.db.prepare("UPDATE agents SET status=?,result=COALESCE(?,result),error=COALESCE(?,error),updated_at=? WHERE id=?").run(status,result??null,error??null,new Date().toISOString(),id);this.appendControlEvent({type:"agent.updated",resourceType:"agent",resourceId:id,data:{status}});}

  saveCheckpoint(c:Checkpoint):void{this.db.prepare("INSERT OR REPLACE INTO checkpoints (agent_id,step,messages,status,result) VALUES (?,?,?,?,?)").run(c.agentId,c.step,JSON.stringify(c.messages),c.status,c.result??null);}
  getCheckpoint(id:string):Checkpoint|undefined{const row=this.db.prepare("SELECT agent_id as agentId,step,messages,status,result FROM checkpoints WHERE agent_id=?").get(id) as (Omit<Checkpoint,"messages">&{messages:string})|undefined;return row?{...row,messages:JSON.parse(row.messages) as Message[]}:undefined;}

  addTrace(agentId:string,type:string,data:Record<string,unknown>,correlation:TraceCorrelation={}):void{
    const agent=this.getAgent(agentId);const merged={rootAgentId:agent?.rootAgentId,parentAgentId:agent?.parentAgentId,...correlation};
    this.db.prepare("INSERT INTO traces(agent_id,type,data,created_at,root_agent_id,parent_agent_id,task_id,delegation_id,message_id,tool_call_id,checkpoint_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(agentId,type,JSON.stringify(redactTraceData(data)),new Date().toISOString(),merged.rootAgentId??null,merged.parentAgentId??null,merged.taskId??null,merged.delegationId??null,merged.messageId??null,merged.toolCallId??null,merged.checkpointId??null);
  }
  getTrace(id:string,rootTimeline=false):TraceEvent[]{
    const select="SELECT id,agent_id as agentId,type,data,created_at as createdAt,root_agent_id as rootAgentId,parent_agent_id as parentAgentId,task_id as taskId,delegation_id as delegationId,message_id as messageId,tool_call_id as toolCallId,checkpoint_id as checkpointId FROM traces";
    const rows=(rootTimeline?this.db.prepare(`${select} WHERE root_agent_id=? ORDER BY id`).all(id):this.db.prepare(`${select} WHERE agent_id=? ORDER BY id`).all(id)) as Array<TraceEvent&{data:string}>;return rows.map(row=>({...row,data:JSON.parse(row.data)}));
  }

  listMemory(agentId:string):MemoryEntry[]{return this.db.prepare("SELECT agent_id as agentId,key,value,updated_at as updatedAt FROM working_memory WHERE agent_id=? ORDER BY key").all(agentId) as MemoryEntry[];}
  putMemory(agentId:string,key:string,value:string):void{this.db.prepare("INSERT OR REPLACE INTO working_memory VALUES (?,?,?,?)").run(agentId,key,value,new Date().toISOString());}
  deleteMemory(agentId:string,key:string):void{this.db.prepare("DELETE FROM working_memory WHERE agent_id=? AND key=?").run(agentId,key);}
  clearMemory(agentId:string):void{this.db.prepare("DELETE FROM working_memory WHERE agent_id=?").run(agentId);}
  putScopedMemory(input:{agentId:string;scope:MemoryScope;key:string;value:string;visibility?:Visibility;allowProjectWrite?:boolean}):void{const agent=this.getAgent(input.agentId);if(!agent)throw new Error(`agent not found: ${input.agentId}`);if(input.scope==="project"&&!input.allowProjectWrite)throw new Error("project memory write requires explicit policy");this.db.prepare("INSERT OR REPLACE INTO scoped_memory VALUES (?,?,?,?,?,?,?)").run(agent.id,agent.rootAgentId,input.scope,input.visibility??"private",input.key,input.value,new Date().toISOString());}
  listVisibleMemory(agentId:string):MemoryEntry[]{const agent=this.getAgent(agentId);if(!agent)throw new Error(`agent not found: ${agentId}`);const rows=this.db.prepare("SELECT agent_id as agentId,root_agent_id as rootAgentId,scope,visibility,key,value,updated_at as updatedAt FROM scoped_memory WHERE agent_id=? OR (root_agent_id=? AND scope='root-task' AND visibility='team-visible') OR (scope='project' AND visibility!='private') ORDER BY updated_at").all(agent.id,agent.rootAgentId) as MemoryEntry[];return [...this.listMemory(agent.id),...rows];}

  getToolExecution(id:string){return this.db.prepare("SELECT tool_call_id as toolCallId,agent_id as agentId,tool_name as toolName,input,status,result,error,updated_at as updatedAt FROM tool_execution_ledger WHERE tool_call_id=?").get(id) as {toolCallId:string;agentId:string;toolName:string;input:string;status:string;result?:string;error?:string;updatedAt:string}|undefined;}
  recordToolExecution(id:string,agentId:string,name:string,input:Record<string,unknown>,status:string,result?:string,error?:string):void{this.db.prepare("INSERT OR REPLACE INTO tool_execution_ledger VALUES (?,?,?,?,?,?,?,?)").run(id,agentId,name,JSON.stringify(input),status,result??null,error??null,new Date().toISOString());}

  createPlan(agentId:string,goal:string,id=`plan_${randomUUID()}`):Plan{const now=new Date().toISOString();this.db.prepare("INSERT INTO plans VALUES (?,?,?,?,?,?,?)").run(id,agentId,goal,"running","plan",now,now);return this.getPlan(id)!;}
  getPlan(id:string):Plan|undefined{return this.db.prepare("SELECT id,agent_id as agentId,goal,status,phase,created_at as createdAt,updated_at as updatedAt FROM plans WHERE id=?").get(id) as Plan|undefined;}
  getPlanForAgent(agentId:string):Plan|undefined{return this.db.prepare("SELECT id,agent_id as agentId,goal,status,phase,created_at as createdAt,updated_at as updatedAt FROM plans WHERE agent_id=? ORDER BY created_at DESC LIMIT 1").get(agentId) as Plan|undefined;}
  updatePlan(id:string,status:AgentStatus,phase:ExecutionPhase):void{this.db.prepare("UPDATE plans SET status=?,phase=?,updated_at=? WHERE id=?").run(status,phase,new Date().toISOString(),id);}
  addPlanTask(input:{id?:string;planId:string;title:string;kind:string;dependencies?:string[];maxRetries?:number;position:number}):PlanTask{const id=input.id??`task_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO plan_tasks (id,plan_id,title,kind,status,dependencies,retry_count,max_retries,failure_policy,blocked_reason,result,position,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,NULL,NULL,NULL,?,?,?)").run(id,input.planId,input.title,input.kind,"pending",JSON.stringify(input.dependencies??[]),0,input.maxRetries??1,input.position,now,now);return this.getPlanTask(id)!;}
  getPlanTask(id:string):PlanTask|undefined{const row=this.db.prepare(`${taskSelect} WHERE id=?`).get(id) as (Omit<PlanTask,"dependencies">&{dependencies:string})|undefined;return row?{...row,dependencies:JSON.parse(row.dependencies)}:undefined;}
  listPlanTasks(planId:string):PlanTask[]{return (this.db.prepare(`${taskSelect} WHERE plan_id=? ORDER BY position`).all(planId) as Array<Omit<PlanTask,"dependencies">&{dependencies:string}>).map(row=>({...row,dependencies:JSON.parse(row.dependencies)}));}
  updatePlanTask(id:string,status:TaskStatus,data:{result?:string;failurePolicy?:FailurePolicy;blockedReason?:string;incrementRetry?:boolean;ownerAgentId?:string|null}={}):void{this.db.prepare("UPDATE plan_tasks SET status=?,result=COALESCE(?,result),failure_policy=COALESCE(?,failure_policy),blocked_reason=COALESCE(?,blocked_reason),retry_count=retry_count+?,owner_agent_id=CASE WHEN ? IS NULL THEN owner_agent_id ELSE ? END,updated_at=? WHERE id=?").run(status,data.result??null,data.failurePolicy??null,data.blockedReason??null,data.incrementRetry?1:0,data.ownerAgentId===undefined?null:"set",data.ownerAgentId??null,new Date().toISOString(),id);}

  createApproval(input:{agentId:string;taskId?:string;toolCallId?:string;toolName:string;input:Record<string,unknown>;reason?:string}):ApprovalRequest{const existing=input.toolCallId?this.getApprovalByToolCall(input.toolCallId):undefined;if(existing)return existing;const agent=this.getAgent(input.agentId);const id=`approval_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO approval_requests (id,agent_id,task_id,tool_call_id,tool_name,input,status,created_at,decided_at,role,reason,arguments_summary) VALUES (?,?,?,?,?,?,?,?,NULL,?,?,?)").run(id,input.agentId,input.taskId??null,input.toolCallId??null,input.toolName,JSON.stringify(input.input),"pending",now,agent?.role??null,input.reason??`permission policy requires approval for ${input.toolName}`,JSON.stringify(input.input).slice(0,500));const approval=this.getApproval(id)!;this.appendControlEvent({type:"approval.created",resourceType:"approval",resourceId:id,data:{status:approval.status,agentId:approval.agentId}});return approval;}
  getApproval(id:string):ApprovalRequest|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,tool_call_id as toolCallId,tool_name as toolName,input,status,created_at as createdAt,decided_at as decidedAt,role,reason,arguments_summary as argumentsSummary FROM approval_requests WHERE id=?").get(id) as (Omit<ApprovalRequest,"input">&{input:string})|undefined;return row?{...row,input:JSON.parse(row.input)}:undefined;}
  getApprovalByToolCall(id:string):ApprovalRequest|undefined{const row=this.db.prepare("SELECT id FROM approval_requests WHERE tool_call_id=? ORDER BY created_at DESC LIMIT 1").get(id) as {id:string}|undefined;return row?this.getApproval(row.id):undefined;}
  resolveApproval(id:string,status:"approved"|"denied"):void{this.db.prepare("UPDATE approval_requests SET status=?,decided_at=? WHERE id=?").run(status,new Date().toISOString(),id);this.appendControlEvent({type:"approval.resolved",resourceType:"approval",resourceId:id,data:{status}});}
  listApprovals(agentId?:string):ApprovalRequest[]{const rows=(agentId?this.db.prepare("SELECT id FROM approval_requests WHERE agent_id=? ORDER BY created_at DESC").all(agentId):this.db.prepare("SELECT id FROM approval_requests ORDER BY created_at DESC").all()) as Array<{id:string}>;return rows.map(row=>this.getApproval(row.id)!);}
  listApprovalsForRoot(rootAgentId:string):ApprovalRequest[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listApprovals(agent.id));}

  addArtifact(input:{agentId:string;taskId?:string;checkpointId?:string;path:string;type?:string;operation:ArtifactOperation;visibility?:Visibility}):Artifact{const existing=this.db.prepare("SELECT id FROM artifacts WHERE agent_id=? AND COALESCE(task_id,'')=COALESCE(?,'') AND COALESCE(checkpoint_id,'')=COALESCE(?,'') AND path=? AND operation=? LIMIT 1").get(input.agentId,input.taskId??null,input.checkpointId??null,input.path,input.operation) as {id:string}|undefined;if(existing)return this.getArtifact(existing.id)!;const id=`artifact_${randomUUID()}`;this.db.prepare("INSERT INTO artifacts (id,agent_id,task_id,checkpoint_id,path,operation,created_at,type,visibility) VALUES (?,?,?,?,?,?,?,?,?)").run(id,input.agentId,input.taskId??null,input.checkpointId??null,input.path,input.operation,new Date().toISOString(),input.type??"file",input.visibility??"parent-visible");return this.getArtifact(id)!;}
  getArtifact(id:string):Artifact|undefined{return this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE id=?").get(id) as Artifact|undefined;}
  listArtifacts(agentId:string,taskId?:string):Artifact[]{return (taskId?this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE agent_id=? AND task_id=? ORDER BY created_at").all(agentId,taskId):this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE agent_id=? ORDER BY created_at").all(agentId)) as Artifact[];}
  listArtifactsForRoot(rootAgentId:string):Artifact[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listArtifacts(agent.id).filter(artifact=>artifact.agentId===rootAgentId||artifact.visibility!=="private"));}

  createTaskCheckpoint(input:{agentId:string;planId:string;taskId?:string;phase:ExecutionPhase;step:number;snapshot:Record<string,unknown>}):TaskCheckpoint{const id=`cp_${randomUUID()}`;this.db.prepare("INSERT INTO task_checkpoints VALUES (?,?,?,?,?,?,?,?)").run(id,input.agentId,input.planId,input.taskId??null,input.phase,input.step,JSON.stringify(input.snapshot),new Date().toISOString());this.addTrace(input.agentId,"checkpoint.created",{checkpointId:id,planId:input.planId,taskId:input.taskId,phase:input.phase,step:input.step},{taskId:input.taskId,checkpointId:id});return this.getTaskCheckpoint(id)!;}
  getTaskCheckpoint(id:string):TaskCheckpoint|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,plan_id as planId,task_id as taskId,phase,step,snapshot,created_at as createdAt FROM task_checkpoints WHERE id=?").get(id) as (Omit<TaskCheckpoint,"snapshot">&{snapshot:string})|undefined;return row?{...row,snapshot:JSON.parse(row.snapshot)}:undefined;}
  latestTaskCheckpoint(agentId:string):TaskCheckpoint|undefined{const row=this.db.prepare("SELECT id FROM task_checkpoints WHERE agent_id=? ORDER BY created_at DESC LIMIT 1").get(agentId) as {id:string}|undefined;return row?this.getTaskCheckpoint(row.id):undefined;}

  createChildAndDelegation(input:{parentAgentId:string;taskId?:string;goal:string;role:AgentRole;childAgentId?:string;delegationId?:string}):{agent:Agent;delegation:Delegation}{return this.transaction(()=>{const parent=this.getAgent(input.parentAgentId);if(!parent)throw new Error(`parent agent not found: ${input.parentAgentId}`);if(input.taskId){const active=this.getActiveDelegationForTask(input.parentAgentId,input.taskId);if(active)return {agent:this.getAgent(active.childAgentId)!,delegation:active};}const agent=this.createAgentRecord({id:input.childAgentId,goal:input.goal,task:input.goal,role:input.role,parentAgentId:parent.id,rootAgentId:parent.rootAgentId});const id=input.delegationId??`delegation_${randomUUID()}`;this.db.prepare("INSERT INTO delegations (id,parent_agent_id,child_agent_id,task_id,goal,status,created_at) VALUES (?,?,?,?,?,'assigned',?)").run(id,parent.id,agent.id,input.taskId??null,input.goal,new Date().toISOString());return {agent,delegation:this.getDelegation(id)!};});}
  getDelegation(id:string):Delegation|undefined{return this.db.prepare("SELECT id,parent_agent_id as parentAgentId,child_agent_id as childAgentId,task_id as taskId,goal,status,failure_policy as failurePolicy,created_at as createdAt,started_at as startedAt,completed_at as completedAt,result_summary as resultSummary,failure_reason as failureReason FROM delegations WHERE id=?").get(id) as Delegation|undefined;}
  getDelegationForTask(parentAgentId:string,taskId:string):Delegation|undefined{const row=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? AND task_id=? ORDER BY created_at DESC LIMIT 1").get(parentAgentId,taskId) as {id:string}|undefined;return row?this.getDelegation(row.id):undefined;}
  getActiveDelegationForTask(parentAgentId:string,taskId:string):Delegation|undefined{const row=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? AND task_id=? AND status IN ('created','assigned','running','waiting') ORDER BY created_at DESC LIMIT 1").get(parentAgentId,taskId) as {id:string}|undefined;return row?this.getDelegation(row.id):undefined;}
  listDelegations(agentId:string):Delegation[]{const rows=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? OR child_agent_id=? ORDER BY created_at").all(agentId,agentId) as Array<{id:string}>;return rows.map(row=>this.getDelegation(row.id)!);}
  listDelegationsForRoot(rootAgentId:string):Delegation[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listDelegations(agent.id)).filter((item,index,all)=>all.findIndex(other=>other.id===item.id)===index);}
  updateDelegation(id:string,status:DelegationStatus,data:{failurePolicy?:FailurePolicy|"cancelled";resultSummary?:string;failureReason?:string}={}):void{const now=new Date().toISOString();this.db.prepare("UPDATE delegations SET status=?,failure_policy=COALESCE(?,failure_policy),result_summary=COALESCE(?,result_summary),failure_reason=COALESCE(?,failure_reason),started_at=CASE WHEN ?='running' AND started_at IS NULL THEN ? ELSE started_at END,completed_at=CASE WHEN ? IN ('completed','failed','cancelled') THEN ? ELSE completed_at END WHERE id=?").run(status,data.failurePolicy??null,data.resultSummary??null,data.failureReason??null,status,now,status,now,id);}

  sendAgentMessage(input:{fromAgentId:string;toAgentId:string;type:AgentMessageType;payload:unknown;visibility?:Visibility;id?:string}):AgentMessage{const from=this.getAgent(input.fromAgentId);const to=this.getAgent(input.toAgentId);if(!from||!to)throw new Error("message sender or recipient not found");if(from.rootAgentId!==to.rootAgentId)throw new Error("cross-root messages are not supported");const id=input.id??`message_${randomUUID()}`;this.db.prepare("INSERT INTO agent_messages VALUES (?,?,?,?,?,?,?,?,NULL,NULL)").run(id,from.rootAgentId,from.id,to.id,input.type,JSON.stringify(input.payload),input.visibility??"parent-visible",new Date().toISOString());return this.getAgentMessage(id)!;}
  getAgentMessage(id:string):AgentMessage|undefined{const row=this.db.prepare("SELECT id,root_agent_id as rootAgentId,from_agent_id as fromAgentId,to_agent_id as toAgentId,type,payload,visibility,created_at as createdAt,delivered_at as deliveredAt,acknowledged_at as acknowledgedAt FROM agent_messages WHERE id=?").get(id) as (Omit<AgentMessage,"payload">&{payload:string})|undefined;return row?{...row,payload:JSON.parse(row.payload)}:undefined;}
  receiveAgentMessages(agentId:string):AgentMessage[]{const now=new Date().toISOString();this.db.prepare("UPDATE agent_messages SET delivered_at=COALESCE(delivered_at,?) WHERE to_agent_id=?").run(now,agentId);return this.listAgentMessages(agentId).filter(message=>!message.acknowledgedAt);}
  acknowledgeAgentMessage(id:string):void{const now=new Date().toISOString();this.db.prepare("UPDATE agent_messages SET delivered_at=COALESCE(delivered_at,?),acknowledged_at=COALESCE(acknowledged_at,?) WHERE id=?").run(now,now,id);}
  listAgentMessages(agentId:string):AgentMessage[]{const rows=this.db.prepare("SELECT id FROM agent_messages WHERE from_agent_id=? OR to_agent_id=? ORDER BY created_at").all(agentId,agentId) as Array<{id:string}>;return rows.map(row=>this.getAgentMessage(row.id)!);}

  completeDelegationWithResult(delegationId:string,result:AgentResult):AgentResult{return this.transaction(()=>{const existing=this.getAgentResultByDelegation(delegationId);if(existing)return existing;const delegation=this.getDelegation(delegationId);if(!delegation)throw new Error(`delegation not found: ${delegationId}`);const id=`result_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO agent_results VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(id,delegation.childAgentId,delegation.id,result.status,result.summary,JSON.stringify(result.artifacts??[]),JSON.stringify(result.taskUpdates??[]),JSON.stringify(result.findings??{}),result.failurePolicy??null,result.error??null,now);this.updateDelegation(delegation.id,result.status==="completed"?"completed":"failed",{failurePolicy:result.failurePolicy,resultSummary:result.summary,failureReason:result.error});this.updateAgent(delegation.childAgentId,result.status==="completed"?"completed":"failed",result.status==="completed"?result.summary:undefined,result.error);const message=this.sendAgentMessage({id:`message_result_${delegation.id}`,fromAgentId:delegation.childAgentId,toAgentId:delegation.parentAgentId,type:result.status==="completed"?"response":"error",payload:{delegationId:delegation.id,resultId:id,status:result.status,summary:result.summary},visibility:"parent-visible"});this.addTrace(delegation.childAgentId,"message.sent",{toAgentId:delegation.parentAgentId,type:message.type},{taskId:delegation.taskId,delegationId:delegation.id,messageId:message.id});return this.getAgentResult(id)!;});}
  getAgentResult(id:string):AgentResult|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,delegation_id as delegationId,status,summary,artifacts,task_updates as taskUpdates,findings,failure_policy as failurePolicy,error,created_at as createdAt FROM agent_results WHERE id=?").get(id) as (AgentResult&{artifacts:string;taskUpdates:string;findings:string})|undefined;return row?{...row,artifacts:JSON.parse(row.artifacts),taskUpdates:JSON.parse(row.taskUpdates),findings:JSON.parse(row.findings)}:undefined;}
  getAgentResultByDelegation(delegationId:string):AgentResult|undefined{const row=this.db.prepare("SELECT id FROM agent_results WHERE delegation_id=?").get(delegationId) as {id:string}|undefined;return row?this.getAgentResult(row.id):undefined;}

  acquireTaskLease(taskId:string,agentId:string,ttlMs=30000,leaseId=`lease_${randomUUID()}`):TaskLease|undefined{return this.transaction(()=>{const task=this.getPlanTask(taskId);if(!task)throw new Error(`task not found: ${taskId}`);const now=new Date();if(task.leaseId&&task.leaseExpiresAt&&new Date(task.leaseExpiresAt)>now)return task.ownerAgentId===agentId?this.getTaskLease(task.leaseId):undefined;if(task.leaseId)this.db.prepare("UPDATE task_leases SET status='expired',released_at=? WHERE id=? AND status='active'").run(now.toISOString(),task.leaseId);const expiresAt=new Date(now.getTime()+ttlMs).toISOString();this.db.prepare("INSERT INTO task_leases VALUES (?,?,?,'active',?,?,NULL)").run(leaseId,taskId,agentId,now.toISOString(),expiresAt);this.db.prepare("UPDATE plan_tasks SET owner_agent_id=?,lease_id=?,lease_expires_at=?,updated_at=? WHERE id=?").run(agentId,leaseId,expiresAt,now.toISOString(),taskId);return this.getTaskLease(leaseId);});}
  getTaskLease(id:string):TaskLease|undefined{return this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases WHERE id=?").get(id) as TaskLease|undefined;}
  releaseTaskLease(taskId:string,status:"released"|"cancelled"="released"):void{const task=this.getPlanTask(taskId);if(!task?.leaseId)return;this.transaction(()=>{this.db.prepare("UPDATE task_leases SET status=?,released_at=? WHERE id=? AND status='active'").run(status,new Date().toISOString(),task.leaseId!);this.db.prepare("UPDATE plan_tasks SET lease_id=NULL,lease_expires_at=NULL,updated_at=? WHERE id=?").run(new Date().toISOString(),taskId);});}
  listTaskLeases(agentId?:string):TaskLease[]{return (agentId?this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases WHERE agent_id=? ORDER BY acquired_at").all(agentId):this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases ORDER BY acquired_at").all()) as TaskLease[];}
  recordCoordinationDecision(input:{rootAgentId:string;agentId:string;taskId?:string;delegationId?:string;decision:string;reason:string}):void{this.db.prepare("INSERT INTO coordination_decisions VALUES (?,?,?,?,?,?,?,?)").run(`decision_${randomUUID()}`,input.rootAgentId,input.agentId,input.taskId??null,input.delegationId??null,input.decision,input.reason,new Date().toISOString());}

  createOperatorCredential(input:{id?:string;name:string;tokenHash:string;enabled?:boolean;role?:"viewer"|"operator";createdAt?:number}){const id=input.id??`operator_${randomUUID()}`,createdAt=input.createdAt??Date.now();this.db.prepare("INSERT INTO operator_credentials(id,name,role,token_hash,enabled,created_at) VALUES(?,?,?,?,?,?)").run(id,input.name,input.role??"operator",input.tokenHash,input.enabled===false?0:1,createdAt);return this.getOperatorCredential(id);}
  getOperatorCredential(id:string){const row=this.db.prepare("SELECT id,name,role,token_hash as tokenHash,enabled,created_at as createdAt,last_used_at as lastUsedAt FROM operator_credentials WHERE id=?").get(id) as any;if(row)row.enabled=Boolean(row.enabled);return row;}
  findOperatorCredentialByTokenHash(tokenHash:string){const row=this.db.prepare("SELECT id,name,role,token_hash as tokenHash,enabled,created_at as createdAt,last_used_at as lastUsedAt FROM operator_credentials WHERE token_hash=?").get(tokenHash) as any;if(row)row.enabled=Boolean(row.enabled);return row;}
  createOperatorSession(input:{id:string;credentialId:string;sessionHash:string;csrfHash:string;createdAt:number;expiresAt:number;lastSeenAt:number}){this.db.prepare("INSERT INTO operator_sessions(id,credential_id,session_hash,csrf_hash,created_at,last_seen_at,expires_at,revoked_at) VALUES(?,?,?,?,?,?,?,NULL)").run(input.id,input.credentialId,input.sessionHash,input.csrfHash,input.createdAt,input.lastSeenAt,input.expiresAt);return this.getOperatorSession(input.sessionHash);}
  getOperatorSession(sessionHash:string){return this.db.prepare("SELECT id,credential_id as credentialId,session_hash as sessionHash,csrf_hash as csrfHash,created_at as createdAt,last_seen_at as lastSeenAt,expires_at as expiresAt,revoked_at as revokedAt FROM operator_sessions WHERE session_hash=?").get(sessionHash) as any;}
  rotateOperatorSessionCsrf(id:string,csrfHash:string,lastSeenAt:number){this.db.prepare("UPDATE operator_sessions SET csrf_hash=?,last_seen_at=? WHERE id=? AND revoked_at IS NULL AND expires_at>?").run(csrfHash,lastSeenAt,id,lastSeenAt);return this.db.prepare("SELECT id,credential_id as credentialId,session_hash as sessionHash,csrf_hash as csrfHash,created_at as createdAt,last_seen_at as lastSeenAt,expires_at as expiresAt,revoked_at as revokedAt FROM operator_sessions WHERE id=?").get(id) as any;}
  touchOperatorSession(id:string,lastSeenAt:number){this.db.prepare("UPDATE operator_sessions SET last_seen_at=? WHERE id=? AND revoked_at IS NULL AND expires_at>?").run(lastSeenAt,id,lastSeenAt);}
  revokeOperatorSession(id:string,revokedAt=Date.now()){this.db.prepare("UPDATE operator_sessions SET revoked_at=? WHERE id=? AND revoked_at IS NULL").run(revokedAt,id);}
  recordOperatorAudit(input:{requestId:string;actorId?:string;sessionFingerprint?:string;action:string;resourceType?:string;resourceId?:string;outcome:"success"|"denied"|"error";httpStatus:number;sourceAddress?:string;details?:Record<string,unknown>;createdAt?:number}){const result=this.db.prepare("INSERT INTO operator_audit(request_id,actor_id,session_fingerprint,action,resource_type,resource_id,outcome,http_status,source_address,details_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(input.requestId,input.actorId??null,input.sessionFingerprint??null,input.action,input.resourceType??null,input.resourceId??null,input.outcome,input.httpStatus,input.sourceAddress??null,JSON.stringify(input.details??{}),input.createdAt??Date.now()) as any;return this.listOperatorAudit({afterId:Number(result.lastInsertRowid)-1,limit:1})[0];}
  listOperatorAudit(input:{afterId?:number;limit?:number;action?:string;resourceType?:string}={}){const limit=Math.max(1,Math.min(200,input.limit??50)),clauses=["id>?"],params:any[]=[input.afterId??0];if(input.action){clauses.push("action=?");params.push(input.action);}if(input.resourceType){clauses.push("resource_type=?");params.push(input.resourceType);}params.push(limit);const rows=this.db.prepare(`SELECT id,request_id as requestId,actor_id as actorId,session_fingerprint as sessionFingerprint,action,resource_type as resourceType,resource_id as resourceId,outcome,http_status as httpStatus,source_address as sourceAddress,details_json as details,created_at as createdAt FROM operator_audit WHERE ${clauses.join(" AND ")} ORDER BY id LIMIT ?`).all(...params) as any[];return rows.map(row=>({...row,details:JSON.parse(row.details)}));}
  appendControlEvent(input:{type:string;resourceType?:string;resourceId?:string;data?:unknown;createdAt?:number}){const result=this.db.prepare("INSERT INTO control_events(type,resource_type,resource_id,data_json,created_at) VALUES(?,?,?,?,?)").run(input.type,input.resourceType??null,input.resourceId??null,JSON.stringify(input.data??{}),input.createdAt??Date.now()) as any;return this.listControlEvents({afterId:Number(result.lastInsertRowid)-1,limit:1})[0];}
  listControlEvents(input:{afterId?:number;limit?:number}={}){const limit=Math.max(1,Math.min(200,input.limit??50));const rows=this.db.prepare("SELECT id,type,resource_type as resourceType,resource_id as resourceId,data_json as data,created_at as createdAt FROM control_events WHERE id>? ORDER BY id LIMIT ?").all(input.afterId??0,limit) as any[];return rows.map(row=>({...row,data:JSON.parse(row.data)}));}
  cancelJob(id:string,now=Date.now()){const result=this.db.prepare("UPDATE jobs SET status='cancelled',error_message='cancelled by operator',updated_at=?,completed_at=? WHERE id=? AND status IN ('queued','claimed','running','waiting','retry_wait')").run(now,now,id) as any;const job=result.changes?this.getJob(id):undefined;if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:id,data:{status:job.status}});return job;}
  retryJob(id:string,now=Date.now()){const result=this.db.prepare("UPDATE jobs SET status='queued',attempt=0,available_at=?,claimed_by=NULL,lease_expires_at=NULL,updated_at=?,completed_at=NULL,error_code=NULL,error_message=NULL,waiting_reason=NULL,waiting_ref=NULL WHERE id=? AND status IN ('failed','cancelled')").run(now,now,id) as any;const job=result.changes?this.getJob(id):undefined;if(job)this.appendControlEvent({type:"job.updated",resourceType:"job",resourceId:id,data:{status:job.status}});return job;}
  resolveApprovalIfPending(id:string,decision:"approved"|"denied"){const result=this.db.prepare("UPDATE approval_requests SET status=?,decided_at=? WHERE id=? AND status='pending'").run(decision,new Date().toISOString(),id) as any;const approval=result.changes?this.getApproval(id):undefined;if(approval)this.appendControlEvent({type:"approval.resolved",resourceType:"approval",resourceId:id,data:{status:decision}});return approval;}
  deleteSchedule(id:string){const existing=this.getSchedule(id);if(!existing)return undefined;this.db.prepare("DELETE FROM schedules WHERE id=?").run(id);this.appendControlEvent({type:"schedule.deleted",resourceType:"schedule",resourceId:id});return existing;}
  listWorkerConnections(workerId:string){return this.db.prepare("SELECT connection_id as connectionId,worker_id as workerId,transport,status,connected_at as connectedAt,last_seen_at as lastSeenAt,disconnected_at as disconnectedAt,metadata_json as metadata FROM connections WHERE worker_id=? ORDER BY connected_at DESC").all(workerId).map((row:any)=>({...row,metadata:JSON.parse(row.metadata)}));}
  listRemoteLeases(workerId?:string){return (workerId?this.db.prepare("SELECT id,assignment_id as assignmentId,worker_id as workerId,status,acquired_at as acquiredAt,expires_at as expiresAt,fencing_token as fencingToken,released_at as releasedAt FROM remote_leases WHERE worker_id=? ORDER BY acquired_at DESC").all(workerId):this.db.prepare("SELECT id,assignment_id as assignmentId,worker_id as workerId,status,acquired_at as acquiredAt,expires_at as expiresAt,fencing_token as fencingToken,released_at as releasedAt FROM remote_leases ORDER BY acquired_at DESC").all()) as any[];}
  listRemoteExecutionEvents(assignmentId:string,limit=100){const rows=this.db.prepare("SELECT execution_id as executionId,sequence,message_id as messageId,payload_json as payload,created_at as createdAt FROM execution_events WHERE execution_id=? ORDER BY sequence DESC LIMIT ?").all(assignmentId,Math.max(1,Math.min(200,limit))) as any[];return rows.map(row=>({...row,payload:JSON.parse(row.payload)}));}
  listTraces(input:{type?:string;since?:string;limit?:number}={}){const limit=Math.max(1,Math.min(500,input.limit??100)),clauses:string[]=[],params:any[]=[];if(input.type){clauses.push("type=?");params.push(input.type);}if(input.since){clauses.push("created_at>=?");params.push(input.since);}params.push(limit);const where=clauses.length?` WHERE ${clauses.join(" AND ")}`:"";const rows=this.db.prepare(`SELECT id,agent_id as agentId,type,data,created_at as createdAt,root_agent_id as rootAgentId,parent_agent_id as parentAgentId,task_id as taskId,delegation_id as delegationId,message_id as messageId,tool_call_id as toolCallId,checkpoint_id as checkpointId FROM traces${where} ORDER BY id DESC LIMIT ?`).all(...params) as any[];return rows.map(row=>({...row,data:JSON.parse(row.data)}));}
  activateWorkerConnectionEpoch(workerId:string){return this.transaction(()=>{const now=Date.now(),current=(this.db.prepare("SELECT epoch FROM worker_connection_epochs WHERE worker_id=?").get(workerId) as any)?.epoch??0,epoch=current+1;this.db.prepare("INSERT INTO worker_connection_epochs(worker_id,epoch,updated_at) VALUES(?,?,?) ON CONFLICT(worker_id) DO UPDATE SET epoch=excluded.epoch,updated_at=excluded.updated_at").run(workerId,epoch,now);return epoch;});}
  getWorkerConnectionEpoch(workerId:string){return (this.db.prepare("SELECT epoch FROM worker_connection_epochs WHERE worker_id=?").get(workerId) as any)?.epoch??0;}
}
