import {mkdirSync} from "node:fs";
import {randomUUID} from "node:crypto";
import {createRequire} from "node:module";
import type {
  Agent, AgentMessage, AgentMessageType, AgentResult, AgentRole, AgentStatus,
  ApprovalRequest, Artifact, ArtifactOperation, Checkpoint, Delegation,
  DelegationStatus, ExecutionPhase, FailurePolicy, MemoryEntry, MemoryScope,
  Message, Plan, PlanTask, TaskCheckpoint, TaskLease, TaskStatus, TraceCorrelation,
  TraceEvent, Visibility,
} from "@loom/core";

type Statement={run(...args:unknown[]):unknown;get(...args:unknown[]):unknown;all(...args:unknown[]):unknown[]};
type Database={exec(sql:string):void;prepare(sql:string):Statement;pragma(sql:string):unknown;close?():void};

function loadDatabase(filename:string):Database{
  const req=createRequire(import.meta.url);const mod=process.versions.bun?req("bun:sqlite"):req("node:sqlite");
  if(process.versions.bun){const db=new mod.Database(filename);return {exec:(sql)=>db.run(sql),prepare:(sql)=>db.query(sql),pragma:()=>undefined,close:()=>db.close()};}
  const db=new mod.DatabaseSync(filename);return {exec:(sql)=>db.exec(sql),prepare:(sql)=>db.prepare(sql),pragma:()=>undefined,close:()=>db.close()};
}

const agentSelect=`SELECT id,task,COALESCE(goal,task) as goal,COALESCE(role,'general') as role,parent_agent_id as parentAgentId,COALESCE(root_agent_id,id) as rootAgentId,status,created_at as createdAt,updated_at as updatedAt,result,error FROM agents`;
const taskSelect=`SELECT id,plan_id as planId,title,kind,status,dependencies,retry_count as retryCount,max_retries as maxRetries,failure_policy as failurePolicy,blocked_reason as blockedReason,result,position,owner_agent_id as ownerAgentId,lease_id as leaseId,lease_expires_at as leaseExpiresAt,created_at as createdAt,updated_at as updatedAt FROM plan_tasks`;

export class StateStore{
  readonly db:Database;
  constructor(filename=process.env.LOOM_DB??".loom/loom.db"){
    if(filename!==":memory:"){const dir=filename.replace(/[\\/][^\\/]+$/,"");if(dir)mkdirSync(dir,{recursive:true});}
    this.db=loadDatabase(filename);this.db.pragma("journal_mode = WAL");this.migrate();
  }

  private migrate(){
    this.db.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);`);
    this.applyMigration(1,`CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, task TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, result TEXT, error TEXT); CREATE TABLE IF NOT EXISTS traces (id INTEGER PRIMARY KEY AUTOINCREMENT, agent_id TEXT NOT NULL, type TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS checkpoints (agent_id TEXT PRIMARY KEY, step INTEGER NOT NULL, messages TEXT NOT NULL, status TEXT NOT NULL, result TEXT);`);
    this.applyMigration(2,`CREATE TABLE IF NOT EXISTS working_memory (agent_id TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(agent_id,key)); CREATE TABLE IF NOT EXISTS tool_execution_ledger (tool_call_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, tool_name TEXT NOT NULL, input TEXT NOT NULL, status TEXT NOT NULL, result TEXT, error TEXT, updated_at TEXT NOT NULL);`);
    this.applyMigration(3,`CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, goal TEXT NOT NULL, status TEXT NOT NULL, phase TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS plan_tasks (id TEXT PRIMARY KEY, plan_id TEXT NOT NULL, title TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, dependencies TEXT NOT NULL, retry_count INTEGER NOT NULL, max_retries INTEGER NOT NULL, failure_policy TEXT, blocked_reason TEXT, result TEXT, position INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS approval_requests (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, task_id TEXT, tool_call_id TEXT, tool_name TEXT NOT NULL, input TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, decided_at TEXT); CREATE TABLE IF NOT EXISTS artifacts (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, task_id TEXT, checkpoint_id TEXT, path TEXT NOT NULL, operation TEXT NOT NULL, created_at TEXT NOT NULL);`);
    this.applyMigration(4,`CREATE TABLE IF NOT EXISTS task_checkpoints (id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, plan_id TEXT NOT NULL, task_id TEXT, phase TEXT NOT NULL, step INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL);`);
    this.applyMigration(5,`
      ALTER TABLE agents ADD COLUMN parent_agent_id TEXT; ALTER TABLE agents ADD COLUMN root_agent_id TEXT; ALTER TABLE agents ADD COLUMN role TEXT NOT NULL DEFAULT 'general'; ALTER TABLE agents ADD COLUMN goal TEXT;
      UPDATE agents SET root_agent_id=id WHERE root_agent_id IS NULL; UPDATE agents SET goal=task WHERE goal IS NULL;
      ALTER TABLE plan_tasks ADD COLUMN owner_agent_id TEXT; ALTER TABLE plan_tasks ADD COLUMN lease_id TEXT; ALTER TABLE plan_tasks ADD COLUMN lease_expires_at TEXT;
      ALTER TABLE artifacts ADD COLUMN type TEXT NOT NULL DEFAULT 'file'; ALTER TABLE artifacts ADD COLUMN visibility TEXT NOT NULL DEFAULT 'parent-visible';
      ALTER TABLE approval_requests ADD COLUMN role TEXT; ALTER TABLE approval_requests ADD COLUMN reason TEXT; ALTER TABLE approval_requests ADD COLUMN arguments_summary TEXT;
      ALTER TABLE traces ADD COLUMN root_agent_id TEXT; ALTER TABLE traces ADD COLUMN parent_agent_id TEXT; ALTER TABLE traces ADD COLUMN task_id TEXT; ALTER TABLE traces ADD COLUMN delegation_id TEXT; ALTER TABLE traces ADD COLUMN message_id TEXT; ALTER TABLE traces ADD COLUMN tool_call_id TEXT; ALTER TABLE traces ADD COLUMN checkpoint_id TEXT;
      UPDATE traces SET root_agent_id=agent_id WHERE root_agent_id IS NULL;
      CREATE TABLE delegations (id TEXT PRIMARY KEY,parent_agent_id TEXT NOT NULL,child_agent_id TEXT NOT NULL,task_id TEXT,goal TEXT NOT NULL,status TEXT NOT NULL,failure_policy TEXT,created_at TEXT NOT NULL,started_at TEXT,completed_at TEXT,result_summary TEXT,failure_reason TEXT);
      CREATE UNIQUE INDEX delegations_active_task ON delegations(parent_agent_id,task_id) WHERE status IN ('created','assigned','running','waiting');
      CREATE TABLE agent_messages (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,from_agent_id TEXT NOT NULL,to_agent_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,visibility TEXT NOT NULL,created_at TEXT NOT NULL,delivered_at TEXT,acknowledged_at TEXT);
      CREATE TABLE agent_results (id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,delegation_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL,summary TEXT NOT NULL,artifacts TEXT,task_updates TEXT,findings TEXT,failure_policy TEXT,error TEXT,created_at TEXT NOT NULL);
      CREATE TABLE task_leases (id TEXT PRIMARY KEY,task_id TEXT NOT NULL,agent_id TEXT NOT NULL,status TEXT NOT NULL,acquired_at TEXT NOT NULL,expires_at TEXT NOT NULL,released_at TEXT);
      CREATE UNIQUE INDEX task_leases_active_task ON task_leases(task_id) WHERE status='active';
      CREATE TABLE scoped_memory (agent_id TEXT NOT NULL,root_agent_id TEXT NOT NULL,scope TEXT NOT NULL,visibility TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(agent_id,scope,key));
      CREATE TABLE coordination_decisions (id TEXT PRIMARY KEY,root_agent_id TEXT NOT NULL,agent_id TEXT NOT NULL,task_id TEXT,delegation_id TEXT,decision TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
      CREATE INDEX agents_root_idx ON agents(root_agent_id); CREATE INDEX messages_recipient_idx ON agent_messages(to_agent_id,acknowledged_at); CREATE INDEX traces_root_idx ON traces(root_agent_id,id);
    `);
  }
  private applyMigration(version:number,sql:string){if(!this.db.prepare("SELECT version FROM schema_migrations WHERE version=?").get(version)){this.transaction(()=>{this.db.exec(sql);this.db.prepare("INSERT INTO schema_migrations VALUES (?,?)").run(version,new Date().toISOString());});}}
  transaction<T>(operation:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const result=operation();this.db.exec("COMMIT");return result;}catch(error){this.db.exec("ROLLBACK");throw error;}}
  close():void{this.db.close?.();}
  getSchemaVersion():number{return (this.db.prepare("SELECT MAX(version) as version FROM schema_migrations").get() as {version:number}).version;}

  createAgent(task:string,id:string=randomUUID()):Agent{return this.createAgentRecord({id,goal:task,task,role:"general"});}
  createAgentRecord(input:{id?:string;goal:string;task?:string;role?:AgentRole;parentAgentId?:string;rootAgentId?:string}):Agent{
    const id=input.id??`agent_${randomUUID()}`;const parent=input.parentAgentId?this.getAgent(input.parentAgentId):undefined;
    if(input.parentAgentId&&!parent)throw new Error(`parent agent not found: ${input.parentAgentId}`);
    const rootAgentId=input.rootAgentId??parent?.rootAgentId??id;const now=new Date().toISOString();
    this.db.prepare("INSERT INTO agents (id,task,status,created_at,updated_at,result,error,parent_agent_id,root_agent_id,role,goal) VALUES (?,?,?,?,?,NULL,NULL,?,?,?,?)").run(id,input.task??input.goal,"created",now,now,input.parentAgentId??null,rootAgentId,input.role??"general",input.goal);
    return this.getAgent(id)!;
  }
  getAgent(id:string):Agent|undefined{return this.db.prepare(`${agentSelect} WHERE id=?`).get(id) as Agent|undefined;}
  listAgents(rootAgentId?:string):Agent[]{return (rootAgentId?this.db.prepare(`${agentSelect} WHERE root_agent_id=? ORDER BY created_at`).all(rootAgentId):this.db.prepare(`${agentSelect} ORDER BY created_at DESC`).all()) as Agent[];}
  listChildren(parentAgentId:string):Agent[]{return this.db.prepare(`${agentSelect} WHERE parent_agent_id=? ORDER BY created_at`).all(parentAgentId) as Agent[];}
  updateAgent(id:string,status:AgentStatus,result?:string,error?:string):void{this.db.prepare("UPDATE agents SET status=?,result=COALESCE(?,result),error=COALESCE(?,error),updated_at=? WHERE id=?").run(status,result??null,error??null,new Date().toISOString(),id);}

  saveCheckpoint(c:Checkpoint):void{this.db.prepare("INSERT OR REPLACE INTO checkpoints (agent_id,step,messages,status,result) VALUES (?,?,?,?,?)").run(c.agentId,c.step,JSON.stringify(c.messages),c.status,c.result??null);}
  getCheckpoint(id:string):Checkpoint|undefined{const row=this.db.prepare("SELECT agent_id as agentId,step,messages,status,result FROM checkpoints WHERE agent_id=?").get(id) as (Omit<Checkpoint,"messages">&{messages:string})|undefined;return row?{...row,messages:JSON.parse(row.messages) as Message[]}:undefined;}

  addTrace(agentId:string,type:string,data:Record<string,unknown>,correlation:TraceCorrelation={}):void{
    const agent=this.getAgent(agentId);const merged={rootAgentId:agent?.rootAgentId,parentAgentId:agent?.parentAgentId,...correlation};
    this.db.prepare("INSERT INTO traces(agent_id,type,data,created_at,root_agent_id,parent_agent_id,task_id,delegation_id,message_id,tool_call_id,checkpoint_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(agentId,type,JSON.stringify(data),new Date().toISOString(),merged.rootAgentId??null,merged.parentAgentId??null,merged.taskId??null,merged.delegationId??null,merged.messageId??null,merged.toolCallId??null,merged.checkpointId??null);
  }
  getTrace(id:string,rootTimeline=false):TraceEvent[]{
    const select="SELECT id,agent_id as agentId,type,data,created_at as createdAt,root_agent_id as rootAgentId,parent_agent_id as parentAgentId,task_id as taskId,delegation_id as delegationId,message_id as messageId,tool_call_id as toolCallId,checkpoint_id as checkpointId FROM traces";
    const rows=(rootTimeline?this.db.prepare(`${select} WHERE root_agent_id=? ORDER BY id`).all(id):this.db.prepare(`${select} WHERE agent_id=? ORDER BY id`).all(id)) as Array<TraceEvent&{data:string}>;return rows.map(row=>({...row,data:JSON.parse(row.data)}));
  }

  listMemory(agentId:string):MemoryEntry[]{return this.db.prepare("SELECT agent_id as agentId,key,value,updated_at as updatedAt FROM working_memory WHERE agent_id=? ORDER BY key").all(agentId) as MemoryEntry[];}
  putMemory(agentId:string,key:string,value:string):void{this.db.prepare("INSERT OR REPLACE INTO working_memory VALUES (?,?,?,?)").run(agentId,key,value,new Date().toISOString());}
  deleteMemory(agentId:string,key:string):void{this.db.prepare("DELETE FROM working_memory WHERE agent_id=? AND key=?").run(agentId,key);}
  clearMemory(agentId:string):void{this.db.prepare("DELETE FROM working_memory WHERE agent_id=?").run(agentId);}
  putScopedMemory(input:{agentId:string;scope:MemoryScope;key:string;value:string;visibility?:Visibility;allowProjectWrite?:boolean}):void{const agent=this.getAgent(input.agentId);if(!agent)throw new Error(`agent not found: ${input.agentId}`);if(input.scope==="project"&&!input.allowProjectWrite)throw new Error("project memory write requires explicit policy");this.db.prepare("INSERT OR REPLACE INTO scoped_memory VALUES (?,?,?,?,?,?,?)").run(agent.id,agent.rootAgentId,input.scope,input.visibility??"private",input.key,input.value,new Date().toISOString());}
  listVisibleMemory(agentId:string):MemoryEntry[]{const agent=this.getAgent(agentId);if(!agent)throw new Error(`agent not found: ${agentId}`);const rows=this.db.prepare("SELECT agent_id as agentId,root_agent_id as rootAgentId,scope,visibility,key,value,updated_at as updatedAt FROM scoped_memory WHERE agent_id=? OR (root_agent_id=? AND scope='root-task' AND visibility='team-visible') OR (scope='project' AND visibility!='private') ORDER BY updated_at").all(agent.id,agent.rootAgentId) as MemoryEntry[];return [...this.listMemory(agent.id),...rows];}

  getToolExecution(id:string){return this.db.prepare("SELECT tool_call_id as toolCallId,agent_id as agentId,tool_name as toolName,input,status,result,error,updated_at as updatedAt FROM tool_execution_ledger WHERE tool_call_id=?").get(id) as {toolCallId:string;agentId:string;toolName:string;input:string;status:string;result?:string;error?:string;updatedAt:string}|undefined;}
  recordToolExecution(id:string,agentId:string,name:string,input:Record<string,unknown>,status:string,result?:string,error?:string):void{this.db.prepare("INSERT OR REPLACE INTO tool_execution_ledger VALUES (?,?,?,?,?,?,?,?)").run(id,agentId,name,JSON.stringify(input),status,result??null,error??null,new Date().toISOString());}

  createPlan(agentId:string,goal:string,id=`plan_${randomUUID()}`):Plan{const now=new Date().toISOString();this.db.prepare("INSERT INTO plans VALUES (?,?,?,?,?,?,?)").run(id,agentId,goal,"running","plan",now,now);return this.getPlan(id)!;}
  getPlan(id:string):Plan|undefined{return this.db.prepare("SELECT id,agent_id as agentId,goal,status,phase,created_at as createdAt,updated_at as updatedAt FROM plans WHERE id=?").get(id) as Plan|undefined;}
  getPlanForAgent(agentId:string):Plan|undefined{return this.db.prepare("SELECT id,agent_id as agentId,goal,status,phase,created_at as createdAt,updated_at as updatedAt FROM plans WHERE agent_id=? ORDER BY created_at DESC LIMIT 1").get(agentId) as Plan|undefined;}
  updatePlan(id:string,status:AgentStatus,phase:ExecutionPhase):void{this.db.prepare("UPDATE plans SET status=?,phase=?,updated_at=? WHERE id=?").run(status,phase,new Date().toISOString(),id);}
  addPlanTask(input:{id?:string;planId:string;title:string;kind:string;dependencies?:string[];maxRetries?:number;position:number}):PlanTask{const id=input.id??`task_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO plan_tasks (id,plan_id,title,kind,status,dependencies,retry_count,max_retries,failure_policy,blocked_reason,result,position,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,NULL,NULL,NULL,?,?,?)").run(id,input.planId,input.title,input.kind,"pending",JSON.stringify(input.dependencies??[]),0,input.maxRetries??1,input.position,now,now);return this.getPlanTask(id)!;}
  getPlanTask(id:string):PlanTask|undefined{const row=this.db.prepare(`${taskSelect} WHERE id=?`).get(id) as (Omit<PlanTask,"dependencies">&{dependencies:string})|undefined;return row?{...row,dependencies:JSON.parse(row.dependencies)}:undefined;}
  listPlanTasks(planId:string):PlanTask[]{return (this.db.prepare(`${taskSelect} WHERE plan_id=? ORDER BY position`).all(planId) as Array<Omit<PlanTask,"dependencies">&{dependencies:string}>).map(row=>({...row,dependencies:JSON.parse(row.dependencies)}));}
  updatePlanTask(id:string,status:TaskStatus,data:{result?:string;failurePolicy?:FailurePolicy;blockedReason?:string;incrementRetry?:boolean;ownerAgentId?:string|null}={}):void{this.db.prepare("UPDATE plan_tasks SET status=?,result=COALESCE(?,result),failure_policy=COALESCE(?,failure_policy),blocked_reason=COALESCE(?,blocked_reason),retry_count=retry_count+?,owner_agent_id=CASE WHEN ? IS NULL THEN owner_agent_id ELSE ? END,updated_at=? WHERE id=?").run(status,data.result??null,data.failurePolicy??null,data.blockedReason??null,data.incrementRetry?1:0,data.ownerAgentId===undefined?null:"set",data.ownerAgentId??null,new Date().toISOString(),id);}

  createApproval(input:{agentId:string;taskId?:string;toolCallId?:string;toolName:string;input:Record<string,unknown>;reason?:string}):ApprovalRequest{const existing=input.toolCallId?this.getApprovalByToolCall(input.toolCallId):undefined;if(existing)return existing;const agent=this.getAgent(input.agentId);const id=`approval_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO approval_requests (id,agent_id,task_id,tool_call_id,tool_name,input,status,created_at,decided_at,role,reason,arguments_summary) VALUES (?,?,?,?,?,?,?,?,NULL,?,?,?)").run(id,input.agentId,input.taskId??null,input.toolCallId??null,input.toolName,JSON.stringify(input.input),"pending",now,agent?.role??null,input.reason??`permission policy requires approval for ${input.toolName}`,JSON.stringify(input.input).slice(0,500));return this.getApproval(id)!;}
  getApproval(id:string):ApprovalRequest|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,tool_call_id as toolCallId,tool_name as toolName,input,status,created_at as createdAt,decided_at as decidedAt,role,reason,arguments_summary as argumentsSummary FROM approval_requests WHERE id=?").get(id) as (Omit<ApprovalRequest,"input">&{input:string})|undefined;return row?{...row,input:JSON.parse(row.input)}:undefined;}
  getApprovalByToolCall(id:string):ApprovalRequest|undefined{const row=this.db.prepare("SELECT id FROM approval_requests WHERE tool_call_id=? ORDER BY created_at DESC LIMIT 1").get(id) as {id:string}|undefined;return row?this.getApproval(row.id):undefined;}
  resolveApproval(id:string,status:"approved"|"denied"):void{this.db.prepare("UPDATE approval_requests SET status=?,decided_at=? WHERE id=?").run(status,new Date().toISOString(),id);}
  listApprovals(agentId?:string):ApprovalRequest[]{const rows=(agentId?this.db.prepare("SELECT id FROM approval_requests WHERE agent_id=? ORDER BY created_at DESC").all(agentId):this.db.prepare("SELECT id FROM approval_requests ORDER BY created_at DESC").all()) as Array<{id:string}>;return rows.map(row=>this.getApproval(row.id)!);}
  listApprovalsForRoot(rootAgentId:string):ApprovalRequest[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listApprovals(agent.id));}

  addArtifact(input:{agentId:string;taskId?:string;checkpointId?:string;path:string;type?:string;operation:ArtifactOperation;visibility?:Visibility}):Artifact{const existing=this.db.prepare("SELECT id FROM artifacts WHERE agent_id=? AND COALESCE(task_id,'')=COALESCE(?,'') AND COALESCE(checkpoint_id,'')=COALESCE(?,'') AND path=? AND operation=? LIMIT 1").get(input.agentId,input.taskId??null,input.checkpointId??null,input.path,input.operation) as {id:string}|undefined;if(existing)return this.getArtifact(existing.id)!;const id=`artifact_${randomUUID()}`;this.db.prepare("INSERT INTO artifacts (id,agent_id,task_id,checkpoint_id,path,operation,created_at,type,visibility) VALUES (?,?,?,?,?,?,?,?,?)").run(id,input.agentId,input.taskId??null,input.checkpointId??null,input.path,input.operation,new Date().toISOString(),input.type??"file",input.visibility??"parent-visible");return this.getArtifact(id)!;}
  getArtifact(id:string):Artifact|undefined{return this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE id=?").get(id) as Artifact|undefined;}
  listArtifacts(agentId:string,taskId?:string):Artifact[]{return (taskId?this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE agent_id=? AND task_id=? ORDER BY created_at").all(agentId,taskId):this.db.prepare("SELECT id,agent_id as agentId,task_id as taskId,checkpoint_id as checkpointId,path,type,operation,visibility,created_at as createdAt FROM artifacts WHERE agent_id=? ORDER BY created_at").all(agentId)) as Artifact[];}
  listArtifactsForRoot(rootAgentId:string):Artifact[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listArtifacts(agent.id).filter(artifact=>artifact.agentId===rootAgentId||artifact.visibility!=="private"));}

  createTaskCheckpoint(input:{agentId:string;planId:string;taskId?:string;phase:ExecutionPhase;step:number;snapshot:Record<string,unknown>}):TaskCheckpoint{const id=`cp_${randomUUID()}`;this.db.prepare("INSERT INTO task_checkpoints VALUES (?,?,?,?,?,?,?,?)").run(id,input.agentId,input.planId,input.taskId??null,input.phase,input.step,JSON.stringify(input.snapshot),new Date().toISOString());this.addTrace(input.agentId,"checkpoint.created",{checkpointId:id,planId:input.planId,taskId:input.taskId,phase:input.phase,step:input.step},{taskId:input.taskId,checkpointId:id});return this.getTaskCheckpoint(id)!;}
  getTaskCheckpoint(id:string):TaskCheckpoint|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,plan_id as planId,task_id as taskId,phase,step,snapshot,created_at as createdAt FROM task_checkpoints WHERE id=?").get(id) as (Omit<TaskCheckpoint,"snapshot">&{snapshot:string})|undefined;return row?{...row,snapshot:JSON.parse(row.snapshot)}:undefined;}
  latestTaskCheckpoint(agentId:string):TaskCheckpoint|undefined{const row=this.db.prepare("SELECT id FROM task_checkpoints WHERE agent_id=? ORDER BY created_at DESC LIMIT 1").get(agentId) as {id:string}|undefined;return row?this.getTaskCheckpoint(row.id):undefined;}

  createChildAndDelegation(input:{parentAgentId:string;taskId?:string;goal:string;role:AgentRole;childAgentId?:string;delegationId?:string}):{agent:Agent;delegation:Delegation}{return this.transaction(()=>{const parent=this.getAgent(input.parentAgentId);if(!parent)throw new Error(`parent agent not found: ${input.parentAgentId}`);if(input.taskId){const active=this.getActiveDelegationForTask(input.parentAgentId,input.taskId);if(active)return {agent:this.getAgent(active.childAgentId)!,delegation:active};}const agent=this.createAgentRecord({id:input.childAgentId,goal:input.goal,task:input.goal,role:input.role,parentAgentId:parent.id,rootAgentId:parent.rootAgentId});const id=input.delegationId??`delegation_${randomUUID()}`;this.db.prepare("INSERT INTO delegations (id,parent_agent_id,child_agent_id,task_id,goal,status,created_at) VALUES (?,?,?,?,?,'assigned',?)").run(id,parent.id,agent.id,input.taskId??null,input.goal,new Date().toISOString());return {agent,delegation:this.getDelegation(id)!};});}
  getDelegation(id:string):Delegation|undefined{return this.db.prepare("SELECT id,parent_agent_id as parentAgentId,child_agent_id as childAgentId,task_id as taskId,goal,status,failure_policy as failurePolicy,created_at as createdAt,started_at as startedAt,completed_at as completedAt,result_summary as resultSummary,failure_reason as failureReason FROM delegations WHERE id=?").get(id) as Delegation|undefined;}
  getDelegationForTask(parentAgentId:string,taskId:string):Delegation|undefined{const row=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? AND task_id=? ORDER BY created_at DESC LIMIT 1").get(parentAgentId,taskId) as {id:string}|undefined;return row?this.getDelegation(row.id):undefined;}
  getActiveDelegationForTask(parentAgentId:string,taskId:string):Delegation|undefined{const row=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? AND task_id=? AND status IN ('created','assigned','running','waiting') ORDER BY created_at DESC LIMIT 1").get(parentAgentId,taskId) as {id:string}|undefined;return row?this.getDelegation(row.id):undefined;}
  listDelegations(agentId:string):Delegation[]{const rows=this.db.prepare("SELECT id FROM delegations WHERE parent_agent_id=? OR child_agent_id=? ORDER BY created_at").all(agentId,agentId) as Array<{id:string}>;return rows.map(row=>this.getDelegation(row.id)!);}
  listDelegationsForRoot(rootAgentId:string):Delegation[]{return this.listAgents(rootAgentId).flatMap(agent=>this.listDelegations(agent.id)).filter((item,index,all)=>all.findIndex(other=>other.id===item.id)===index);}
  updateDelegation(id:string,status:DelegationStatus,data:{failurePolicy?:FailurePolicy|"cancelled";resultSummary?:string;failureReason?:string}={}):void{const now=new Date().toISOString();this.db.prepare("UPDATE delegations SET status=?,failure_policy=COALESCE(?,failure_policy),result_summary=COALESCE(?,result_summary),failure_reason=COALESCE(?,failure_reason),started_at=CASE WHEN ?='running' AND started_at IS NULL THEN ? ELSE started_at END,completed_at=CASE WHEN ? IN ('completed','failed','cancelled') THEN ? ELSE completed_at END WHERE id=?").run(status,data.failurePolicy??null,data.resultSummary??null,data.failureReason??null,status,now,status,now,id);}

  sendAgentMessage(input:{fromAgentId:string;toAgentId:string;type:AgentMessageType;payload:unknown;visibility?:Visibility;id?:string}):AgentMessage{const from=this.getAgent(input.fromAgentId);const to=this.getAgent(input.toAgentId);if(!from||!to)throw new Error("message sender or recipient not found");if(from.rootAgentId!==to.rootAgentId)throw new Error("cross-root messages are not supported");const id=input.id??`message_${randomUUID()}`;this.db.prepare("INSERT INTO agent_messages VALUES (?,?,?,?,?,?,?,?,NULL,NULL)").run(id,from.rootAgentId,from.id,to.id,input.type,JSON.stringify(input.payload),input.visibility??"parent-visible",new Date().toISOString());return this.getAgentMessage(id)!;}
  getAgentMessage(id:string):AgentMessage|undefined{const row=this.db.prepare("SELECT id,root_agent_id as rootAgentId,from_agent_id as fromAgentId,to_agent_id as toAgentId,type,payload,visibility,created_at as createdAt,delivered_at as deliveredAt,acknowledged_at as acknowledgedAt FROM agent_messages WHERE id=?").get(id) as (Omit<AgentMessage,"payload">&{payload:string})|undefined;return row?{...row,payload:JSON.parse(row.payload)}:undefined;}
  receiveAgentMessages(agentId:string):AgentMessage[]{const now=new Date().toISOString();this.db.prepare("UPDATE agent_messages SET delivered_at=COALESCE(delivered_at,?) WHERE to_agent_id=?").run(now,agentId);return this.listAgentMessages(agentId).filter(message=>!message.acknowledgedAt);}
  acknowledgeAgentMessage(id:string):void{const now=new Date().toISOString();this.db.prepare("UPDATE agent_messages SET delivered_at=COALESCE(delivered_at,?),acknowledged_at=COALESCE(acknowledged_at,?) WHERE id=?").run(now,now,id);}
  listAgentMessages(agentId:string):AgentMessage[]{const rows=this.db.prepare("SELECT id FROM agent_messages WHERE from_agent_id=? OR to_agent_id=? ORDER BY created_at").all(agentId,agentId) as Array<{id:string}>;return rows.map(row=>this.getAgentMessage(row.id)!);}

  completeDelegationWithResult(delegationId:string,result:AgentResult):AgentResult{return this.transaction(()=>{const existing=this.getAgentResultByDelegation(delegationId);if(existing)return existing;const delegation=this.getDelegation(delegationId);if(!delegation)throw new Error(`delegation not found: ${delegationId}`);const id=`result_${randomUUID()}`;const now=new Date().toISOString();this.db.prepare("INSERT INTO agent_results VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(id,delegation.childAgentId,delegation.id,result.status,result.summary,JSON.stringify(result.artifacts??[]),JSON.stringify(result.taskUpdates??[]),JSON.stringify(result.findings??{}),result.failurePolicy??null,result.error??null,now);this.updateDelegation(delegation.id,result.status==="completed"?"completed":"failed",{failurePolicy:result.failurePolicy,resultSummary:result.summary,failureReason:result.error});this.updateAgent(delegation.childAgentId,result.status==="completed"?"completed":"failed",result.status==="completed"?result.summary:undefined,result.error);const message=this.sendAgentMessage({id:`message_result_${delegation.id}`,fromAgentId:delegation.childAgentId,toAgentId:delegation.parentAgentId,type:result.status==="completed"?"response":"error",payload:{delegationId:delegation.id,resultId:id,status:result.status,summary:result.summary},visibility:"parent-visible"});this.addTrace(delegation.childAgentId,"message.sent",{toAgentId:delegation.parentAgentId,type:message.type},{taskId:delegation.taskId,delegationId:delegation.id,messageId:message.id});return this.getAgentResult(id)!;});}
  getAgentResult(id:string):AgentResult|undefined{const row=this.db.prepare("SELECT id,agent_id as agentId,delegation_id as delegationId,status,summary,artifacts,task_updates as taskUpdates,findings,failure_policy as failurePolicy,error,created_at as createdAt FROM agent_results WHERE id=?").get(id) as (AgentResult&{artifacts:string;taskUpdates:string;findings:string})|undefined;return row?{...row,artifacts:JSON.parse(row.artifacts),taskUpdates:JSON.parse(row.taskUpdates),findings:JSON.parse(row.findings)}:undefined;}
  getAgentResultByDelegation(delegationId:string):AgentResult|undefined{const row=this.db.prepare("SELECT id FROM agent_results WHERE delegation_id=?").get(delegationId) as {id:string}|undefined;return row?this.getAgentResult(row.id):undefined;}

  acquireTaskLease(taskId:string,agentId:string,ttlMs=30000,leaseId=`lease_${randomUUID()}`):TaskLease|undefined{return this.transaction(()=>{const task=this.getPlanTask(taskId);if(!task)throw new Error(`task not found: ${taskId}`);const now=new Date();if(task.leaseId&&task.leaseExpiresAt&&new Date(task.leaseExpiresAt)>now)return task.ownerAgentId===agentId?this.getTaskLease(task.leaseId):undefined;if(task.leaseId)this.db.prepare("UPDATE task_leases SET status='expired',released_at=? WHERE id=? AND status='active'").run(now.toISOString(),task.leaseId);const expiresAt=new Date(now.getTime()+ttlMs).toISOString();this.db.prepare("INSERT INTO task_leases VALUES (?,?,?,'active',?,?,NULL)").run(leaseId,taskId,agentId,now.toISOString(),expiresAt);this.db.prepare("UPDATE plan_tasks SET owner_agent_id=?,lease_id=?,lease_expires_at=?,updated_at=? WHERE id=?").run(agentId,leaseId,expiresAt,now.toISOString(),taskId);return this.getTaskLease(leaseId);});}
  getTaskLease(id:string):TaskLease|undefined{return this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases WHERE id=?").get(id) as TaskLease|undefined;}
  releaseTaskLease(taskId:string,status:"released"|"cancelled"="released"):void{const task=this.getPlanTask(taskId);if(!task?.leaseId)return;this.transaction(()=>{this.db.prepare("UPDATE task_leases SET status=?,released_at=? WHERE id=? AND status='active'").run(status,new Date().toISOString(),task.leaseId!);this.db.prepare("UPDATE plan_tasks SET lease_id=NULL,lease_expires_at=NULL,updated_at=? WHERE id=?").run(new Date().toISOString(),taskId);});}
  listTaskLeases(agentId?:string):TaskLease[]{return (agentId?this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases WHERE agent_id=? ORDER BY acquired_at").all(agentId):this.db.prepare("SELECT id,task_id as taskId,agent_id as agentId,status,acquired_at as acquiredAt,expires_at as expiresAt,released_at as releasedAt FROM task_leases ORDER BY acquired_at").all()) as TaskLease[];}
  recordCoordinationDecision(input:{rootAgentId:string;agentId:string;taskId?:string;delegationId?:string;decision:string;reason:string}):void{this.db.prepare("INSERT INTO coordination_decisions VALUES (?,?,?,?,?,?,?,?)").run(`decision_${randomUUID()}`,input.rootAgentId,input.agentId,input.taskId??null,input.delegationId??null,input.decision,input.reason,new Date().toISOString());}
}
