import {describe,expect,it} from "vitest";
import {mkdtempSync,rmSync} from "node:fs";import {join} from "node:path";import {tmpdir} from "node:os";
import {EventGateway} from "./hardened-event-gateway";
import {EnhancedBotSessionManager} from "../sessions/enhanced-session-manager";
import {StateStore} from "@loom/state";
import type {BotEvent,} from "../types";
import {createAdaptiveBotRunner} from "../adaptive-runner";
import type {Provider} from "@loom/core";
const event=(id:string,text:string):BotEvent=>({id,transport:"test",type:"message",botId:"bot",channelId:"dm",userId:"u",text,timestamp:new Date().toISOString()});
describe("adaptive bot gateway",()=>it("reuses the session root for follow-ups",async()=>{const state=new StateStore(":memory:");let roots:string[]=[];const provider:Provider={name:"bot-test",complete:async()=>({content:"verified"})};const adaptive=createAdaptiveBotRunner(state,provider);const runner={run:async(input:{goal:string;session:any;rootAgentId?:string})=>{const result=await adaptive.run(input);roots.push(result.rootAgentId);return result;}};const gateway=new EventGateway(state,new EnhancedBotSessionManager(state,{authorization:{allowedUsers:["u"],allowedChannels:[],admins:[]}}),runner);const first=await gateway.processEvent(event("1","fix tests"));const second=await gateway.processEvent(event("2","what is current status?"));expect(first.status).toBe("handled");expect(second.status).toBe("handled");expect(first.response).toContain("evidence");expect(roots).toHaveLength(2);expect(roots[1]).toBe(roots[0]);state.close();}));

it("survives runtime restart with the same adaptive session root",async()=>{const dir=mkdtempSync(join(tmpdir(),"loom-bot-adaptive-"));const db=join(dir,"bot.db");const provider:Provider={name:"bot-restart",complete:async()=>({content:"verified"})};const firstState=new StateStore(db);const firstRunner=createAdaptiveBotRunner(firstState,provider);const firstGateway=new EventGateway(firstState,new EnhancedBotSessionManager(firstState,{authorization:{allowedUsers:["u"],allowedChannels:[],admins:[]}}),firstRunner);const first=await firstGateway.processEvent(event("restart-1","fix tests"));const rootId=(first.session as any).rootAgentId;expect(first.status).toBe("handled");expect(rootId).toBeTruthy();firstState.close();const secondState=new StateStore(db);const secondRunner=createAdaptiveBotRunner(secondState,provider);const secondGateway=new EventGateway(secondState,new EnhancedBotSessionManager(secondState,{authorization:{allowedUsers:["u"],allowedChannels:[],admins:[]}}),secondRunner);const second=await secondGateway.processEvent(event("restart-2","what changed?"));expect(second.status).toBe("handled");expect((second.session as any).rootAgentId).toBe(rootId);expect(second.response).toContain("evidence");secondState.close();rmSync(dir,{recursive:true,force:true});});
