import {describe,expect,it} from "vitest";
import {mkdtempSync,writeFileSync,existsSync,readFileSync,mkdirSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {pathToFileURL} from "node:url";
import {spawn,spawnSync} from "node:child_process";
import {createServer} from "node:net";
import {StateStore} from "@loom/state";
import {RemoteControllerService,hashWorkerToken} from "./index.js";

const waitFor=(check:()=>boolean,timeout=30000)=>new Promise<void>((resolvePromise,reject)=>{const started=Date.now();const tick=()=>{try{if(check())return resolvePromise();}catch{}if(Date.now()-started>timeout)return reject(new Error("process E2E timeout"));setTimeout(tick,25);};tick();});
const freePort=()=>new Promise<number>(resolvePromise=>{const server=createServer();server.listen(0,"127.0.0.1",()=>{const port=(server.address() as any).port;server.close(()=>resolvePromise(port));});});
const kill=async(child:any)=>{if(!child||child.exitCode!==null)return;await new Promise<void>(resolvePromise=>{const done=()=>resolvePromise();child.once("exit",done);// Platform-aware force kill: taskkill on Windows, SIGKILL elsewhere.
    if(process.platform==="win32")spawnSync("taskkill",["/T","/F","/PID",String(child.pid)]);else child.kill("SIGKILL");setTimeout(done,3000);});};
function spawnController(dir:string,port:number,db:string,token:string,leaseMs=30000){const dist=pathToFileURL(resolve(process.cwd(),"packages/remote/dist/index.js")).href,stateDist=pathToFileURL(resolve(process.cwd(),"packages/state/dist/index.js")).href,script=join(dir,`controller-${port}.mjs`);writeFileSync(script,`import {StateStore} from ${JSON.stringify(stateDist)};import {RemoteControllerService,hashWorkerToken} from ${JSON.stringify(dist)};import {createInterface} from "node:readline";const state=new StateStore(${JSON.stringify(db)});const service=new RemoteControllerService(state,{host:"127.0.0.1",port:${port},leaseMs:${leaseMs},credentials:[{workerId:"worker-a",tokenHash:hashWorkerToken(${JSON.stringify(token)})},{workerId:"worker-b",tokenHash:hashWorkerToken(${JSON.stringify(token)})},{workerId:"child-worker",tokenHash:hashWorkerToken(${JSON.stringify(token)})}]});await service.start();console.log("CONTROLLER_READY");const rl=createInterface({input:process.stdin});const shutdown=async()=>{await service.stop();state.close();process.exit(0)};rl.on("line",async line=>{try{if(String(line).trim()==="shutdown"){await shutdown();return;}const command=JSON.parse(line);if(command.op==="dispatch")await service.fabric.dispatchTool(command.input);if(command.op==="recover")await service.fabric.recoverExpiredAssignments();if(command.op==="expire")state.expireRemoteLeases();if(command.op==="status")console.log("STATE "+JSON.stringify(state.getRemoteAssignment(command.assignmentId))+" LEASE "+JSON.stringify(state.getRemoteLease(state.getRemoteAssignment(command.assignmentId)?.leaseId??"")));if(command.op==="cancel")await service.fabric.cancel(command.assignmentId);if(command.op==="stale")console.log("STALE "+JSON.stringify(state.acceptRemoteEvent(command.input)));console.log("COMMAND_DONE");}catch(error){console.log("COMMAND_ERROR "+String(error));}});if(process.platform!=="win32")process.on("SIGTERM",()=>void shutdown());await new Promise(()=>{});`);const child=spawn(process.execPath,[script],{env:{...process.env},stdio:["pipe","pipe","pipe"]});const output={text:"",errors:""};child.stdout.on("data",(chunk:Buffer)=>{output.text+=chunk.toString();});child.stderr.on("data",(chunk:Buffer)=>{output.errors+=chunk.toString();});return {child,output};}
function spawnWorker(dir:string,port:number,token:string,workerId:string,stateFile:string,workspace:string,custom=false){const dist=pathToFileURL(resolve(process.cwd(),"packages/remote/dist/index.js")).href,stateDist=pathToFileURL(resolve(process.cwd(),"packages/state/dist/index.js")).href,toolsDist=pathToFileURL(resolve(process.cwd(),"packages/tools/dist/index.js")).href,script=join(dir,`${workerId}-${Date.now()}.mjs`);const executor=custom?`const {StateStore}=await import(${JSON.stringify(stateDist)});const {ToolRegistry,ToolExecutor}=await import(${JSON.stringify(toolsDist)});const localState=new StateStore(${JSON.stringify(stateFile)});const registry=new ToolRegistry();registry.register({name:"delay_append",description:"test",execute:async input=>{await new Promise(r=>setTimeout(r,1000));(await import("node:fs")).appendFileSync(${JSON.stringify(join(workspace,"effect.log"))},"one"+String.fromCharCode(10));return "appended";}});const executor=new ToolExecutor(registry,{permissions:{delay_append:"allow"},ledger:localState});`:`const executor=undefined;`;
writeFileSync(script,`import {RemoteWorkerRuntime} from ${JSON.stringify(dist)};${executor}const runtime=new RemoteWorkerRuntime({url:${JSON.stringify(`ws://127.0.0.1:${port}/v1/workers/connect`)},token:process.env.LOOM_WORKER_TOKEN,workerId:${JSON.stringify(workerId)},workspaceRoot:${JSON.stringify(workspace)},stateFile:${JSON.stringify(stateFile)},allowedTools:${custom?"[\"delay_append\"]":"[\"write_file\"]"},allowShell:true,leaseRenewMs:${custom?100:10000},executor});await runtime.start();console.log("WORKER_READY "+runtime.workerInstanceId);const shutdown=()=>runtime.stop().then(()=>process.exit(0));process.stdin.on("data",(c)=>{if(String(c).includes("shutdown"))void shutdown();});if(process.platform!=="win32")process.on("SIGTERM",()=>void shutdown());await new Promise(()=>{});`);const child=spawn(process.execPath,[script],{env:{...process.env,LOOM_WORKER_TOKEN:token},stdio:["pipe","pipe","pipe"]});const output={text:"",errors:""};child.stdout.on("data",(chunk:Buffer)=>{output.text+=chunk.toString();});child.stderr.on("data",(chunk:Buffer)=>{output.errors+=chunk.toString();});return {child,output};}
const waitExpired=async(controller:any,assignmentId:string)=>{for(let i=0;i<100;i++){await issue(controller.child,controller.output,{op:"expire"});controller.child.stdin.write(JSON.stringify({op:"status",assignmentId})+"\n");try{await waitFor(()=>controller.output.text.includes("\"status\":\"expired\""),100);return;}catch{}await new Promise(resolvePromise=>setTimeout(resolvePromise,25));}throw new Error("lease did not expire");};
const waitAssignmentStatus=async(controller:any,assignmentId:string,status:string,timeout=10000)=>{const deadline=Date.now()+timeout;while(Date.now()<deadline){controller.child.stdin.write(JSON.stringify({op:"status",assignmentId})+"\n");await new Promise(resolvePromise=>setTimeout(resolvePromise,50));const latest=controller.output.text.split("\n").filter((line:string)=>line.startsWith("STATE ")).at(-1);if(latest?.includes(`"status":"${status}"`))return;}throw new Error(`assignment did not reach ${status}`);};
const command=(child:any,input:any)=>{child.stdin.write(JSON.stringify({op:"dispatch",input})+"\n");};
const issue=async(child:any,output:any,commandValue:any)=>{const before=(output.text.match(/COMMAND_DONE/g)||[]).length;child.stdin.write(JSON.stringify(commandValue)+"\n");await waitFor(()=>((output.text.match(/COMMAND_DONE/g)||[]).length>before));};

describe("remote multi-process recovery",()=>{
 it("recovers a logical assignment after controller process restart",async()=>{const dir=mkdtempSync(join(tmpdir(),"loom-controller-restart-")),workspace=join(dir,"workspace");mkdirSync(workspace);const db=join(dir,"controller.db"),token="restart-secret",port=await freePort();let controller:any,worker:any;try{controller=spawnController(dir,port,db,token);await waitFor(()=>controller.output.text.includes("CONTROLLER_READY"));worker=spawnWorker(dir,port,token,"child-worker",join(dir,"worker.db"),workspace);await waitFor(()=>worker.output.text.includes("WORKER_READY"));command(controller.child,{jobId:"restart-job",toolName:"write_file",toolInput:{path:"effect.log",content:"one"},allowedTools:["write_file"]});await waitFor(()=>existsSync(join(workspace,"effect.log")));await kill(controller.child);controller=spawnController(dir,port,db,token);await waitFor(()=>controller.output.text.includes("CONTROLLER_READY"));await waitAssignmentStatus(controller,"restart-job","completed",12000);expect(controller.output.text).toContain("\"id\":\"restart-job\"");expect(readFileSync(join(workspace,"effect.log"),"utf8")).toBe("one");}finally{await kill(worker?.child);await kill(controller?.child);rmSync(dir,{recursive:true,force:true});}},90000);
 it("preserves worker identity across process restart without repeating a completed tool",async()=>{const dir=mkdtempSync(join(tmpdir(),"loom-worker-restart-")),workspace=join(dir,"workspace");mkdirSync(workspace);const state=new StateStore(":memory:"),service=new RemoteControllerService(state,{host:"127.0.0.1",port:0,credentials:[{workerId:"child-worker",tokenHash:hashWorkerToken("secret")}]}),portHolder={port:0};let worker:any;try{await service.start();portHolder.port=service.address()!.port;const stateFile=join(dir,"worker.db");worker=spawnWorker(dir,portHolder.port,"secret","child-worker",stateFile,workspace);await waitFor(()=>worker.output.text.includes("WORKER_READY"));const first=worker.output.text.match(/WORKER_READY ([^\n]+)/)?.[1];const firstWorker=state.getWorker("child-worker"),firstConnection=(state.db.prepare("SELECT connection_id as connectionId FROM connections WHERE worker_id=? AND status='online'").get("child-worker") as any)?.connectionId;await service.fabric.dispatchTool({jobId:"worker-restart-job",toolName:"write_file",toolInput:{path:"effect.log",content:"one"},allowedTools:["write_file"]});await waitFor(()=>state.getRemoteAssignment("worker-restart-job")?.status==="completed");await kill(worker.child);worker=spawnWorker(dir,portHolder.port,"secret","child-worker",stateFile,workspace);await waitFor(()=>worker.output.text.includes("WORKER_READY"));const second=worker.output.text.match(/WORKER_READY ([^\n]+)/)?.[1],secondWorker=state.getWorker("child-worker"),secondConnection=(state.db.prepare("SELECT connection_id as connectionId FROM connections WHERE worker_id=? AND status='online'").get("child-worker") as any)?.connectionId;expect(second).not.toBe(first);expect(secondWorker?.workerId).toBe(firstWorker?.workerId);expect(secondWorker?.metadata.epoch).toBeGreaterThan(firstWorker?.metadata.epoch);expect(secondConnection).not.toBe(firstConnection);expect(readFileSync(join(workspace,"effect.log"),"utf8")).toBe("one");}finally{await kill(worker?.child);await service.stop();state.close();rmSync(dir,{recursive:true,force:true});}},90000);
 it("takes over an expired lease in Worker B and rejects stale Worker A generation",async()=>{const dir=mkdtempSync(join(tmpdir(),"loom-takeover-")),workspace=join(dir,"workspace");mkdirSync(workspace);const db=join(dir,"controller.db"),token="takeover-secret",port=await freePort();let controller:any,a:any,b:any;try{controller=spawnController(dir,port,db,token,500);await waitFor(()=>controller.output.text.includes("CONTROLLER_READY"));a=spawnWorker(dir,port,token,"worker-a",join(dir,"a.db"),workspace,true);b=spawnWorker(dir,port,token,"worker-b",join(dir,"b.db"),workspace,true);await waitFor(()=>a.output.text.includes("WORKER_READY")&&b.output.text.includes("WORKER_READY"));await issue(controller.child,controller.output,{op:"dispatch",input:{jobId:"takeover-job",toolName:"delay_append",toolInput:{},allowedTools:["delay_append"],requiredCapabilities:[]}});controller.child.stdin.write(JSON.stringify({op:"status",assignmentId:"takeover-job"})+"\n");await waitFor(()=>controller.output.text.includes("STATE")&&controller.output.text.includes("\"status\":\"running\""));const firstLine=controller.output.text.split("\n").filter((line:string)=>line.startsWith("STATE ")).at(-1)!;const first=JSON.parse(firstLine.slice(6).split(" LEASE ")[1]);await kill(a.child);await new Promise(resolvePromise=>setTimeout(resolvePromise,250));await waitExpired(controller,"takeover-job");await issue(controller.child,controller.output,{op:"recover"});controller.child.stdin.write(JSON.stringify({op:"status",assignmentId:"takeover-job"})+"\n");await waitFor(()=>controller.output.text.includes("\"workerId\":\"worker-b\""));const secondLine=controller.output.text.split("\n").filter((line:string)=>line.startsWith("STATE ")).at(-1)!;const second=JSON.parse(secondLine.slice(6).split(" LEASE ")[1]);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);await waitAssignmentStatus(controller,"takeover-job","completed");await issue(controller.child,controller.output,{op:"stale",input:{assignmentId:"takeover-job",workerId:"worker-a",leaseId:first.id,fencingToken:first.fencingToken,sequence:999,messageId:"stale-worker-a-result",payload:{executionId:"takeover-job",status:"completed"}}});expect(controller.output.text).toContain("STALE {\"accepted\":false");a=spawnWorker(dir,port,token,"worker-a",join(dir,"a.db"),workspace,true);await waitFor(()=>a.output.text.includes("WORKER_READY"));await new Promise(resolve=>setTimeout(resolve,500));await waitAssignmentStatus(controller,"takeover-job","completed");expect(readFileSync(join(workspace,"effect.log"),"utf8")).toBe("one\n");}finally{await kill(a?.child);await kill(b?.child);await kill(controller?.child);rmSync(dir,{recursive:true,force:true});}},120000);
});
