import {describe,expect,it} from "vitest";
import {DeterministicRouter,LeaseManager,SequenceJournal,WorkerRegistry,RemoteFabricController,assertFencingToken,normalizeCapabilities,ProtocolValidationError,createEnvelope,validateEnvelope} from "../src/index.js";
import {StateStore} from "@loom-agent/state";
const identity=(workerId:string)=>({workerId,instanceId:`${workerId}-1`,trust:"trusted" as const});
describe("remote protocol",()=>{
 it("normalizes capability names deterministically",()=>expect(normalizeCapabilities([{name:" Zeta ",roles:["Coder"],tools:["Shell"]},{name:"zeta",version:"2"},{name:"alpha"}])).toEqual({names:["alpha","zeta"],roles:["coder"],tools:["shell"],versions:{zeta:"2"}}));
 it("routes with capability and stable tie break",()=>{const r=new WorkerRegistry();r.register(identity("b"),["gpu"],{running:0,capacity:1});r.register(identity("a"),["gpu"],{running:0,capacity:1});expect(new DeterministicRouter(r).route({jobId:"j",payload:0,requiredCapabilities:["GPU"]})?.workerId).toBe("a");});
 it("fences stale leases",()=>{const l=new LeaseManager();const a=l.acquire("j","a",100,0);expect(l.validate("j",a,1)).toBe(true);expect(()=>l.renew("j",{...a,fencingToken:0},10,1)).toThrow();l.release("j",a,2);const b=l.acquire("j","b",100,3);expect(b.fencingToken).toBeGreaterThan(a.fencingToken);expect(()=>assertFencingToken(a.fencingToken,b)).toThrow();});
 it("replays unacknowledged sequence in order",()=>{const j=new SequenceJournal(identity("a"));j.append("dispatch",{x:1});j.append("result",{x:2});j.append("ack",{x:3});j.acknowledge(1);expect(j.replay().map(x=>x.sequence)).toEqual([2,3]);});
it("validates durable event sequences per authenticated connection",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.assignRemote({id:"sequence-assignment",workerId:"a",payload:{}});const lease=state.acquireRemoteLease("sequence-assignment","a",1000),base={assignmentId:"sequence-assignment",workerId:"a",leaseId:lease.id,fencingToken:lease.fencingToken,payload:{executionId:"sequence-assignment"}};expect(state.acceptRemoteEvent({...base,connectionId:"c1",sequence:5,messageId:"m5"})).toMatchObject({accepted:true,ack:5});expect(state.acceptRemoteEvent({...base,connectionId:"c1",sequence:7,messageId:"m7"})).toMatchObject({accepted:false,reason:"sequence_gap",ack:5});expect(state.acceptRemoteEvent({...base,connectionId:"c1",sequence:6,messageId:"m6"})).toMatchObject({accepted:true,ack:6});expect(state.acceptRemoteEvent({...base,connectionId:"c1",sequence:6,messageId:"m6"})).toMatchObject({accepted:true,duplicate:true,ack:6});expect(state.acceptRemoteEvent({...base,connectionId:"c1",sequence:7,messageId:"m6"})).toMatchObject({accepted:false,reason:"message_id_conflict"});expect(state.acceptRemoteEvent({...base,connectionId:"c2",sequence:20,messageId:"m20"})).toMatchObject({accepted:true,ack:20});state.close();});
it("rejects invalid or unauthorized durable lease acquisition",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.registerWorker({workerId:"b"});expect(()=>state.acquireRemoteLease("missing","a",1000)).toThrow("not found");state.assignRemote({id:"lease-validation",workerId:"a",payload:{}});expect(()=>state.acquireRemoteLease("lease-validation","a",0)).toThrow("positive integer");expect(()=>state.acquireRemoteLease("lease-validation","b",1000)).toThrow("owner mismatch");const first=state.acquireRemoteLease("lease-validation","a",1);expect(()=>state.acquireRemoteLease("lease-validation","a",1000)).toThrow("not available");state.expireRemoteLeases(Date.now()+5);const second=state.acquireRemoteLease("lease-validation","b",1000);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);state.close();});

 it("journals a fresh fenced dispatch when an expired assignment is recovered",async()=>{const state=new StateStore(":memory:");const sent:any[]=[];const controller=new RemoteFabricController(state,undefined,undefined,{},1);const worker=identity("recovery-worker");controller.attach(worker,{send:async (envelope:any)=>{sent.push(envelope);},close:()=>{},onMessage:()=>{},onDisconnect:()=>{}},[]);const first=await controller.dispatch({jobId:"recovery-job",payload:{}});state.ackProtocolMessagesForWorker(worker.workerId,"outbound",1);state.expireRemoteLeases(Date.now()+10);const recovered=await controller.recoverExpiredAssignments();expect(recovered).toHaveLength(1);expect(recovered[0].lease.fencingToken).toBeGreaterThan(first.lease.fencingToken);const pending=state.listUnackedProtocolMessagesForWorker(worker.workerId,"outbound");expect(pending).toHaveLength(1);const envelope=JSON.parse(pending[0].envelope);expect(envelope.id).toBe(`dispatch_recovery-job_${recovered[0].lease.fencingToken}`);expect(envelope.lease.fencingToken).toBe(recovered[0].lease.fencingToken);state.close();});

});

it("rejects unsupported and malformed protocol envelopes without mutation",()=>{const sender=identity("w");expect(()=>validateEnvelope({protocol:"999",type:"heartbeat",id:"m",sequence:1,sentAt:new Date().toISOString(),sender,payload:{}})).toThrowError(ProtocolValidationError);expect(()=>validateEnvelope({protocol:"0.8",type:"heartbeat",id:"",sequence:1,sentAt:new Date().toISOString(),sender,payload:{}})).toThrow();});
it("durably fences lease takeover and dedupes protocol messages",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.assignRemote({id:"assignment-a",workerId:"a",payload:{}});const first=state.acquireRemoteLease("assignment-a","a",1);state.expireRemoteLeases(Date.now()+10);const second=state.acquireRemoteLease("assignment-a","a",1000);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);expect(state.recordProtocolMessage({messageId:"m1",connectionId:"c",direction:"outbound",sequence:1,envelope:{x:1}})).toBe(true);expect(state.recordProtocolMessage({messageId:"m1",connectionId:"c",direction:"outbound",sequence:1,envelope:{x:1}})).toBe(false);expect(state.listUnackedProtocolMessages("c")).toHaveLength(1);state.ackProtocolMessage("c","outbound",1);expect(state.listUnackedProtocolMessages("c")).toHaveLength(0);state.close();});

it("uses one durable assignment and replays unacked dispatch after reconnect",async()=>{const state=new StateStore(":memory:");const sent:any[]=[];let onMessage=(x:any)=>{};let onDisconnect=()=>{};const transport={send:(e:any)=>{sent.push(e);},close:()=>{},onMessage:(h:any)=>{onMessage=h;},onDisconnect:(h:any)=>{onDisconnect=h;}};const {RemoteFabricController}=await import("../src/index.js");const controller=new RemoteFabricController(state);const worker=identity("worker-1");const attached=controller.attach(worker,transport,["shell"],{running:0,capacity:2});const result=await controller.dispatch({jobId:"job-1",payload:{command:"echo"},requiredCapabilities:["shell"]});expect(result.assignmentId).toBe("job-1");expect(state.listWorkers()).toHaveLength(1);await controller.dispatch({jobId:"job-1",payload:{command:"echo"},requiredCapabilities:["shell"]});expect(state.getRemoteAssignment("job-1").id).toBe("job-1");expect(sent).toHaveLength(1);expect(state.listUnackedProtocolMessages(attached.connectionId)).toHaveLength(1);await controller.reconnect(worker.workerId,0);expect(sent).toHaveLength(2);state.close();});

it("rejects a stale worker event after durable lease takeover",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.registerWorker({workerId:"b"});state.assignRemote({id:"assignment-fence",workerId:"a",payload:{}});const first=state.acquireRemoteLease("assignment-fence","a",1);state.expireRemoteLeases(Date.now()+5);const second=state.acquireRemoteLease("assignment-fence","b",1000);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);expect(state.getRemoteAssignment("assignment-fence")?.workerId).toBe("b");expect(state.acceptRemoteEvent({assignmentId:"assignment-fence",workerId:"a",leaseId:first.id,fencingToken:first.fencingToken,sequence:1,messageId:"late",payload:{executionId:"assignment-fence"}}).accepted).toBe(false);expect(state.acceptRemoteEvent({assignmentId:"assignment-fence",workerId:"b",leaseId:second.id,fencingToken:second.fencingToken,sequence:1,messageId:"current",payload:{executionId:"assignment-fence"}}).accepted).toBe(true);state.close();});

it("rejects sequence gaps and enforces trust-aware routing",()=>{const r=new WorkerRegistry();r.register({...identity("untrusted"),trust:"untrusted"},["shell"]);r.register({...identity("trusted"),trust:"trusted"},["shell"]);expect(new DeterministicRouter(r).route({jobId:"secure",payload:{},requiredCapabilities:["shell"]},{trust:"trusted"})?.workerId).toBe("trusted");const j=new SequenceJournal(identity("w"));const inbound=createEnvelope({type:"heartbeat",id:"in-1",sender:identity("w"),sequence:1,payload:{}});expect(j.receive(inbound)).toBe("accepted");expect(j.receive(inbound)).toBe("duplicate");expect(()=>j.receive({...inbound,id:"in-3",sequence:3})).toThrow(/gap/);});
it("persists a failed dispatch send and replays it after reconnect",async()=>{const state=new StateStore(":memory:");const {RemoteFabricController}=await import("../src/index.js");const controller=new RemoteFabricController(state);const worker=identity("outbox-worker"),failed={send:async()=>{throw new Error("socket closed");},close:()=>{},onMessage:()=>{},onDisconnect:()=>{}};controller.attach(worker,failed,["shell"]);await expect(controller.dispatch({jobId:"outbox-job",payload:{command:"echo"},requiredCapabilities:["shell"]})).rejects.toThrow("socket closed");expect(state.getRemoteAssignment("outbox-job")?.status).toBe("dispatched");const sent:any[]=[];controller.attach({...worker,instanceId:"outbox-worker-2"},{send:async (envelope:any)=>{sent.push(envelope);},close:()=>{},onMessage:()=>{},onDisconnect:()=>{}},["shell"]);await controller.reconnect(worker.workerId,0);expect(sent.map(envelope=>envelope.id)).toContain("dispatch_outbox-job_1");await controller.dispatch({jobId:"outbox-job-2",payload:{command:"echo"},requiredCapabilities:["shell"]});expect(sent.filter(envelope=>envelope.type==="dispatch").map(envelope=>envelope.sequence)).toEqual([1,2]);state.close();});
it("durably queues cancellation while a worker is disconnected",async()=>{const state=new StateStore(":memory:");const {RemoteFabricController}=await import("../src/index.js");const controller=new RemoteFabricController(state);const worker=identity("cancel-offline");let disconnect=()=>{};controller.attach(worker,{send:async()=>{},close:()=>{},onMessage:()=>{},onDisconnect:handler=>{disconnect=handler;}},[]);await controller.dispatch({jobId:"cancel-offline-job",payload:{}});disconnect();await controller.cancel("cancel-offline-job");expect(state.getRemoteAssignment("cancel-offline-job")?.status).toBe("cancelled");const replayed:any[]=[];controller.attach({...worker,instanceId:"cancel-offline-2"},{send:async (envelope:any)=>{replayed.push(envelope);},close:()=>{},onMessage:()=>{},onDisconnect:()=>{}},[]);await controller.reconnect(worker.workerId,0);expect(replayed.map(envelope=>envelope.type)).toContain("cancel");state.close();});
it("persists worker connection epochs across controller restart",async()=>{const state=new StateStore(":memory:"),transport={send:async()=>{},close:()=>{},onMessage:()=>{},onDisconnect:()=>{}},{RemoteFabricController}=await import("../src/index.js"),worker=identity("epoch-worker");const first=new RemoteFabricController(state).attach(worker,transport,[],{running:0,capacity:1},"connection-1");const second=new RemoteFabricController(state).attach({...worker,instanceId:"epoch-worker-2"},transport,[],{running:0,capacity:1},"connection-2");expect(second.epoch).toBe(first.epoch+1);state.close();});
