import {describe,expect,it} from "vitest";
import {DeterministicRouter,LeaseManager,SequenceJournal,WorkerRegistry,assertFencingToken,normalizeCapabilities,ProtocolValidationError,createEnvelope,validateEnvelope} from "../src/index.js";
import {StateStore} from "@loom/state";
const identity=(workerId:string)=>({workerId,instanceId:`${workerId}-1`,trust:"trusted" as const});
describe("remote protocol",()=>{
 it("normalizes capability names deterministically",()=>expect(normalizeCapabilities([{name:" Zeta ",roles:["Coder"],tools:["Shell"]},{name:"zeta",version:"2"},{name:"alpha"}])).toEqual({names:["alpha","zeta"],roles:["coder"],tools:["shell"],versions:{zeta:"2"}}));
 it("routes with capability and stable tie break",()=>{const r=new WorkerRegistry();r.register(identity("b"),["gpu"],{running:0,capacity:1});r.register(identity("a"),["gpu"],{running:0,capacity:1});expect(new DeterministicRouter(r).route({jobId:"j",payload:0,requiredCapabilities:["GPU"]})?.workerId).toBe("a");});
 it("fences stale leases",()=>{const l=new LeaseManager();const a=l.acquire("j","a",100,0);expect(l.validate("j",a,1)).toBe(true);expect(()=>l.renew("j",{...a,fencingToken:0},10,1)).toThrow();l.release("j",a,2);const b=l.acquire("j","b",100,3);expect(b.fencingToken).toBeGreaterThan(a.fencingToken);expect(()=>assertFencingToken(a.fencingToken,b)).toThrow();});
 it("replays unacknowledged sequence in order",()=>{const j=new SequenceJournal(identity("a"));j.append("dispatch",{x:1});j.append("result",{x:2});j.append("ack",{x:3});j.acknowledge(1);expect(j.replay().map(x=>x.sequence)).toEqual([2,3]);});
});

it("rejects unsupported and malformed protocol envelopes without mutation",()=>{const sender=identity("w");expect(()=>validateEnvelope({protocol:"999",type:"heartbeat",id:"m",sequence:1,sentAt:new Date().toISOString(),sender,payload:{}})).toThrowError(ProtocolValidationError);expect(()=>validateEnvelope({protocol:"0.8",type:"heartbeat",id:"",sequence:1,sentAt:new Date().toISOString(),sender,payload:{}})).toThrow();});
it("durably fences lease takeover and dedupes protocol messages",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.assignRemote({id:"assignment-a",workerId:"a",payload:{}});const first=state.acquireRemoteLease("assignment-a","a",1);state.expireRemoteLeases(Date.now()+10);const second=state.acquireRemoteLease("assignment-a","a",1000);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);expect(state.recordProtocolMessage({messageId:"m1",connectionId:"c",direction:"outbound",sequence:1,envelope:{x:1}})).toBe(true);expect(state.recordProtocolMessage({messageId:"m1",connectionId:"c",direction:"outbound",sequence:1,envelope:{x:1}})).toBe(false);expect(state.listUnackedProtocolMessages("c")).toHaveLength(1);state.ackProtocolMessage("c","outbound",1);expect(state.listUnackedProtocolMessages("c")).toHaveLength(0);state.close();});

it("uses one durable assignment and replays unacked dispatch after reconnect",async()=>{const state=new StateStore(":memory:");const sent:any[]=[];let onMessage=(x:any)=>{};let onDisconnect=()=>{};const transport={send:(e:any)=>{sent.push(e);},close:()=>{},onMessage:(h:any)=>{onMessage=h;},onDisconnect:(h:any)=>{onDisconnect=h;}};const {RemoteFabricController}=await import("../src/index.js");const controller=new RemoteFabricController(state);const worker=identity("worker-1");const attached=controller.attach(worker,transport,["shell"],{running:0,capacity:2});const result=await controller.dispatch({jobId:"job-1",payload:{command:"echo"},requiredCapabilities:["shell"]});expect(result.assignmentId).toBe("job-1");expect(state.listWorkers()).toHaveLength(1);await controller.dispatch({jobId:"job-1",payload:{command:"echo"},requiredCapabilities:["shell"]});expect(state.getRemoteAssignment("job-1").id).toBe("job-1");expect(sent).toHaveLength(1);expect(state.listUnackedProtocolMessages(attached.connectionId)).toHaveLength(1);await controller.reconnect(worker.workerId,0);expect(sent).toHaveLength(2);state.close();});

it("rejects a stale worker event after durable lease takeover",()=>{const state=new StateStore(":memory:");state.registerWorker({workerId:"a"});state.registerWorker({workerId:"b"});state.assignRemote({id:"assignment-fence",workerId:"a",payload:{}});const first=state.acquireRemoteLease("assignment-fence","a",1);state.expireRemoteLeases(Date.now()+5);state.assignRemote({id:"assignment-fence-b",workerId:"b",payload:{}});const second=state.acquireRemoteLease("assignment-fence-b","b",1000);expect(second.fencingToken).toBeGreaterThan(first.fencingToken);expect(state.acceptRemoteEvent({assignmentId:"assignment-fence",workerId:"a",leaseId:first.id,fencingToken:first.fencingToken,sequence:1,messageId:"late",payload:{executionId:"assignment-fence"}}).accepted).toBe(false);state.close();});
