import {describe,expect,it} from "vitest";
import {mkdtempSync,readFileSync,existsSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {StateStore} from "@loom-agent/state";
import {RemoteFabricController,hashWorkerToken,WebSocketControllerTransport,WebSocketWorkerTransport,RemoteWorkerRuntime} from "./index.js";
import {ToolExecutor,ToolRegistry} from "@loom-agent/tools";

const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const waitFor=async(check:()=>boolean,timeout=3000)=>{const deadline=Date.now()+timeout;while(Date.now()<deadline){if(check())return;await wait(10);}throw new Error("websocket test timeout");};

describe("websocket reverse transport",()=>{
 it("authenticates an outbound worker and carries assignment ACKs",async()=>{const state=new StateStore(":memory:"),server=new WebSocketControllerTransport({host:"127.0.0.1",port:0,credentials:[{workerId:"w1",tokenHash:hashWorkerToken("secret")} ]});const controller=new RemoteFabricController(state);let connectionId="";server.onWorker(worker=>{connectionId=worker.connectionId;controller.attach(worker.identity,worker.transport,worker.capabilities,worker.load,worker.connectionId);});await server.start();const address=server.address()!;const runtime=new RemoteWorkerRuntime({url:`ws://127.0.0.1:${address.port}/v1/workers/connect`,workerId:"w1",token:"secret",capabilities:["shell"]});await runtime.start();const result=await controller.dispatch({jobId:"network-job",payload:{x:1},requiredCapabilities:["shell"]});expect(result.assignmentId).toBe("network-job");await waitFor(()=>state.listUnackedProtocolMessages(connectionId).length===0);expect(state.listUnackedProtocolMessages(connectionId)).toHaveLength(0);await runtime.stop();await wait(25);await server.stop();state.close();});
 it("rejects invalid credentials while keeping the endpoint healthy",async()=>{const server=new WebSocketControllerTransport({host:"127.0.0.1",port:0,authTimeoutMs:1000,credentials:[{workerId:"w1",tokenHash:hashWorkerToken("secret")} ]});await server.start();const address=server.address()!;const bad=new WebSocketWorkerTransport({url:`ws://127.0.0.1:${address.port}/v1/workers/connect`,worker:{workerId:"w1",instanceId:"bad",trust:"untrusted"},token:"wrong"});await expect(bad.connect()).rejects.toThrow();await server.stop();});
 it("executes through ToolExecutor and intersects worker policy",async()=>{const workspace=mkdtempSync(join(tmpdir(),"loom-worker-")),state=new StateStore(":memory:"),server=new WebSocketControllerTransport({host:"127.0.0.1",port:0,credentials:[{workerId:"policy-worker",tokenHash:hashWorkerToken("secret")} ]});const controller=new RemoteFabricController(state);server.onWorker(worker=>controller.attach(worker.identity,worker.transport,worker.capabilities,worker.load,worker.connectionId));await server.start();const address=server.address()!;const runtime=new RemoteWorkerRuntime({url:`ws://127.0.0.1:${address.port}/v1/workers/connect`,workerId:"policy-worker",token:"secret",workspaceRoot:workspace,stateFile:join(workspace,"worker.db"),allowedTools:["read_file"]});await runtime.start();await controller.dispatchTool({jobId:"policy-job",toolName:"write_file",toolInput:{path:"blocked.txt",content:"no"},allowedTools:["read_file","write_file"]});await waitFor(()=>state.getRemoteAssignment("policy-job")?.status==="failed");expect(state.getRemoteAssignment("policy-job")).toMatchObject({status:"failed"});expect(existsSync(join(workspace,"blocked.txt"))).toBe(false);await runtime.stop();await wait(25);await server.stop();state.close();});
 it("cancels an executing remote assignment over the real socket",async()=>{const state=new StateStore(":memory:"),server=new WebSocketControllerTransport({host:"127.0.0.1",port:0,credentials:[{workerId:"cancel-worker",tokenHash:hashWorkerToken("secret")} ]});const controller=new RemoteFabricController(state);server.onWorker(worker=>controller.attach(worker.identity,worker.transport,worker.capabilities,worker.load,worker.connectionId));await server.start();const address=server.address()!;const registry=new ToolRegistry();registry.register({name:"wait",description:"controlled wait",execute:async()=>{await wait(200);return "done";}} as any);const runtime=new RemoteWorkerRuntime({url:`ws://127.0.0.1:${address.port}/v1/workers/connect`,workerId:"cancel-worker",token:"secret",executor:new ToolExecutor(registry,{permissions:{wait:"allow"}}),stateFile:join(tmpdir(),`cancel-${Date.now()}.db`)});await runtime.start();await controller.dispatchTool({jobId:"cancel-job",toolName:"wait",toolInput:{},allowedTools:["wait"]});await wait(30);await controller.cancel("cancel-job");await wait(50);expect(state.getRemoteAssignment("cancel-job")).toMatchObject({status:"cancelled"});await runtime.stop();await wait(25);await server.stop();state.close();});

 it("keeps a stable loom worker address while reconnecting to a new route epoch",async()=>{const state=new StateStore(":memory:"),server=new WebSocketControllerTransport({host:"127.0.0.1",port:0,credentials:[{workerId:"route-worker",tokenHash:hashWorkerToken("secret")}]});const controller=new RemoteFabricController(state);server.onWorker(worker=>{const binding=controller.attach(worker.identity,worker.transport,worker.capabilities,worker.load,worker.connectionId);return {epoch:binding.epoch};});await server.start();const port=server.address()!.port;let runtime=new RemoteWorkerRuntime({url:`ws://127.0.0.1:${port}/v1/workers/connect`,workerId:"route-worker",token:"secret"});await runtime.start();const first=controller.resolveRoute("loom://worker/route-worker")!;const firstEpoch=runtime.transport.epoch;expect(first).toMatchObject({connectionId:runtime.transport.connectionId,state:"available"});expect(controller.workerAddress("route-worker")).toBe("loom://worker/route-worker");await runtime.stop();await waitFor(()=>controller.resolveRoute("loom://worker/route-worker")?.state==="unavailable");runtime=new RemoteWorkerRuntime({url:`ws://127.0.0.1:${port}/v1/workers/connect`,workerId:"route-worker",token:"secret"});await runtime.start();const second=controller.resolveRoute("loom://worker/route-worker")!;expect(second.connectionId).not.toBe(first.connectionId);expect(runtime.transport.epoch).toBeGreaterThan(firstEpoch);expect(controller.workerAddress("route-worker")).toBe("loom://worker/route-worker");await runtime.stop();await waitFor(()=>controller.resolveRoute("loom://worker/route-worker")?.state==="unavailable");await server.stop();state.close();});

 it("rejects non-local worker exposure without TLS",async()=>{const server=new WebSocketControllerTransport({host:"0.0.0.0",port:0});await expect(server.start()).rejects.toThrow(/requires TLS/);});

});
