import type {Message,Provider} from "@loom/core";
import {StateStore} from "@loom/state";
import {ToolExecutor,ToolPolicy,ToolRegistry} from "@loom/tools";
import {ContextCompiler} from "@loom/context";
import {SkillRuntime} from "@loom/skills";
export type AgentLoopOptions={context?:ContextCompiler;skills?:SkillRuntime;selectedSkills?:string[];maxChars?:number;system?:string;toolPolicy?:ToolPolicy;files?:string[]};
export class AgentLoop {
 constructor(private readonly state:StateStore,private readonly provider:Provider,private readonly tools?:ToolRegistry,private readonly options:AgentLoopOptions={}){}
 async run(task:string,id?:string){const agent=id?this.state.getAgent(id):this.state.createAgent(task);if(!agent)throw new Error(`agent not found: ${id}`);const checkpoint=this.state.getCheckpoint(agent.id);const previous=checkpoint?.messages??[{role:"user",content:agent.task}];this.state.updateAgent(agent.id,"running");this.state.addTrace(agent.id,"agent.started",{task:agent.task,resumed:Boolean(checkpoint)});try{const selected=this.options.selectedSkills?.length&&this.options.skills?await this.options.skills.load(this.options.selectedSkills):[];for(const skill of selected??[])this.state.addTrace(agent.id,"skill.loaded",{name:skill.name});const compiled=await (this.options.context??new ContextCompiler()).compile({system:this.options.system,goal:agent.task,runtimeState:`agent=${agent.id}; status=running`,messages:previous,memory:this.state.listMemory(agent.id),skills:(selected??[]).map(s=>`${s.name}: ${s.instructions}`),files:this.options.files,tools:this.tools?.definitions(),maxChars:this.options.maxChars,trace:(type,data)=>this.state.addTrace(agent.id,type,data)});const messages:Message[]=[...previous,{role:"user",content:compiled.text}];this.state.saveCheckpoint({agentId:agent.id,step:checkpoint?.step??0,messages,status:"running",phase:"provider"});this.state.addTrace(agent.id,"provider.request",{provider:this.provider.name,step:checkpoint?.step??0});const response=this.provider.generate?await this.provider.generate({messages,tools:this.tools?.definitions(),system:this.options.system}):await this.provider.complete(messages);this.state.addTrace(agent.id,"provider.response",{provider:this.provider.name,requestId:response.requestId,finishReason:response.finishReason});messages.push({role:"assistant",content:response.content});if(response.toolCalls&&this.tools){const executor=new ToolExecutor(this.tools,{...this.options.toolPolicy,trace:(type,data)=>this.state.addTrace(agent.id,type,data),ledger:this.state});for(const call of response.toolCalls){const output=await executor.execute(call.name,call.input,{agentId:agent.id,toolCallId:call.id});messages.push({role:"tool",content:output});}}this.state.saveCheckpoint({agentId:agent.id,step:(checkpoint?.step??0)+1,messages,status:"completed",result:response.content,phase:"completed",providerRequestId:response.requestId});this.state.updateAgent(agent.id,"completed",response.content);this.state.addTrace(agent.id,"checkpoint.created",{step:(checkpoint?.step??0)+1});this.state.addTrace(agent.id,"agent.completed",{result:response.content});return this.state.getAgent(agent.id)!;}catch(error){const message=error instanceof Error?error.message:String(error);this.state.updateAgent(agent.id,"failed",undefined,message);this.state.addTrace(agent.id,"agent.failed",{error:message});throw error;}}
 resume(id:string){const agent=this.state.getAgent(id);if(!agent)throw new Error(`agent not found: ${id}`);this.state.updateAgent(id,"recovering");this.state.addTrace(id,"agent.recovering",{checkpoint:this.state.getCheckpoint(id)?.step??0});return this.run(agent.task,id);}
}
