#!/usr/bin/env node
import {promises as fs} from "node:fs";
import {join} from "node:path";
import type {PlanTask,Provider} from "@loom/core";
import {StateStore} from "@loom/state";
import {MockProvider,OpenAICompatibleProvider} from "@loom/providers";
import {AgentLoop} from "@loom/runtime";
import {createNativeTools,ToolExecutor} from "@loom/tools";
import {SkillRuntime} from "@loom/skills";
import {McpClient,mcpTools} from "@loom/mcp";
import {PlanEngine,Reviewer,TaskExecutor,VerifiedExecutionRuntime} from "@loom/planner";
type Config={provider?:string;model?:string;context?:{maxChars?:number};permissions?:Record<string,"allow"|"deny"|"ask">;mcpServers?:Record<string,{command:string;args?:string[];env?:Record<string,string>}>};
async function loadConfig():Promise<Config>{try{return JSON.parse(await fs.readFile(join(process.cwd(),".loom","config.json"),"utf8"));}catch{return {}}}
const cfg=await loadConfig();const argv=process.argv.slice(2);const command=argv[0];const json=argv.includes("--json");const skillIndex=argv.indexOf("--skill");const maxTasksIndex=argv.indexOf("--max-tasks");const selectedSkills=skillIndex>=0?[argv[skillIndex+1]]:[];const maxTasks=maxTasksIndex>=0?Number(argv[maxTasksIndex+1]):undefined;const skipped=new Set(["--json","--skill",skillIndex>=0?argv[skillIndex+1]:"","--max-tasks",maxTasksIndex>=0?argv[maxTasksIndex+1]:""]);const args=argv.slice(1).filter(x=>!skipped.has(x));
const state=new StateStore();const registry=createNativeTools(process.cwd());
async function loadTools(){for(const [name,server] of Object.entries(cfg.mcpServers??{})){try{const client=await new McpClient(server,(type,data)=>console.error(`[${type}]`,data)).connect();for(const tool of mcpTools(client))registry.register(tool);}catch(error){console.error(`MCP server ${name} unavailable: ${error instanceof Error?error.message:error}`);}}return registry;}
function loadProvider():Provider{const name=process.env.LOOM_PROVIDER??cfg.provider??"mock";if(name==="openai")return new OpenAICompatibleProvider(undefined,process.env.LOOM_MODEL??cfg.model);return new MockProvider();}
function output(value:unknown,human?:string){console.log(json?JSON.stringify(value,null,2):human??(typeof value==="string"?value:JSON.stringify(value,null,2)));}
function usage(){console.log("loom run <goal> | ps | inspect <id> | resume <id> | trace <id> | approve <request-id> | deny <request-id> | approvals | skills | tools | memory | config");}
function executionServices(provider:Provider,tools:Awaited<ReturnType<typeof loadTools>>){const toolExecutor=new ToolExecutor(tools,{permissions:cfg.permissions,ledger:state,approvals:state,artifacts:state});const executor:TaskExecutor={async execute(task,context){if(task.kind==="inspect")return {result:await toolExecutor.execute("shell",{command:"git status --short"},{agentId:context.agentId,taskId:task.id,toolCallId:`${task.id}:inspect`})};if(task.kind==="test"){try{return {result:await toolExecutor.execute("shell",{command:"bun x vitest run --config vitest.config.ts"},{agentId:context.agentId,taskId:task.id,toolCallId:`${task.id}:baseline-tests`})};}catch(error){if((error as any).failurePolicy)throw error;return {result:`Tests currently failing: ${error instanceof Error?error.message:error}`};}}const response=provider.generate?await provider.generate({messages:[{role:"user",content:`Goal: ${context.goal}\nCurrent task: ${task.title}`}],tools:tools.definitions()}):await provider.complete([{role:"user",content:`Goal: ${context.goal}\nCurrent task: ${task.title}`}]);return {result:response.content};}};const reviewer:Reviewer={async verify(task,context){const reviewDiff=/review/i.test(task.title);const shellCommand=reviewDiff?"git diff --check && git diff --stat":"bun x vitest run --config vitest.config.ts";try{const result=await toolExecutor.execute("shell",{command:shellCommand},{agentId:context.agentId,taskId:task.id,toolCallId:`${task.id}:verification`});return {passed:true,summary:result};}catch(error){if((error as any).failurePolicy==="needs_approval")throw error;return {passed:false,summary:error instanceof Error?error.message:String(error),failurePolicy:"retryable"};}}};return {executor,reviewer};}
async function verifiedRuntime(){const provider=loadProvider();const tools=await loadTools();const services=executionServices(provider,tools);return new VerifiedExecutionRuntime(state,services.executor,services.reviewer);}
function inspectHuman(agentId:string){const agent=state.getAgent(agentId);if(!agent)throw new Error("agent not found");const plan=state.getPlanForAgent(agentId);const tasks=plan?state.listPlanTasks(plan.id):[];const current=tasks.find(t=>["running","ready","needs_approval"].includes(t.status));const checkpoint=state.getCheckpoint(agentId);const taskCheckpoint=state.latestTaskCheckpoint(agentId);const marks:Record<string,string>={completed:"✓",running:"→",ready:"→",pending:"○",waiting:"◌",blocked:"!",failed:"×",needs_approval:"?"};const lines=[`Goal: ${agent.task}`,`Status: ${agent.status}`,plan?`Phase: ${plan.phase}`:"","Tasks",...tasks.map(t=>`${marks[t.status]??"○"} ${t.title}${t.retryCount?` (retry ${t.retryCount}/${t.maxRetries})`:""}${t.blockedReason?` — ${t.blockedReason}`:""}`),"",`Current task: ${current?.title??"none"}`,`Checkpoint: ${taskCheckpoint?.id??checkpoint?.checkpointId??(checkpoint?`step_${checkpoint.step}`:"none")}`,`Modified: ${state.listArtifacts(agentId).map(a=>a.path).join(", ")||"none"}`];return lines.join("\n");}
try{
 if(command==="run"){const goal=args.join(" ");if(!goal)throw new Error("goal is required");const agent=state.createAgent(goal);state.addTrace(agent.id,"agent.created",{goal});const plan=new PlanEngine(state).create(agent.id,goal);const result=await (await verifiedRuntime()).run(plan.id,{maxTasks});output({agent:state.getAgent(agent.id),plan:result,tasks:state.listPlanTasks(plan.id)},`Agent: ${agent.id}\nPlan: ${plan.id}\nStatus: ${result.status}`);}
 else if(command==="ps"){const agents=state.listAgents();output(agents,agents.map(a=>`${a.id}\t${a.status}\t${a.task}`).join("\n"));}
 else if(command==="inspect"){const agent=state.getAgent(args[0]);if(!agent)throw new Error("agent not found");const plan=state.getPlanForAgent(agent.id);output({...agent,checkpoint:state.getCheckpoint(agent.id),taskCheckpoint:state.latestTaskCheckpoint(agent.id),plan,tasks:plan?state.listPlanTasks(plan.id):[],artifacts:state.listArtifacts(agent.id),approvals:state.listApprovals(agent.id)},inspectHuman(agent.id));}
 else if(command==="resume"){const plan=state.getPlanForAgent(args[0]);if(plan){const result=await (await verifiedRuntime()).resume(args[0],{maxTasks});output(result,`Plan: ${result.id}\nStatus: ${result.status}`);}else{const loop=new AgentLoop(state,loadProvider(),await loadTools(),{skills:new SkillRuntime(),maxChars:cfg.context?.maxChars,toolPolicy:{permissions:cfg.permissions,approvals:state,artifacts:state}});output(await loop.resume(args[0]));}}
 else if(command==="trace"){if(!state.getAgent(args[0]))throw new Error("agent not found");output(state.getTrace(args[0]));}
 else if(command==="approve"||command==="deny"){const request=state.getApproval(args[0]);if(!request)throw new Error("approval request not found");state.resolveApproval(request.id,command==="approve"?"approved":"denied");state.addTrace(request.agentId,`approval.${command==="approve"?"approved":"denied"}`,{requestId:request.id});output(state.getApproval(request.id),`${command==="approve"?"Approved":"Denied"}: ${request.id}`);}
 else if(command==="approvals"){output(state.listApprovals(args[0]));}
 else if(command==="skills"){const all=await new SkillRuntime().discover();if(args[0]==="show"){const skill=all.find(s=>s.name===args[1]);if(!skill)throw new Error("skill not found");output(skill);}else output(all);}
 else if(command==="tools"){output((await loadTools()).definitions());}
 else if(command==="memory"){if(args[0]==="set"){state.putMemory(args[1],args[2],args.slice(3).join(" "));state.addTrace(args[1],"memory.updated",{key:args[2]});output({ok:true});}else if(args[0]==="delete"){state.deleteMemory(args[1],args[2]);output({ok:true});}else output(state.listMemory(args[0]));}
 else if(command==="config"){output({...cfg,provider:process.env.LOOM_PROVIDER??cfg.provider??"mock",model:process.env.LOOM_MODEL??cfg.model});}
 else{usage();process.exitCode=1;}
}catch(error){console.error(error instanceof Error?error.message:error);process.exitCode=1;}
