import {promises as fs} from "node:fs";
import {mkdir} from "node:fs/promises";
import {resolve,relative,sep} from "node:path";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import type {PermissionLevel,Tool,ToolDefinition} from "@loom/core";
const exec=promisify(execFile);
export type PermissionHooks={readFile?:(path:string)=>boolean;writeFile?:(path:string)=>boolean;shell?:(command:string)=>boolean};
function isInside(root:string,target:string){const workspace=resolve(root).toLowerCase();return target.toLowerCase()===workspace||target.toLowerCase().startsWith(workspace+sep);}
function safePath(root:string,value:unknown):string{if(typeof value!=="string"||!value)throw new Error("path must be a non-empty string");const workspace=resolve(root);const p=resolve(workspace,value);if(!isInside(workspace,p)||relative(workspace,p).startsWith(".."))throw new Error("path is outside workspace");return p;}
export class ApprovalRequiredError extends Error{readonly failurePolicy="needs_approval";constructor(readonly requestId:string){super(`approval required: ${requestId}`);}}
export type ToolPolicy={defaultPermission?:PermissionLevel;permissions?:Record<string,PermissionLevel>;allowAsk?:boolean;maxResultChars?:number;trace?:(type:string,data:Record<string,unknown>)=>void;ledger?:{getToolExecution(id:string):any;recordToolExecution(id:string,agentId:string,name:string,input:Record<string,unknown>,status:string,result?:string,error?:string):void};approvals?:{getApprovalByToolCall(id:string):any;createApproval(input:{agentId:string;taskId?:string;toolCallId?:string;toolName:string;input:Record<string,unknown>}):any};artifacts?:{addArtifact(input:{agentId:string;taskId?:string;checkpointId?:string;path:string;operation:"created"|"modified"|"deleted"}):any}};
export class ToolRegistry{private tools=new Map<string,Tool>();register(tool:Tool){this.tools.set(tool.name,tool);return this;}get(name:string){return this.tools.get(name);}list(){return [...this.tools.values()];}definitions():ToolDefinition[]{return this.list().map(t=>({name:t.name,description:t.description,inputSchema:t.inputSchema}));}}
export class ToolExecutor{constructor(private readonly registry:ToolRegistry,private readonly policy:ToolPolicy={}){}async execute(name:string,input:Record<string,unknown>,options:{agentId?:string;taskId?:string;checkpointId?:string;toolCallId?:string}={}):Promise<string>{const tool=this.registry.get(name);if(!tool)throw new Error(`unknown tool: ${name}`);const permission=this.policy.permissions?.[name]??this.policy.defaultPermission??"allow";this.policy.trace?.("tool.requested",{name,toolCallId:options.toolCallId});if(permission==="deny"){const error=new Error(`tool denied: ${name}`) as Error&{failurePolicy:string};error.failurePolicy="non_retryable";throw error;}if(permission==="ask"&&!this.policy.allowAsk){const existing=options.toolCallId?this.policy.approvals?.getApprovalByToolCall(options.toolCallId):undefined;if(existing?.status==="denied"){const error=new Error(`approval denied: ${existing.id}`) as Error&{failurePolicy:string};error.failurePolicy="non_retryable";throw error;}if(existing?.status!=="approved"){if(!this.policy.approvals)throw new Error(`approval required for tool: ${name}`);const request=this.policy.approvals.createApproval({agentId:options.agentId??"",taskId:options.taskId,toolCallId:options.toolCallId,toolName:name,input});this.policy.trace?.("approval.requested",{requestId:request.id,name});throw new ApprovalRequiredError(request.id);}}const id=options.toolCallId;if(id&&this.policy.ledger){const previous=this.policy.ledger.getToolExecution(id);if(previous?.status==="succeeded")return previous.result??"";if(previous?.status==="executing"||previous?.status==="unknown")throw new Error(`tool execution state is ${previous.status}: ${name}`);this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"executing");}this.policy.trace?.("tool.executing",{name,toolCallId:id});try{const result=await tool.execute(input);const limited=result.slice(0,this.policy.maxResultChars??20000);if(id&&this.policy.ledger)this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"succeeded",limited);if(name==="write_file"&&typeof input.path==="string"&&this.policy.artifacts)this.policy.artifacts.addArtifact({agentId:options.agentId??"",taskId:options.taskId,checkpointId:options.checkpointId,path:input.path,operation:"modified"});this.policy.trace?.("tool.completed",{name,toolCallId:id,resultChars:limited.length});return limited;}catch(error){const message=error instanceof Error?error.message:String(error);if(id&&this.policy.ledger)this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"failed",undefined,message);this.policy.trace?.("tool.failed",{name,toolCallId:id,error:message});throw error;}}}
export function createNativeTools(root=process.cwd(),hooks:PermissionHooks={}):ToolRegistry{const registry=new ToolRegistry();registry.register({name:"read_file",description:"Read a UTF-8 file inside the workspace",execute:async input=>{const path=safePath(root,input.path);if(hooks.readFile&&!hooks.readFile(path))throw new Error("read permission denied");const real=await fs.realpath(path);if(!isInside(root,real))throw new Error("path is outside workspace");return fs.readFile(real,"utf8");}});registry.register({name:"write_file",description:"Write a UTF-8 file inside the workspace",execute:async input=>{const path=safePath(root,input.path);if(hooks.writeFile&&!hooks.writeFile(path))throw new Error("write permission denied");if(typeof input.content!=="string")throw new Error("content must be a string");await mkdir(resolve(path,".."),{recursive:true});const parent=await fs.realpath(resolve(path,".."));if(!isInside(root,parent))throw new Error("path is outside workspace");await fs.writeFile(path,input.content,"utf8");return `wrote ${path}`;}});registry.register({name:"shell",description:"Run a command with a timeout",execute:async input=>{if(typeof input.command!=="string"||!input.command)throw new Error("command must be a non-empty string");if(hooks.shell&&!hooks.shell(input.command))throw new Error("shell permission denied");const timeout=typeof input.timeoutMs==="number"?Math.min(Math.max(input.timeoutMs,1),120000):30000;const started=Date.now();try{const result=await exec(process.platform==="win32"?"cmd":"sh",process.platform==="win32"?["/d","/s","/c",input.command]:["-c",input.command],{cwd:root,timeout,maxBuffer:1024*1024});return `[exit=0 durationMs=${Date.now()-started}]\n${result.stdout}${result.stderr}`.trim();}catch(error:any){throw new Error(`shell failed (exit ${error.code??"unknown"}, durationMs=${Date.now()-started}): ${String(error.stdout??"")} ${String(error.stderr??error.message??"")}`.trim());}}});return registry;}
