import {promises as fs} from "node:fs";
import {mkdir} from "node:fs/promises";
import {resolve,relative,isAbsolute,sep} from "node:path";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import type {PermissionLevel,Tool,ToolDefinition} from "@loom/core";
const exec=promisify(execFile);
export type PermissionHooks={readFile?:(path:string)=>boolean;writeFile?:(path:string)=>boolean;shell?:(command:string)=>boolean};
function isInside(root:string,target:string){const workspace=resolve(root).toLowerCase();return target.toLowerCase()===workspace||target.toLowerCase().startsWith(workspace+sep);}
function safePath(root:string,value:unknown):string{if(typeof value!=="string"||!value)throw new Error("path must be a non-empty string");const workspace=resolve(root);const p=resolve(workspace,value);if(!isInside(workspace,p)||relative(workspace,p).startsWith(".."))throw new Error("path is outside workspace");return p;}
export type ToolPolicy={defaultPermission?:PermissionLevel;permissions?:Record<string,PermissionLevel>;allowAsk?:boolean;maxResultChars?:number;trace?:(type:string,data:Record<string,unknown>)=>void;ledger?:{getToolExecution(id:string):any;recordToolExecution(id:string,agentId:string,name:string,input:Record<string,unknown>,status:string,result?:string,error?:string):void}};
export class ToolRegistry{private tools=new Map<string,Tool>();register(tool:Tool){this.tools.set(tool.name,tool);return this;}get(name:string){return this.tools.get(name);}list(){return [...this.tools.values()];}definitions():ToolDefinition[]{return this.list().map(t=>({name:t.name,description:t.description,inputSchema:t.inputSchema}));}}
export class ToolExecutor{constructor(private readonly registry:ToolRegistry,private readonly policy:ToolPolicy={}){}async execute(name:string,input:Record<string,unknown>,options:{agentId?:string;toolCallId?:string}={}):Promise<string>{const t=this.registry.get(name);if(!t)throw new Error(`unknown tool: ${name}`);const permission=this.policy.permissions?.[name]??this.policy.defaultPermission??"allow";this.policy.trace?.("tool.requested",{name,toolCallId:options.toolCallId});if(permission==="deny"||permission==="ask"&&!this.policy.allowAsk)throw new Error(permission==="deny"?`tool denied: ${name}`:`approval required for tool: ${name}`);const id=options.toolCallId;if(id&&this.policy.ledger){const previous=this.policy.ledger.getToolExecution(id);if(previous?.status==="succeeded")return previous.result??"";if(previous?.status==="executing"||previous?.status==="unknown")throw new Error(`tool execution state is ${previous.status}: ${name}`);this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"executing");}this.policy.trace?.("tool.executing",{name,toolCallId:id});try{const result=await t.execute(input);const limited=result.slice(0,this.policy.maxResultChars??20000);if(id&&this.policy.ledger)this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"succeeded",limited);this.policy.trace?.("tool.completed",{name,toolCallId:id,resultChars:limited.length});return limited;}catch(error){const message=error instanceof Error?error.message:String(error);if(id&&this.policy.ledger)this.policy.ledger.recordToolExecution(id,options.agentId??"",name,input,"failed",undefined,message);this.policy.trace?.("tool.failed",{name,toolCallId:id,error:message});throw error;}}}
export function createNativeTools(root=process.cwd(),hooks:PermissionHooks={}):ToolRegistry{
 const r=new ToolRegistry();
 r.register({name:"read_file",description:"Read a UTF-8 file inside the workspace",execute:async i=>{const p=safePath(root,i.path);if(hooks.readFile&&!hooks.readFile(p))throw new Error("read permission denied");const real=await fs.realpath(p);if(!isInside(root,real))throw new Error("path is outside workspace");return fs.readFile(real,"utf8");}});
 r.register({name:"write_file",description:"Write a UTF-8 file inside the workspace",execute:async i=>{const p=safePath(root,i.path);if(hooks.writeFile&&!hooks.writeFile(p))throw new Error("write permission denied");if(typeof i.content!=="string")throw new Error("content must be a string");await mkdir(resolve(p,".."),{recursive:true});const parent=await fs.realpath(resolve(p,".."));if(!isInside(root,parent))throw new Error("path is outside workspace");await fs.writeFile(p,i.content,"utf8");return `wrote ${p}`;}});
 r.register({name:"shell",description:"Run a command with a timeout",execute:async i=>{if(typeof i.command!=="string"||!i.command)throw new Error("command must be a non-empty string");if(hooks.shell&&!hooks.shell(i.command))throw new Error("shell permission denied");const timeout=typeof i.timeoutMs==="number"?Math.min(Math.max(i.timeoutMs,1),120000):30000;const started=Date.now();try{const result=await exec(process.platform==="win32"?"cmd":"sh",process.platform==="win32"?["/d","/s","/c",i.command] : ["-c",i.command],{cwd:root,timeout,maxBuffer:1024*1024});return `[exit=0 durationMs=${Date.now()-started}]\n${result.stdout}${result.stderr}`.trim();}catch(error:any){throw new Error(`shell failed (exit ${error.code??"unknown"}, durationMs=${Date.now()-started}): ${String(error.stdout??"")} ${String(error.stderr??error.message??"")}`.trim());}}});
 return r;
}
