import {randomUUID} from "node:crypto";import os from "node:os";import type {Provider} from "@loom/core";import {AdaptiveOrchestrator} from "@loom/adaptive";import {StateStore} from "@loom/state";
export interface DaemonOptions {heartbeatIntervalMs?:number;staleAfterMs?:number;leaseMs?:number;pollMs?:number;maxConcurrentJobs?:number;shutdownGraceMs?:number;provider?:Provider;jobRunner?:JobRunner;botSupervisor?:BotSupervisor;}
export interface BotSupervisor {start():Promise<void>;stop():Promise<void>;status?():unknown}
export interface ManagedBot {id:string;start():Promise<void>;stop():Promise<void>;status?():unknown}
export class ManagedBotSupervisor implements BotSupervisor {private states=new Map<string,any>();constructor(private readonly bots:ManagedBot[]){ }async start(){await Promise.all(this.bots.map(async bot=>{try{await bot.start();this.states.set(bot.id,{id:bot.id,status:"connected"});}catch(error){this.states.set(bot.id,{id:bot.id,status:"degraded",lastError:String(error)});}}));}async stop(){await Promise.all(this.bots.map(async bot=>{try{await bot.stop();}finally{this.states.set(bot.id,{...(this.states.get(bot.id)??{id:bot.id}),status:"stopped"});}}));}status(){return [...this.states.values()];}}
export interface JobRunner {run(job:any,daemon:Daemon):Promise<{status:"completed"|"failed"|"cancelled";rootAgentId?:string;summary?:string;retryable?:boolean;error?:string}>}
export interface DaemonStatus {running:boolean;daemonId?:string;startedAt?:number;heartbeatAt?:number;queue:{queued:number;running:number;retrying:number;failed:number};scheduler:{enabled:boolean;schedules:number;nextRunAt?:number};bots?:unknown}
export function nextScheduleAt(kind:string,expression:string,from=Date.now()):number|undefined {if(kind==="once")return Date.parse(expression);const m=/^(\d+)\s*(m|min|h|hour|d|day)s?$/i.exec(expression);if(m){const n=Number(m[1]),u=m[2].toLowerCase();return from+n*(u.startsWith("m")?60000:u.startsWith("h")?3600000:86400000);}if(kind==="cron"){const parts=expression.trim().split(/\s+/);if(parts.length!==5)throw new Error("cron requires 5 fields");const d=new Date(from);d.setSeconds(0,0);const minute=parts[0]==="*"?d.getMinutes()+1:Number(parts[0]),hour=parts[1]==="*"?d.getHours():Number(parts[1]);if(!Number.isInteger(minute)||minute<0||minute>59||!Number.isInteger(hour)||hour<0||hour>23)throw new Error("invalid cron time");d.setUTCHours(hour,minute,0,0);if(d.getTime()<=from)d.setUTCDate(d.getUTCDate()+1);return d.getTime();}throw new Error(`unsupported schedule kind: ${kind}`)}
export class DefaultJobRunner implements JobRunner {constructor(private readonly state:StateStore,private readonly provider:Provider){}async run(job:any):Promise<any>{const payload=typeof job.payload==="string"?JSON.parse(job.payload):job.payload;const root=job.rootAgentId??this.state.createAgentRecord({goal:payload.goal,role:"planner"}).id;if(!job.rootAgentId)this.state.updateJob(job.id,"claimed",{rootAgentId:root});const plan=await new AdaptiveOrchestrator(this.state,this.provider).run(root,payload.goal);const agent=this.state.getAgent(root);if(agent?.status==="cancelled")return {status:"cancelled",rootAgentId:root};if(plan.status==="completed")return {status:"completed",rootAgentId:root,summary:agent?.result};return {status:"failed",rootAgentId:root,error:agent?.error??"agent execution failed",retryable:agent?.status!=="failed"};}}
export class Daemon {readonly daemonId=`daemon_${randomUUID()}`;private running=false;private stopping=false;private heartbeatTimer?:ReturnType<typeof setInterval>;private pollTimer?:ReturnType<typeof setInterval>;private active=0;private readonly options:Required<Pick<DaemonOptions,"heartbeatIntervalMs"|"staleAfterMs"|"leaseMs"|"pollMs"|"maxConcurrentJobs"|"shutdownGraceMs">>;constructor(readonly state:StateStore,options:DaemonOptions={}){this.options={heartbeatIntervalMs:5000,staleAfterMs:20000,leaseMs:30000,pollMs:1000,maxConcurrentJobs:4,shutdownGraceMs:15000,...options};this.runner=options.jobRunner??(options.provider?new DefaultJobRunner(state,options.provider):undefined);this.botSupervisor=options.botSupervisor;}
 private readonly runner?:JobRunner;private readonly botSupervisor?:BotSupervisor;async start(){if(this.running)return;this.state.startDaemon({daemonId:this.daemonId,pid:process.pid,hostname:os.hostname(),version:"0.7.0",staleAfterMs:this.options.staleAfterMs});this.running=true;this.state.recoverStaleJobs(Date.now()+this.options.leaseMs,Date.now());this.state.addTrace("daemon", "daemon.started",{daemonId:this.daemonId});await this.botSupervisor?.start();this.heartbeatTimer=setInterval(()=>{if(this.running)this.state.heartbeatDaemon(this.daemonId)},this.options.heartbeatIntervalMs);this.pollTimer=setInterval(()=>void this.tick(),this.options.pollMs);await this.tick();}
 async tick(){if(!this.running||this.stopping)return;this.materializeSchedules();while(this.active<this.options.maxConcurrentJobs){const job=this.state.claimNextJob(this.daemonId,this.options.leaseMs);if(!job)break;this.active++;void this.execute(job).finally(()=>{this.active--;});}}
 private materializeSchedules(){const now=Date.now();for(const schedule of this.state.listSchedules()){if(!schedule.enabled||!schedule.nextRunAt||schedule.nextRunAt>now)continue;try{this.state.materializeSchedule(schedule.id,schedule.nextRunAt,JSON.parse(schedule.payload));const next=nextScheduleAt(schedule.kind,schedule.expression,schedule.nextRunAt);this.state.updateSchedule(schedule.id,{lastRunAt:schedule.nextRunAt,nextRunAt:schedule.kind==="once"?undefined:next,enabled:schedule.kind!=="once"});this.state.addTrace("daemon","schedule.materialized",{scheduleId:schedule.id,intendedRunAt:schedule.nextRunAt});}catch(error){this.state.updateSchedule(schedule.id,{errorMessage:String(error),enabled:false});}}}
 private async execute(job:any){this.state.updateJob(job.id,"running",{claimedBy:this.daemonId,leaseExpiresAt:Date.now()+this.options.leaseMs});try{if(!this.runner)throw new Error("daemon provider/job runner is not configured");const result=await this.runner.run(job,this);if(result.status==="completed")this.state.updateJob(job.id,"completed",{rootAgentId:result.rootAgentId,resultSummary:result.summary});else if(result.status==="cancelled")this.state.updateJob(job.id,"cancelled",{rootAgentId:result.rootAgentId,errorMessage:result.error});else if(result.retryable&&job.attempt<job.maxAttempts)this.state.updateJob(job.id,"retry_wait",{rootAgentId:result.rootAgentId,errorMessage:result.error,availableAt:Date.now()+Math.min(30000,5000*2**Math.max(0,job.attempt-1))});else this.state.updateJob(job.id,"failed",{rootAgentId:result.rootAgentId,errorMessage:result.error});}catch(error){if(job.attempt<job.maxAttempts)this.state.updateJob(job.id,"retry_wait",{availableAt:Date.now()+Math.min(30000,5000*2**Math.max(0,job.attempt-1)),errorMessage:String(error)});else this.state.updateJob(job.id,"failed",{errorMessage:String(error)});}}
 async stop(){if(!this.running||this.stopping)return;this.stopping=true;this.state.addTrace("daemon","daemon.stopping",{daemonId:this.daemonId});if(this.pollTimer)clearInterval(this.pollTimer);if(this.heartbeatTimer)clearInterval(this.heartbeatTimer);await this.botSupervisor?.stop();const deadline=Date.now()+this.options.shutdownGraceMs;while(this.active>0&&Date.now()<deadline)await new Promise(r=>setTimeout(r,25));this.state.stopDaemon(this.daemonId);this.running=false;this.state.addTrace("daemon","daemon.stopped",{daemonId:this.daemonId});}
 async status():Promise<DaemonStatus>{const jobs=this.state.listJobs();const schedules=this.state.listSchedules();const d=this.state.getDaemon(this.daemonId);return {running:this.running,daemonId:this.daemonId,startedAt:d?.startedAt,heartbeatAt:d?.heartbeatAt,queue:{queued:jobs.filter(j=>j.status==="queued").length,running:jobs.filter(j=>j.status==="running"||j.status==="claimed").length,retrying:jobs.filter(j=>j.status==="retry_wait").length,failed:jobs.filter(j=>j.status==="failed").length},scheduler:{enabled:true,schedules:schedules.length,nextRunAt:schedules.filter(s=>s.enabled).map(s=>s.nextRunAt).filter(Boolean).sort((a,b)=>a-b)[0]},bots:this.botSupervisor?.status?.()};}}
