import {describe,expect,it} from "vitest";
import {AdaptiveOrchestrator,ModelAdaptivePlanner,MultiRoundExecutor,SemanticReviewer,selectRole,selectTests,validatePlan} from "./index";
import {StateStore} from "@loom/state";
import type {Provider,ProviderResponse} from "@loom/core";
class SequenceProvider implements Provider {readonly name="sequence"; private i=0; constructor(private readonly responses:ProviderResponse[]){} async complete(){return this.responses[Math.min(this.i++,this.responses.length-1)]} }
describe("V0.6 adaptive runtime",()=>{
 it("rejects cycles and falls back to a valid deterministic DAG",async()=>{const bad=new SequenceProvider([{content:JSON.stringify({summary:"bad",tasks:[{id:"a",title:"a",description:"a",role:"coder",dependencies:["b"]},{id:"b",title:"b",description:"b",role:"coder",dependencies:["a"]}]})}]); const planner=new ModelAdaptivePlanner({provider:bad}); const p=await planner.plan({goal:"fix",availableRoles:["researcher","coder","tester"]}); expect(p.source).toBe("fallback"); expect(validatePlan(p,{goal:"fix",availableRoles:["researcher","coder","tester"]}).valid).toBe(true);});
 it("selects compatible role and targeted tests",()=>{expect(selectRole(["code-editing","testing"],[{role:"researcher",capabilities:["research"]},{role:"coder",capabilities:["code-editing","testing"]}]).role).toBe("coder"); expect(selectTests({changedFiles:["src/parser.ts"],knownTestFiles:["src/parser.test.ts","src/other.test.ts"],task:{id:"x",title:"x",description:"x",dependencies:[]}}).level).toBe("targeted");});
 it("executes multiple provider/tool rounds with checkpoints",async()=>{const provider=new SequenceProvider([{content:"read",toolCalls:[{id:"1",name:"read_file",input:{path:"x"}}]},{content:"done"}]);let calls=0,rounds=0;const result=await new MultiRoundExecutor(provider,{tool:async()=>{calls++;return "content"},checkpoint:async()=>{rounds++}},{maxModelRounds:3}).run({taskId:"t",goal:"g",messages:[{role:"user",content:"g"}]}); expect(result.status).toBe("completed"); expect(result.rounds).toBe(2); expect(calls).toBe(1); expect(rounds).toBe(2);});
 it("persists an adaptive plan and resumes without duplicating it",async()=>{const state=new StateStore(":memory:");const agent=state.createAgent("fix parser");const provider=new SequenceProvider([{content:"done"}]);const orchestration=new AdaptiveOrchestrator(state,provider);const first=await orchestration.run(agent.id,"fix parser");expect(first.status).toBe("completed");expect(state.listPlanRevisions(first.id)).toHaveLength(1);expect(state.listPlanTasks(first.id).length).toBeGreaterThan(0);const second=await orchestration.run(agent.id,"fix parser");expect(second.id).toBe(first.id);expect(state.listPlanRevisions(first.id)).toHaveLength(1);expect(state.getSchemaVersion()).toBeGreaterThanOrEqual(6);state.close();});
 it("uses deterministic review evidence",async()=>{const r=await new SemanticReviewer().review({goal:"g",task:{id:"t",title:"t",description:"t",dependencies:[]},agentResult:"done",testResults:["exit 0"]}); expect(r.verdict).toBe("accept");});
});
